### ISSUE TITLE
Support concurrent.futures?

### ISSUE THREAD

**Issue by wcmiracle** [rsalmei/alive-progress#100]
i want to ues

import multiprocessing
from concurrent.futures import ProcessPoolExecutor

support it?

**Comment by rsalmei** [comment]
Hello again.

Sure it supports!
But only one bar can be visible in the screen, that's the only limitation.
Here is an example:
![asd](https://user-images.githubusercontent.com/6652853/129527899-da83e8ae-eb23-448b-8ebc-40dddf343b04.gif)


The code (save in a file.py and run `python file.py`):
```python
from concurrent.futures import ProcessPoolExecutor, as_completed
from alive_progress import alive_bar
import time, random

def process(work):
     time.sleep(random.random())
     return work

if __name__ == '__main__':
    workables = [x for x in range(20)]

    with alive_bar(len(workables)) as bar:
        with ProcessPoolExecutor(max_workers=3) as pool:
            futures = [pool.submit(process, work) for work in workables]
            for future in as_completed(futures):
                print('work done:', future.result())
                bar()
    print('Ok! Everything done.\n')
```

**Comment by wcmiracle** [comment]
Thank you very much for the example, it will help others.

**Comment by rsalmei** [comment]
You're welcome man.
