### ISSUE TITLE
Different display in different places (system compatibility)

### ISSUE THREAD

**Issue by wcmiracle** [rsalmei/alive-progress#101]
## code
```
from alive_progress import alive_bar;import time

with alive_bar(1000) as bar:
	for i in range(1000):

		if i %100 ==0:
			print('found')
		time.sleep(0.01)
		bar()
```

# Linux
![linux](https://user-images.githubusercontent.com/5827857/129493290-313820b3-e9c2-48fa-b43c-3cb0380e1ad4.gif)

# Windows
![windows](https://user-images.githubusercontent.com/5827857/129493312-9ea6be9d-06bb-437e-bbbd-ce92c3bb21cb.gif)

# Pycharm
![Pycharm](https://user-images.githubusercontent.com/5827857/129493313-92e8f434-58be-47ad-b65c-30e11f731cd9.gif)

**Comment by rsalmei** [comment]
Hey @wcmiracle, those are not problems, just different platforms, with different behaviors.
Linux is the standard one, it just works.

Windows has a bug that ANSI escape codes do not work by default, to make they work you have to:
```python
import os
os.system('')
```
(In the soon-to-be-released 2.0 this is sent automatically)

PyCharm do not emulate complete terminals, it isn't interactive.
So you have to both:
1. Enable this in your run configuration:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/6652853/129524618-ea5bb824-8239-4394-8d9b-8625e2c30f3a.png">
2. Send `force_tty=True` to `alive_bar`.

Ok? That should make those all work as expected 👍

**Comment by wcmiracle** [comment]
Thank you very much for answering my confusion, I prefer progress to tqdm and hope you can make it very good.

**Comment by rsalmei** [comment]
Great, you're welcome!
