### ISSUE TITLE
alive-bar spam bar over instead of replacing

### ISSUE THREAD

**Issue by comand100vip** [rsalmei/alive-progress#102]
Then I try to look at progress bars that I can use with that code:
```
from alive_progress import alive_bar, show_bars
show_bars()
```
Instead of replacing old bar with new one so it gives nice effect it just spam new one over console.
![image](https://user-images.githubusercontent.com/82674108/129617546-5353e0b8-770c-4965-9de9-401fca4e188b.png)

**Comment by rsalmei** [comment]
Hey @comand100vip,

This released version needs vertical space to keep all on screen at the same time.
The new 2.0, still unreleased, does support smaller numbers of cols and rows terminals.
Also, Windows and Pycharm have special requirements, please see #101, I just answered that 👍

**Comment by comand100vip** [comment]
Thanks!

**Comment by comand100vip** [comment]
So... Itried this and it didn't work...
```
from alive_progress import show_bars
import os
os.system('')
show_bars()
```
Still exact same result.

**Comment by rsalmei** [comment]
Do you have sufficient vertical space? How many rows on your terminal?
Like I said, the unreleased 2.0 is able to show only what happens to fit the screen, but 1.x can't.
If you can't make more space for it, try with 2.0:
```sh
pip install git+https://github.com/rsalmei/alive-progress.git@rsa-refac
```

**Comment by comand100vip** [comment]
It gives me this error:
![image](https://user-images.githubusercontent.com/82674108/129777703-6dc38aed-d355-4f5f-911f-73158d738f77.png)

**Comment by rsalmei** [comment]
Ok, you can try the 2.0 again, I've fixed the default encoding on Windows.

But on 1.x, did you try just increasing the number of rows on your terminal?

**Comment by comand100vip** [comment]
Installed but...
![image](https://user-images.githubusercontent.com/82674108/129787830-b5a60734-fbff-4d93-8417-5d7385b221b0.png)

**Comment by rsalmei** [comment]
Great that it installed!

Yes, the imports are different now:
```python
from alive_progress.styles import show_bars
```

**Comment by comand100vip** [comment]
Everything works, but showtime and show_bars, have same issue. Hey are spaming over, and sound of windows error is that spamed that I here \*pop\* but like from mashine gun and after I turned program off sound continue for like next 10 seconds.

**Comment by rsalmei** [comment]
Humm, I didn't quite understand... Care to explain it better?
Did showtime and show_bars actually work or not? Maybe you could make a small video or gif so I can see it.

**Comment by comand100vip** [comment]
Normal by user made bars works, but show_bars and showtime doesn't.
https://user-images.githubusercontent.com/82674108/129858344-24751cb2-0633-40a3-b6fd-bf9568e8f349.mp4

**Comment by comand100vip** [comment]
And I want ask what that part of bar mean:
![image](https://user-images.githubusercontent.com/82674108/129890628-ab21252f-5073-4840-92fc-61c7a2d5cb57.png)
And if it is possible, how to edit/remove that?

**Comment by rsalmei** [comment]
Ok, did you read #101 like I told you?
It is not working because your pycharm terminal isn't emulating ANSI Escape Codes.
Those symbols are the codes terminals use to accept commands, like clear the line, or move the cursor.

**Comment by comand100vip** [comment]
>  Send `force_tty=True` to `alive_bar`.

Ummm, where do I sent that?

**Comment by rsalmei** [comment]
This one you send to `alive_bar`, to make it run animations even when the terminal reports it is not interactive (used on PyCharm's terminal usually):

```python
with alive_bar(total, force_tty=True) as bar:
    ...
```

The `show_bars` and `showtime` do not have such option, since you should always be in an interactive one.
For these in PyCharm, just enable:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/6652853/130028940-2157752b-256c-4cfd-89e1-184003fff7f5.png">

**Comment by comand100vip** [comment]
I ahev completly no idea what's wrong here
I arledy set in Pycharm to emulate console and everything should be fine
```
from alive_progress.styles import showtime
import os

os.system('')
showtime()
```

**Comment by comand100vip** [comment]
Still didn't work.
![Uploading image.png…]()
I will record the sound of it. (it is spaming errors and sound like bop bop bop)

**Comment by rsalmei** [comment]
Well, you're missing a better font too, that would solve those huge amount of "?", which are unknown characters.
Install some from https://www.nerdfonts.com/, they are awesome.

Regarding your terminal, it is still not interpreting any ANSI control chars. You can see those "←[K" on the end of each line...
How exactly did you started it? Did you use `ipython` or a vanilla `python`?

Well, that's weird. I've just tried on PyCharm's terminal, and it works flawlessly for me, but I'm on macOS.
This is what you should see for 2.0:
![asd](https://user-images.githubusercontent.com/6652853/130038581-090787b8-ec81-4bb6-ae9b-b4e016d5ae1c.gif)

**Comment by comand100vip** [comment]
I am using `python`, and where do I put those fonts?
So later then I compile that can be used on others computers.

**Comment by rsalmei** [comment]
You should set a nerd-font as your terminal font.
There's loads of cool ones, like VictorMono (the one I use), SourceCodePro, Dejavu, Firacode, Hack, etc.
On my terminal:
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/6652853/130040135-2ad4f41e-2bdd-4ed0-a870-98218212ddd5.png">

**Comment by comand100vip** [comment]
I just can't get any font to work with windows.
Nothing shows up after installing those fonts and later the problem will be that then I compile my program it will need be installed on second computer and that is not the best solution, maybe there is way to use those fonts with python code?

**Comment by comand100vip** [comment]
Okay I installed and used hack font, buuuuuuut still....
![image](https://user-images.githubusercontent.com/82674108/130097791-db83e812-1605-47e1-afa1-72af01f42f97.png)

**Comment by rsalmei** [comment]
Are you sure you installed Hack as the terminal font? It doesn't seem different...

Anyway, I don't understand why the ANSI codes are still not being interpreted. 🤔
I've had other reports that say `os.system('')` does make them work on Windows.

I can't say what more to try, I need your help to try more things.
What Python are you using? How did you installed it?
What terminal?

**Comment by comand100vip** [comment]
Python 3.9
Installed via .exe package with adding to path and PIP
Default cmd (also known as Command Prompt) in windows 8.1 (NOT powershell)
![image](https://user-images.githubusercontent.com/82674108/130113490-17fcbbc7-66f9-4bb0-a339-5c4f5814d01a.png)

**Comment by rsalmei** [comment]
Humm, this does not seem a nerd font... Did you download and install from https://www.nerdfonts.com?

**Comment by comand100vip** [comment]
Those are a little bit... _Broken_
Cmd just don't see and can't use them because of the F$(%^$^^ requments acurding to font, so I donwloaded "Fixed" from here:
[](https://github.com/haasosaurus/nerd-fonts/tree/regen-mono-font-fix/patched-fonts/Hack)

**Comment by rsalmei** [comment]
Ok, unfortunately it seems the "?" didn't change that much.
And Python, you said you "installed via .exe", you mean the official package in python.com?

**Comment by comand100vip** [comment]
Yes, python.org

**Comment by comand100vip** [comment]
I was doing some resarch and i think only windows 10 support ANSI Escape codes, it looks like windows 8.1 or older version didn't support it. :/
https://en.wikipedia.org/wiki/ANSI_escape_code
Section: DOS, OS/2, and Windows

**Comment by rsalmei** [comment]
WOW, I wasn't aware of that!! 😨
So... unfortunately there's nothing we can do to make it work 😞
Probably even that fix I've made for the encoding on "Windows" was unneeded. Windows 10 must have changed it to UTF-8, since no one had ever reported that...

But ok, I tried. You should update to Win10...

**Comment by TheTechRobo** [comment]
As I said in a previous issue : Colorama might solve this issue.  
It turns ascii codes into actual API calls.

I successfully used ascii codes in my repo https://github.com/TheTechRobo/python-text-calculator , you can see colorama here: https://github.com/TheTechRobo/python-text-calculator/blob/master/palc.py#L55-L59

@command100vip could you try adding 

```
import colorama
colorama.init()
```
to the start of the file? (You'll need to `pip install colorama` first)

**Comment by comand100vip** [comment]
Almost, it almost, but not quite.
It replace symbols but still spam it over conole,
but maybe a little slower.
But as you can see on image below some ansi escape codes is still not working but it is so close to solving that.
![image](https://user-images.githubusercontent.com/82674108/130805457-ad436322-92e2-46b4-b093-ce4d28026605.png)

**Comment by TheTechRobo** [comment]
Hmm, colorama might not support it.

@rsalmei here's the list of supported codes, is there any one missing?

https://github.com/tartley/colorama#recognised-ansi-sequences

If there is, we can file an Issue.
