### ISSUE TITLE
PyCharm console - terminal ANSI escape codes not following force_tty

### ISSUE THREAD

**Issue by Perik86** [rsalmei/alive-progress#105]
Hello, 
since updating to the newest version, the alive progress bar does not work in Pycharm Ipython or standard console anymore (it worked before updating), even though it works perfectly fine when running the code in Ipython through the terminal (force_tty=True in both cases)! Does anyone know how to fix this and sorry if has already been mentioned/resolved before.

Here's a screen:
![Screenshot_5](https://user-images.githubusercontent.com/89874073/131570997-ce6a2931-5203-4d1b-9ad1-b7b6e4607e38.png)
Thank you in advance!

**Comment by rsalmei** [comment]
Hello @Perik86, you're welcome.

Humm, I see... Indeed PyCharm (which I do not use to run anything myself) is not reporting itself as interactive 😞 
<img width="690" alt="image" src="https://user-images.githubusercontent.com/6652853/131606789-57690658-f8d8-46fc-a8bc-267b74c855a1.png">

I don't actually remember why I've made this change, but certainly it was to fix some issue...
I'm going to try to find it, and then report back.

**Comment by rsalmei** [comment]
Got lucky, found it: https://github.com/rsalmei/alive-progress/issues/55

When we pipe the output into another process, the terminal is not interactive anymore.
It is kinda why I implemented `force_tty` in the first place, to force animations in this case.
But those escape codes, which clear the line and make the cursor return, where also being printed when they shouldn't.
Now they aren't when they should, at least are being forced to.
I'm going to fix it asap!

**Comment by rsalmei** [comment]
Hey, the PR is ready to fix this! #111 
I'll release it very soon...

**Comment by rsalmei** [comment]
Hey, version `2.1` is released!!
This should be fixed, please report back if anything new arises.
