### ISSUE TITLE
Can't the title be changed dynamically?

### ISSUE THREAD

**Issue by dugudongfangshuo** [rsalmei/alive-progress#106]
pbar = alive_it(range(10),title="123")
for i in pbar:
    pbar.title ="12"

no response

**Comment by rsalmei** [comment]
Humm, it can't, but you can change the `.text()`.
I think a processing has always a title, and you put "situational messages" with `.text()`.
Does that work for you?

**Comment by rsalmei** [comment]
Hello @dugudongfangshuo,
This is done! I'm going to release it today 👍
