### ISSUE TITLE
IDLE breaks stdout

### ISSUE THREAD

**Issue by borderline23** [rsalmei/alive-progress#109]
from alive_progress import alive_bar

with alive_bar(1000) as bar:
    for i in compute():
        bar()

////////////////////////////////////////////////////////////

Traceback (most recent call last):
  File "C:\Users\erman\Desktop\prova.py", line 1, in <module>
    from alive_progress import alive_bar
  File "C:\Users\erman\AppData\Local\Programs\Python\Python39\lib\site-packages\alive_progress\__init__.py", line 2, in <module>
    from .core.progress import alive_bar, alive_it
  File "C:\Users\erman\AppData\Local\Programs\Python\Python39\lib\site-packages\alive_progress\core\progress.py", line 10, in <module>
    from ..utils.cells import combine_cells, fix_cells, print_cells, to_cells
  File "C:\Users\erman\AppData\Local\Programs\Python\Python39\lib\site-packages\alive_progress\utils\cells.py", line 63, in <module>
    def print_cells(fragments, cols, last_line_len=0, _write=sys.__stdout__.write):  # noqa
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by TheTechRobo** [comment]
Why in the Lord's name is sys.stdout None?

**Comment by borderline23** [comment]
> 
> 
> Why in the Lord's name is sys.stdout None?

i don't know i just use:
pip install alive-progress

and try the code in a new .py file

**Comment by rsalmei** [comment]
> Why in the Lord's name is sys.stdout None?

Yeah, he is right! WHY?
The imports were just starting to execute, and the default param I've set for `_write` can't resolve `sys.stdout.write`??
That doesn't make any sense.
Please give me more info:
- What python are you using? 
- What is the exact program you tried to run? 
- How did you call it? 
- Where did you call it, shell or ipython?

**Comment by borderline23** [comment]
sorry man i m not a professional coder..
i just installed alive-progress with pip
and put the  example code in new .py so the code is:

from alive_progress import alive_bar

with alive_bar(1000) as bar:
for i in compute():
bar()

python version 3.9 64bit
i run that code from IDLE - RUN - RUN MODULE

> 
> 
> > Why in the Lord's name is sys.stdout None?
> 
> Yeah, he is right! WHY? The imports were just starting to execute, and the default param I've set for `_write` can't resolve `sys.stdout.write`?? That doesn't make any sense. Please give me more info:
> 
>     * What python are you using?
> 
>     * What is the exact program you tried to run?
> 
>     * How did you call it?
> 
>     * Where did you call it, shell or ipython?

sorry man i m not a professional coder..
i just installed alive-progress with pip
and put the  example code in new .py so the code is:

from alive_progress import alive_bar

with alive_bar(1000) as bar:
  for i in compute():
  bar()

python version 3.9 64bit
i run that code from IDLE - RUN - RUN MODULE

**Comment by rsalmei** [comment]
Ahhh I see, it's that IDLE thing...
It is not a Python environment, it is a program running in it only.
And programs can do whatever they want, this one in particular is known to break stuff.

Anyway, you can run your `prog.py` directly in the shell:
```
> python prog.py
```

And to experiment and explore python, i recommend ipython, it's awesome! Just:
```
> pip install ipython
```
And then start it: `ipython`. In there you can write and test code at the same time, and reuse past inputs and outputs.

**Comment by rsalmei** [comment]
OK, I'm closing this one, as it's not a problem.

**Comment by TheTechRobo** [comment]
@rsalmei Offtopic but I'm curious: Have you ever tried https://github.com/bpython/bpython? It looks pretty cool, but I haven't tried it myself

**Comment by rsalmei** [comment]
Hey @TheTechRobo, YES!
It was once my favorite Python REPL, but unfortunately it wasn't working anymore last time I've checked...
I don't recall exactly what was the problem, it was long ago, ~3 years, but I had to switch to `ipython`, and started recommending it instead.
But do try it! And let me know if it is working nowadays... 👍

**Comment by TheTechRobo** [comment]
@rsalmei Seems to work fine for me!

![image](https://user-images.githubusercontent.com/52163910/140431048-8ec770bc-bde4-4259-b3fb-d1bb5d28473e.png)

**Comment by rsalmei** [comment]
Cool! It is awesome to discover new frameworks, with that auto-docstrings panel! 👍
