### ISSUE TITLE
[FR] - Option to not print final result

### ISSUE THREAD

**Issue by bobokun** [rsalmei/alive-progress#120]
Sorry if I missed this option, but I wasn't clear if it is currently possible to choose not to print out the final bar once it reaches 100%. I would like to able to see the progress bar but once it's complete it does not stay in the terminal and the bar disappears completely

**Comment by TheTechRobo** [comment]
Try this? https://github.com/rsalmei/alive-progress/issues/72#issuecomment-757506351

**Comment by bobokun** [comment]
I tried to set the config but it doesn't solve the problem. 
`config_handler.set_global(bar=None, receipt_text=False)`
After completion it still shows the final output printed out
![image](https://user-images.githubusercontent.com/12660469/145844477-39e8879a-8d8b-470e-a5aa-065bc0b1f123.png)

I'm using the `alive_it` function

**Comment by TheTechRobo** [comment]
What's your code?

**Comment by rsalmei** [comment]
Hello @bobokun,

No, there isn't an option to completely ignore the final receipt.
As you have seen, the option you've tried is called `receipt_text`, i.e. it removes or shows the last **situational text** you may have set while the bar was running.

No one has ever asked this, but it should be easy enough to support.
Just the new config parameter for this could maybe give some trouble, but I can do it _eventually_.
At the moment I'm very involved with Rust and a new job I've recently started.

**Comment by bobokun** [comment]
Great thank you!

**Comment by rsalmei** [comment]
Hello @bobokun, I'm glad to inform you this is ready!
I should be releasing it today, if everything goes OK.

![Untitled](https://user-images.githubusercontent.com/6652853/151723001-84a6c0d1-1b2a-4c27-9697-94ed62499f2a.gif)

**Comment by bobokun** [comment]
Is this available for me to test in a branch or is the release coming soon?

**Comment by rsalmei** [comment]
Not yet, but the release is very soon!
I ended up implementing a bunch of other stuff together with this, so I'm polishing them up and then write the readme and changelog. I'll probably release it tomorrow.

**Comment by rsalmei** [comment]
Hey, it is released! #131 
Take a look at the new readme for details! 🎉

**Comment by bobokun** [comment]
Thanks! It's working perfectly :)

**Comment by rsalmei** [comment]
That's great to hear!! 😃 
You're welcome!

**Comment by takanuva15** [comment]
For anyone in the future who comes here trying to figure out how to _not_ show the final bar when the progress completes, just add `receipt=False` to the keyword arguments in the `alive_bar` method.
ie: `with alive_bar(receipt=False):`

(Also I just discovered this library today and it's one of the most legit things I've ever seen in Python!)

**Comment by rsalmei** [comment]
Thanks, man 👍
