### ISSUE TITLE
Progress bar only shows up after entire cell is executed

### ISSUE THREAD

**Issue by zenodallavalle** [rsalmei/alive-progress#121]
Progress bar only shows up after entire notebook's cell is executed.

Video of the behaviour in attachments.

https://user-images.githubusercontent.com/48842588/147406900-2effb3f2-f4d4-486d-8d44-6b07a750828d.mp4

[requirements.txt](https://github.com/rsalmei/alive-progress/files/7776924/requirements.txt)

MacBook Pro 14 M1 Pro, MAC OS X 12.1
VS Code 1.63.2 (November 2021)
Python 3.9.7
Installed packages, see attachments.

**Comment by rsalmei** [comment]
You forgot `force_tty`.

![alive-jupyter](https://user-images.githubusercontent.com/6652853/147425271-bddf78ea-0f5c-4bde-b1ad-f5c39e70d24b.gif)

**Comment by zenodallavalle** [comment]
Already tried with ‘force_tty=True‘, it hangs on forever.

https://user-images.githubusercontent.com/48842588/147448509-f6ac237a-61cf-4117-8b2f-aebbb44a44d2.mp4

**Comment by rsalmei** [comment]
Humm, that's very odd.
It seems some kind of caching within vscode itself.
What happens if you write a cell with a `print('asd')`, followed by a `time.sleep(10)`, both in the same cell?
Does the `asd` appear on screen immediately, or just after 10 seconds?

**Comment by zenodallavalle** [comment]
I tried with 
```
print('test1')
time.sleep(5)
```

`test1` is printed immediately, while cell's execution last 5 seconds, as expected.

**Comment by rsalmei** [comment]
OK, I'm almost out of ideas... Of course, it is something within vscode, but I'm not sure what.
In `alive-progress`, actually I print a little differently, try this:
```python
import sys
sys.stdout.write('testing')
sys.stdout.flush()
time.sleep(5)
```

**Comment by zenodallavalle** [comment]
I tried your code, it works as expected...

**Comment by zenodallavalle** [comment]
I also tried

```
with alive_bar(total=500) as bar:
    for i in range(500):
        time.sleep(.005)
        if i and i % 100 == 0:
            print('cool')
        bar()
```

And I get
```
on 100: cool
on 200: cool
on 300: cool
on 400: cool
|████████████████████████████████████████| 500/500 [100%] in 3.1s (160.99/s)
```

and

```
with alive_bar(total=500, force_tty=True) as bar:
    for i in range(500):
        time.sleep(.005)
        if i and i % 100 == 0:
            print('cool')
        bar()
```
And I get the same result as

>  vscode.bug.2.mp4

**Comment by zenodallavalle** [comment]
I think this should be set to open

**Comment by rsalmei** [comment]
Not yet @zenodallavalle.
I need to confirm it really does that in another machine.

**Comment by rsalmei** [comment]
Please help me here. I don't know what "Metaflow flow" is.
When you bring some exoteric environment that could add to the conversation, explain what it is. Show what you did.
I don't have the time to look for everything, let alone download it, install, learn how to use it, and finally try to simulate the issue.
Assume I do not know it, and just show me everything that could possibly help, will you? Thanks.
