### ISSUE TITLE
Progress Bar With ProcessExecutorPool

### ISSUE THREAD

**Issue by cielowu** [rsalmei/alive-progress#124]
Hi, 

I'm writing an IO-consuming script with a progress bar and I'd like to improve its speed using a ProcessPoolExecutor.

I'm following your example on  https://github.com/rsalmei/alive-progress/issues/75.
However, since I'm new to multi-processing in Python and I'm facing some issues on making it work.

Here's my code sample:
```python
def perform_query(query_end_time, resume_query_from=None):
    with open("processed_tasks.json", "r") as f:
        tasks = json.load(f)

    batch = 0
    if resume_query_from is not None:
        tasks = tasks[resume_query_from:]
        batch = resume_query_from / 1000

    total = len(tasks)
    with alive_bar(total) as bar, ProcessPoolExecutor(max_workers=2) as executor:
        try:
            start = 0
            while start < len(tasks):
                end = min(start + 1000, total)
                t = [(a, query_end_time) for a in tasks[start:end]]
                # perform_request is a simple requests call to an API and process the response
                futures = [executor.submit(perform_request, task) for task in t]
                query_responses = []
                for future in as_completed(futures):
                    bar()
                    query_responses.append(future.result())
                with open(f"processed_results_{batch}.json", "w") as f:
                    json.dump(query_responses, f)
                start += 1000
                batch += 1
        finally:
            executor.shutdown()
```

However, the above does not work, the progress bar is not updated.
![demo](https://user-images.githubusercontent.com/60362790/149207603-9bbb5796-ec95-49fc-b39b-83c66bbc1c6a.gif)

**Comment by TheTechRobo** [comment]
potentially related: #42

**Comment by rsalmei** [comment]
Hello @cielowu,

It seems another process is printing to stdout, you have to avoid that.
All the printing must be done through the main thread, the one where `alive-progress` is running.

Regarding the lack of progress, I think there wasn't any! We can see several stack traces popping up on the screen.
To make the base infrastructure work, you should put together the bare minimum, make It work, then continue.
Remove both the `perform_request` and the batch control, and you should see the problem clearly.

**Comment by rsalmei** [comment]
OK, going to close this one, as there isn't any problem here.
Please continue if you do need any more help 👍

**Comment by cielowu** [comment]
Hi @rsalmei, 

Thank you so much for the quick response and sorry for my delay. I notice it was my bug in which I submit the wrong method in the executor. However, I was testing something, I still did not get it why my progress bar is not updating.

here's my code

```python
import random
import time
from asyncio import as_completed
from concurrent.futures.process import ProcessPoolExecutor
from multiprocessing import cpu_count

from alive_progress import alive_bar


def rand_sleep():
    print("start sleep")
    time.sleep(random.randint(5, 10))
    print("end sleep")

    return 1


def test():
    with alive_bar(1000, force_tty=True) as bar, ProcessPoolExecutor(max_workers=cpu_count()) as executor:
            futures = {
                executor.submit(rand_sleep): a for a in range(1000)
            }
            for future in as_completed(futures):
                bar()
                print(f"Done {futures[future]}")


if __name__ == "__main__":
    test()
```
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/60362790/149835920-fd30cc0e-80c1-4d97-b997-dd89a3278c38.gif)

Notice in the video, `end sleep` was printed out in the terminal, while the progress bar is not updated? What did I miss?

**Comment by cielowu** [comment]
Hi @rsalmei,

Thanks so much for the quick response. Thanks for your suggestion and I found several bugs I have in my code and it is working now.

**Comment by rsalmei** [comment]
Great @cielowu, you're welcome!
