### ISSUE TITLE
Request for usage help on Loop-less use

### ISSUE THREAD

**Issue by dralquinta** [rsalmei/alive-progress#126]
I love this project! However I'm struggling in following the documentation on Loop-less usage. Hopefully I can get your help in understanding it as I need to have a progress bar for a very CPU intensive project I'm working on. This is how it goes. 

Current project is reporting the entries like this (on red arrow, I wanna have a progress bar)

![image](https://user-images.githubusercontent.com/51421891/149545731-02a75bc7-ed13-4a1f-8eab-55ae251be2f0.png)

The implementation of this, first will print out a static header and then the dynamic entries listed as points 1.1, 1.2, 1.N, X.Y will be on a Loopless Implementation like this: 

```python
def main_orchestrator(config,signer, report_directory):
    print_header("Fireup "+Statics.__version__)
    print_report_sub_header()

    __call_1_1(config, signer, report_directory)
    __call_1_2(config, signer, report_directory)
    __call_1_3(config, signer, report_directory)
    __call_1_4(config, signer, report_directory)
    __call_1_5(config, signer, report_directory)
    __call_1_6(config, signer, report_directory)
    __call_1_7(config, signer, report_directory)
    __call_1_8(config, signer, report_directory)
    __call_1_9(config, signer, report_directory)
    __call_1_10(config, signer, report_directory)
    __call_1_11(config, signer, report_directory)
    __call_1_12(config, signer, report_directory)
...
...
...
```

By following the documentation, I figured that this was somewhat the right way of doing it: 

```python
def main_orchestrator(config,signer, report_directory):
    print_header("Fireup "+Statics.__version__)
    print_report_sub_header()

    with alive_bar(get_current_rps()) as bar:
        __call_1_1(config, signer, report_directory)
        bar()
        __call_1_2(config, signer, report_directory)
        bar()
        __call_1_3(config, signer, report_directory)
        bar()
        __call_1_4(config, signer, report_directory)
        bar()
```

However this will printout the progress bar after everything has finished, which somehow defeats the purpose of the bar in the first place :( 

![image](https://user-images.githubusercontent.com/51421891/149546243-762176fa-c0ce-48b5-8a7a-a64013986fe9.png)

I'm sure this is me not being able to follow the documentation, however I'd really appreciate some guidance!

**As a summary** 

- I'd like to have a fixed progressing bar on my header, that takes advantage of the loop-less capabilities published in documentation so then it auto-updates the progress while the points appearing on screen are progressing. 

Thanks

DA

**Comment by rsalmei** [comment]
Hello @dralquinta!
Thank you!

Actually, the bar will start rendering as soon as you enter the `with` context...
I think it may be taking some time to appear because of the very CPU-intensive processing you have told.
But your basic implementation is very correct!
In the docs, I went a little deeper by splitting the fixed steps more smoothly using [about-time](https://github.com/rsalmei/about-time), but if this basic setup gives you good results, that's great!

Anyway, you could try a small `time.sleep(1)`, just to see the bar running prior to any CPU-intensive calls:
```python
def main_orchestrator(config,signer, report_directory):
    print_header("Fireup "+Statics.__version__)
    print_report_sub_header()

    with alive_bar(get_current_rps()) as bar:
        time.sleep(1)  # you should see the bar rendition now!
        __call_1_1(config, signer, report_directory)
        bar()
        ...
```

You're welcome! 👍

**Comment by dralquinta** [comment]
Let me try that. 

I can also make it on a loop-ful implementation, so I'll try to put it like this and let you know. 

Thanks for the response!

DA

**Comment by dralquinta** [comment]
@rsalmei

So I made my updates following your advice and it definitely looks like I'm doing something wrong. I'll explain what I'm doing below: 

The orchestrator function looks like this: 

```python

def main_orchestrator(config,signer, report_directory):
    print_header("Fireup "+Statics.__version__)
    print_report_sub_header()

    with alive_bar(get_current_rps()) as bar:
        time.sleep(1)
        __call_1_1(config, signer, report_directory)
        bar()  
        __call_1_2(config, signer, report_directory)
        bar()
        __call_1_3(config, signer, report_directory)
        bar()
        __call_1_4(config, signer, report_directory)
        bar()
        __call_1_5(config, signer, report_directory)
        bar()
...
...
...
        __call_3_5(config, signer, report_directory)
        bar()
        __call_3_6(config, signer, report_directory)
        bar()
        __call_3_9(config, signer, report_directory)
        bar()
        __call_3_10(config, signer, report_directory)
        bar()
```

So as predicted, this is orchestrating the ordered call of a whole bunch of other functions. 

The first two functions called on `main_orchestrator()`which are `print_header()` and `print_report_subheader()` do this: 

```python
def print_header(msg):
    chars = int(Statics.__lenght_print__)
    print("")
    print('#' * chars)
    print("#" + turn_cyan(msg.center(chars - 2, " ")) + "#")
    print('#' * chars)
```

```python
def print_report_sub_header():
    print('Num' + "  " + " {:<40}".format(str("Area")) + " {:<70}".format(str("Sub-Area")) +
              " {:<5}".format(str("OK")) + " {:<5}".format(str("Findings")) + "   {:<50}".format(str("Review Point")), flush=True)
    print('#' * int(Statics.__lenght_print__), flush=True)
```

So as you see it's basic print on terminal, but using the flush=True option to make it go faster. 

Now, here's what's happening. I start running the process and I get entries such as this: 

```shell
########################################################################################################################################################################################################
#                                                                                            Fireup v0.0.10                                                                                            #
########################################################################################################################################################################################################
Num   Area                                     Sub-Area                                                               OK    Findings   Review Point                                      
########################################################################################################################################################################################################
23   11   8   0
on 0: 1.1   Security and Compliance                  Manage Identities and Authorization Policies                           No   47         Enforce the Use of Multi-Factor Authentication (MFA)
on 1: 1.2   Security and Compliance                  Manage Identities and Authorization Policies                           No   1          Don't Use the Tenancy Administrator Account for Day-to-Day Operations
on 2: 1.3   Security and Compliance                  Manage Identities and Authorization Policies                           No   0          Restrict the Admin Abilities of a Tenancy Administrators Group
on 3: 1.4   Security and Compliance                  Manage Identities and Authorization Policies                           No   0          Prevent Accidental or Malicious Deletion of (and Changes to) Access Policies
on 4: 1.5   Security and Compliance                  Manage Identities and Authorization Policies                           No   24         Federate Oracle Cloud Infrastructure Identity and Access Management
on 5: 1.6   Security and Compliance                  Manage Identities and Authorization Policies                           No   21         Monitor and Manage the Activities and Status of All Users
on 6: 1.7   Security and Compliance                  Isolate Resources and Control Access                                   No   234        Organize Resources Using Compartments and Tags
on 7: 1.8   Security and Compliance                  Isolate Resources and Control Access                                   No   170        Implement Role-Based Access Control
on 8: 1.9   Security and Compliance                  Isolate Resources and Control Access                                   No   89         Secure Cross-Resource Access
on 9: 1.10  Security and Compliance                  Isolate Resources and Control Access                                   No   156        Isolate Resources at the Network Layer
```

So as you see the progress bar is not rendered but on contraire I get the `on` iterator on screen. Eventually the bar will be printed out at the end, rendering correctly however defeating the purpose of the bar in the first place. (See below screenshot)

![image](https://user-images.githubusercontent.com/51421891/149579379-29331b48-2d0e-4dbb-9c7e-0f345fe04b21.png)


I'm unable to see what I'm doing wrong as I'm exactly following what the documentation says. I'm not aware of how the module works, however the only thing that can be causing a compatibility problem (that I can think of) is the usage of Flush option in my prints.

On the other side, I tried to make this loop-ful, however as I'm scheduling threads behind the hood here, it's not feassible to do it on the orchestrator. 

Any pointers are appreciated!

/DA

**Comment by dralquinta** [comment]
Update. 

`flush=True`does not seems to be the smoking gun :(

**Comment by rsalmei** [comment]
You're not doing anything wrong. It is correct.
Are you sure the bar does not show up in the sleep?
I think it definitely should. Maybe send a video of the first few seconds?

**Comment by dralquinta** [comment]
Yup. 100% for sure. 

Here's a video of the entire process. If you see, the sleep is indeed triggered and this spawns a 1 second gap and then all the entries start appearing. Only after last point is processed, progress bar appears rendered on screen (however already completed). 


https://user-images.githubusercontent.com/51421891/149786026-43fd7f0f-fa38-463e-90b0-13d83cb0c92d.mp4

**Comment by dralquinta** [comment]
I've ended up moving to tqdm as it was the only way I could make a progress bar work as I was expecting. Screenshot below: 

![image](https://user-images.githubusercontent.com/51421891/149828322-81cf7388-b64e-4e53-a120-faf66a10a8db.png)


Code was more simple as well: 


```python
from tqdm import tqdm

def main_orchestrator(config,signer, report_directory):
    print_header("Fireup "+Statics.__version__)
    print_report_sub_header()
    
    orchestrated_list = [   __call_1_1,
                            __call_1_2,
                            __call_1_3,
                            __call_1_4,
                            __call_1_5,
                            __call_1_6,
...
...
...
                            __call_3_6,
                            __call_3_9,
                            __call_3_10,
                         ]


    for i in tqdm(range(len(orchestrated_list)), bar_format='{l_bar}{bar} | {n_fmt}/{total_fmt} '):
        orchestrated_list[i](config,signer, report_directory)

```


I'm not really sure why this lib didn't work, unfortunately I don't have enough time to keep on investigating it. 

Thanks for the help anyways 👍
