### ISSUE TITLE
Progress Bar with executor.map()

### ISSUE THREAD

**Issue by shivanraptor** [rsalmei/alive-progress#127]
Similar to #124 , my logic relies on `executor.map()` instead of `executor.submit`. How can I apply the Alive Progress Bar in my logic? 

```
with Manager() as manager:
	file_list = manager.dict()
	with alive_bar(total) as bar, ProcessPoolExecutor() as executor:
		executor.map(time_consuming_function, [(jpg, file_list) for jpg in imgs])
```

Thanks.

**Comment by rsalmei** [comment]
Hello @shivanraptor 

The best examples are in #75, and #125 lists them all.
Going to close this one, as there is another open as you've seen.
