### ISSUE TITLE
Does the progress bar works in exe file???

### ISSUE THREAD

**Issue by ZardForever1009** [rsalmei/alive-progress#128]
I tried to compile my file into **.EXE** file, but it seems not working in the situation, the cmd said **" SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte".** And I am sure that my program working fine in **Python 3.10.1 and PyCharm 2021.3.1**

This is my code:
```
from alive_progress import alive_bar
import time,logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("stayin alive")

with alive_bar(1000) as bar:
    for i in range(1000):
        time.sleep(.005)
        if i and i % 300==0:
            print("haha")
        if i in (450,750):
            logger.info("cool")
        bar()
```

**Comment by TheTechRobo** [comment]
What are you using to freeze your Python code into a binary? If we don't know, we can't help at all.

Windoze is quite picky with unicode, so try running the EXE in the new Windows Terminal or something.

**Comment by ZardForever1009** [comment]
> What are you using to freeze your Python code into a binary? If we don't know, we can't help at all.
> 
> Windoze is quite picky with unicode, so try running the EXE in the new Windows Terminal or something.

I used the **Pyinstaller**, and I run the EXE file with **Fluent Ferminal** installed from Microsoft Store.
This is what it said after execution:
![image](https://user-images.githubusercontent.com/87600155/150237393-a0b9ba56-5335-451d-b0e9-b14f2bd9b521.png)
