### ISSUE TITLE
OSError using os.get_terminal_size()

### ISSUE THREAD

**Issue by yucongo** [rsalmei/alive-progress#129]
``alive-progress`` is very cool! Thanks for providing the package. It does not quit work in colab though.
```
from time import sleep
from alive_progress import alive_bar
with alive_bar(total=1, title="title text", manual=True, force_tty=True) as pbar:
  sleep(4)
  pbar(1)
```
This will hang (run forever). It probably has something to do with ``force_tty=True`` and ``os.get_terminal_size()`` since ``os.get_terminal_size()`` results in ``OSError: [Errno 25] Inappropriate ioctl for device`` in colab. (I was reading another issue and tested ``os.get_terminal_size()`` in colab.)

It runs without ``force_tty=True`` but the progress bar won't show up until the end. I have attached some info about colab's jupyter.

Colab' jupyter info
```
!jupyter --version
jupyter core     : 4.5.0
jupyter-notebook : 5.2.2
qtconsole        : 4.5.2
ipython          : 5.5.0
ipykernel        : 4.10.1
jupyter client   : 5.3.1
jupyter lab      : not installed
nbconvert        : 5.5.0
ipywidgets       : 7.5.0
nbformat         : 4.4.0
traitlets        : 4.3.2
```

**Comment by rsalmei** [comment]
Thanks man!

What is colab? I've never heard about it...

**Comment by TheTechRobo** [comment]
I assume Google Colab

**Comment by yucongo** [comment]
``alive_bar`` would also spit out errors in github's workflows. It's likely related to  ``os.get_terminal_size()`` since I guess workflows also operate in some virtual environment.

It would be nice if it can somehow be fixed. Currently, I resort to the following for pytest in github workflows:
```
def func(alive_bar_on=True):
   ...
   if alive_bar_on:
       with alive_bar(...) as pbar: ...
   else:
       # no alive_bar branch
```

```
def test_func():
    ...
    func(alive_bar_on=False)
    ...
```

**Comment by rsalmei** [comment]
Humm, that's a shame... 😕 
I use the low level implementation, which Is almost 7x faster than the higher level one:
<img width="615" alt="image" src="https://user-images.githubusercontent.com/6652853/151691432-81bb1be0-5573-4d32-8282-8469943be8b6.png">

The higher level protects against cases like this, returning a default 80 cols value.
OK, thanks. I'll consider using it, or fix it some other way.

**Comment by TheTechRobo** [comment]
You could wrap the `shutil.get_terminal_size` call into a `try` block, keeping the speed benefits....

**Comment by rsalmei** [comment]
You mean the `os` one, yes.
But the `shutil` one also tries to find cols via environment variables, maybe it does help in these exoteric scenarios...

Anyway, I'm releasing a new version today with this changed 👍
