### ISSUE TITLE
Use next with `alive_it' object

### ISSUE THREAD

**Issue by shadowrylander** [rsalmei/alive-progress#132]
Hello!

If a certain keyword is passed in, my module `bakery` returns an iterable (I think? Still confused with those) wrapped in your `alive_it` function; however, if I were to use `for` on it, such as `for item in bakery(alive = True)`, I get `TypeError: '__AliveBarIteratorAdapter' object is not an iterator`; this is the relevant code, translated from `hylang`:

```python
def  __iter__(self):
    self.n = 0
    self.output = self.getOutput() # returns `alive_it' wrapped object
    return self
def __next__(self):
    try:
        outputLen = len(self.output)
    except TypeError:
        return next(self.output)
    else:
        if self.n < outputLen:
            self.n += 1
            return self.output[self.n - 1]
        else:
            raise StopIteration
```

How would I go about fixing this?

Thank you kindly for the help!

**Comment by rsalmei** [comment]
Hello @shadowrylander 

Yeah, I think you are mixing Iterables and Iterators.
You can't get "the next item" from an Iterable, only from an Iterator.
Even from a simple `range` you can't get a "next" item, look:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/6652853/152181910-b8376caa-0ece-440e-bed5-fec82071789f.png">

It's the same thing with my AliveIt adapter:
<img width="742" alt="image" src="https://user-images.githubusercontent.com/6652853/152182022-4f4711d4-3353-46f8-8f46-68cff91765f0.png">

It's kinda tricky to implement both `__iter__` and `__next__`, and you probably don't need that!
Together they serve a different purpose, which is not this scope.
But you should implement this using only `__iter__`, and make it a generator, where you `yield` the elements you need.
You can even use `yield from alive_it()`, and let Python work for you.

**Comment by shadowrylander** [comment]
So would something like this in `__iter__` work?

```python
if isinstance(self.output, __AliveBarIteratorAdapter):
    yield from self.output
else:
    return self
```

**Comment by shadowrylander** [comment]
Ahp; wait; never mind. Just turn the whole damn thing into a generator using `yield from`. Thanks for this new fun concept to play with! 😹😹😹😹 And thank you kindly for all the help as well!

**Comment by rsalmei** [comment]
You're welcome 👍
