### ISSUE TITLE
Running demo tests on Windows is about four times(!) slower than on Linux

### ISSUE THREAD

**Issue by thorstenkampe** [rsalmei/alive-progress#133]
The title says it all. For instance, the "Definite/unknown modes" tests take between 12.5 seconds and 18.7 seconds on Windows while they take between 3.1 and 4.8 seconds on Linux. I'm worried that the "no runtime overhead at all" claim might not apply to Windows.

- Windows

```
=== Definite/unknown modes ===
Normal+total           |████████████████████████████████████████| 1000/1000 [100%] in 15.6s (64.06/s)
Underflow+total        |██████████████████████████▋⚠︎            | (!) 800/1200 [67%] in 12.5s (64.05/s)
Overflow+total         |████████████████████████████████████████✗︎ (!) 1200/800 [150%] in 18.7s (64.20/s)
Unknown                |████████████████████████████████████████| 1000 in 15.6s (64.10/s)

=== Manual modes ===
Normal+total+manual    |████████████████████████████████████████| 1000/1000 [100%] in 15.6s (64.12/s)
Underflow+total+manual |██████████████████████████▋⚠︎            | (!) 800/1200 [67%] in 12.5s (64.00/s)
Overflow+total+manual  |████████████████████████████████████████✗︎ (!) 1200/800 [150%] in 18.7s (64.12/s)
Unknown+manual         |████████████████████████████████████████| 100% in 15.6s (6.40%/s)

=== Print and Logging hooks ===
on 400: nice hassle-free print hook!
on 800: INFO:__main__:and even logging hook!!!
Simultaneous           |████████████████████████████████████████| 1000/1000 [100%] in 15.5s (64.34/s)

=== Display features ===
Styles                 |🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃| 1000/1000 [100%] in 15.6s (64.07/s)
Default                [========================================] 1000/1000 [100%] in 15.6s (64.08/s)
Receipt                [########################################] 1000/1000 [100%] in 15.6s (64.05/s) Ok, done!
No spinner             |>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>| 1000/1000 [100%] in 15.6s (64.19/s) Ok, done!
No monitor             |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| in 15.6s (64.22/s) Ok, done!
No stats               <●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●> 1000/1000 [100%] in 15.6s Ok, done!
No monitor/stats       <■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■> in 15.6s Ok, done!
Only bar               |✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓| Ok, done!
No bar                 1000/1000 [100%] in 15.6s (64.09/s) Ok, done!
No bar/spinner         1000/1000 [100%] in 15.6s (64.06/s) Ok, done!
Only spinner           Ok, done!
```

 - Linux
```
=== Definite/unknown modes ===
Normal+total           |████████████████████████████████████████| 1000/1000 [100%] in 3.8s (264.38/s)
Underflow+total        |██████████████████████████▋⚠︎            | (!) 800/1200 [67%] in 3.1s (258.43/s)
Overflow+total         |████████████████████████████████████████✗︎ (!) 1200/800 [150%] in 4.6s (259.55/s)
Unknown                |████████████████████████████████████████| 1000 in 3.8s (260.87/s)

=== Manual modes ===
Normal+total+manual    |████████████████████████████████████████| 1000/1000 [100%] in 3.8s (260.28/s)
Underflow+total+manual |██████████████████████████▋⚠︎            | (!) 800/1200 [67%] in 3.1s (261.20/s)
Overflow+total+manual  |████████████████████████████████████████✗︎ (!) 1200/800 [150%] in 4.6s (260.97/s)
Unknown+manual         |████████████████████████████████████████| 100% in 3.8s (26.22%/s)

=== Print and Logging hooks ===
on 400: nice hassle-free print hook!
on 800: INFO:__main__:and even logging hook!!!
Simultaneous           |████████████████████████████████████████| 1000/1000 [100%] in 3.8s (260.61/s)

=== Display features ===
Styles                 |🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃🎃| 1000/1000 [100%] in 3.8s (260.84/s)
Default                [========================================] 1000/1000 [100%] in 3.8s (262.19/s)
Receipt                [########################################] 1000/1000 [100%] in 3.8s (261.44/s) Ok, done!
No spinner             |>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>| 1000/1000 [100%] in 3.8s (261.91/s) Ok, done!
No monitor             |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| in 3.8s (261.34/s) Ok, done!
No stats               <●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●> 1000/1000 [100%] in 3.8s Ok, done!
No monitor/stats       <■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■> in 3.8s Ok, done!
Only bar               |✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓| Ok, done!
No bar                 1000/1000 [100%] in 3.8s (262.49/s) Ok, done!
No bar/spinner         1000/1000 [100%] in 3.8s (261.57/s) Ok, done!
Only spinner           Ok, done!
```

**Comment by rsalmei** [comment]
Hello,

I've never run `alive-progress` in Windows myself, all I know is what users bring to me.
I use macOS, which is 99% compatible with Linux...

Anyway, that's curious! The code is _exactly_ the same. I don't test the platform _anywhere_ in the code, nor the two dependencies I use (one of them is also mine actually).

So, I can just conclude the terminal Windows emulates has some problems, including a bad overhead.
Especially for a framework like `alive-progress`, which really demands it, updating the screen 60 times per second (at most).

**Comment by thorstenkampe** [comment]
I've tested multiple terminals on Windows (ConEmu, MinTTY, Windows Terminal): the times for the demo are virtually the same.

A simple test shows similar results on Windows (5.5s) and on Linux (5.1s) 
```python
import time, alive_progress
for item in alive_progress.alive_it(range(50)):
    time.sleep(0.1)
```
Maybe this is a grapheme issue?

Anyway, a BIG warning in the documentation ("While alive_progress MAY work on Windows, it is not tested on Windows and I have no way to resolve issues on Windows because of a lack of a Windows testing enviroment" is in my opinion needed.

**Comment by rsalmei** [comment]
No, I don't think it is a grapheme issue. Internally *everything* is a grapheme cluster now. It's the new Cell Architecture since 2.0.
And the `grapheme` lib is used only at the start, to generate and split the clusters.

And also no, I don't think it warrants a warning saying that it "may work on windows", since, as you've seen, it DOES work, even if slower than expected.

Another point, this report of yours is the first I get about it being slower there, it is not relevant yet until other users do report the same.

If you can help to try to sort this out, please try to gather some more info, will you?
Try with `"alive-progress<2"`, then `"alive-progress~=2.0.0`, then `"alive-progress~=2.1.0`, then `"alive-progress~=2.2.0`.
Is the slowdown introduced with any specific version?

Also please create a new virtualenv and try it again installing _only_ `alive-progress`.
You may have something like `colorama`, that is being automatically called somehow.

Thanks!

PS.: `alive_it` and `demo` were introduced in 2.0, so it would be better to test with plain `alive_bar`.

**Comment by rsalmei** [comment]
Closing this one, waiting for more info for three months now.
Please get back in here if you want.
