### ISSUE TITLE
Simple line progress bar

### ISSUE THREAD

**Issue by shadowrylander** [rsalmei/alive-progress#134]
Hello!

Is it possible to have a simple line progress bar, similar to the [rich progress bar](https://github.com/Textualize/rich#rich-library)? I feel your package here is more fluid, but a little too much for me.

Thank you kindly for the help, and thanks for the package! 😸

**Comment by rsalmei** [comment]
Hello!

It isn't at this moment, I only support disabling segments at the moment, like the monitor and stats and elapsed time...
But it is a long-standing request, I can surely implement that!

I'm doing it actually, to allow us to customize any of those segments as you wish!
Stay tuned... Very soon! 😉

**Comment by shadowrylander** [comment]
Eee! Thank you! 😹 Although, to clarify, I think I wanted a thin progression line, actually! 😅 The stats are quite handy!

**Comment by rsalmei** [comment]
Ok, what did you mean by "thin" then?
My `alive-progress` shows lines by default like this:
```
|████████████████                        | ▅▃▁ 44/110 [40%] in 5s (9.4/s, eta: 7s)
```

The one you've mentioned seems to only show `40%` (without `44/110`), and only elapsed time, without any stats.
So, I thought you've wanted to change the _monitor_ to only a percent, and disable stats, this is already possible. So I was just missing the custom monitor, to use `{percent:.0%}` instead of my default `'{count}/{total} [{percent:.0%}]'`.
What didn't I understand?

**Comment by shadowrylander** [comment]
Sorry about that; these example from `rich` are what I meant:
https://raw.githubusercontent.com/Textualize/rich/master/imgs/progress.gif
https://raw.githubusercontent.com/Textualize/rich/master/imgs/downloader.gif

Literally thin progress "lines", instead of the thicker progress "bars".

**Comment by rsalmei** [comment]
Ohhhh I see... 😂 
I've understood "thin" as leaner, simpler info, so I thought you've wanted to slim down some of the rich info panel I have!
Not as an actually narrower progress bar! 😂 

But in that case, you can simply create a custom bar, which is super easy!
![Untitled](https://user-images.githubusercontent.com/6652853/152714373-dceb8332-2812-4a68-b05a-c3c5101d185a.gif)

There's also the awesome `check` tool, where you get to see your creation!
<img width="622" alt="image" src="https://user-images.githubusercontent.com/6652853/152714448-3d96deed-977b-4ede-9081-1a4331dfac7f.png">

Pass a number to choose a variety of options, including animations!
![Untitled](https://user-images.githubusercontent.com/6652853/152715234-18f6e53a-e8b5-4785-8aea-f9b6055dbe59.gif)

Does that work for you? 😄

**Comment by rsalmei** [comment]
Oh, forgot to say, with you want to remove even the borders, you can pass `borders='  '` (two spaces).
The `bar_factory` supports a plethora of options, get creative!!
```
    Args:
        chars (Optional[str]): the sequence of increasing glyphs to fill the bar
            can be None for a transparent fill, unless tip is also None.
        tip (Optional[str): the tip in front of the bar
            can be None, unless chars is also None.
        background (Optional[str]): the pattern to be used underneath the bar
        borders (Optional[Union[str, Tuple[str, str]]): the pattern or patterns to be used
            before and after the bar
        errors (Optional[Union[str, Tuple[str, str]]): the pattern or patterns to be used
            when an underflow or overflow occurs
```

**Comment by shadowrylander** [comment]
Hah! That's what I was looking for! Thanks! 😻😹 Er, any way to color them...? 😅

**Comment by TheTechRobo** [comment]
you might yuse ansui escape codes

**Comment by rsalmei** [comment]
You're welcome! 👍 
No, not at the moment. Since I do herculean work to try to fit animations within a terminal line, even when the user resizes the terminal or in the presence of grapheme clusters (emoji), any color codes would wreck the length assumptions (they are invisible chars).
But someday I might support it, who knows 🙂

**Comment by rsalmei** [comment]
Read my comments here: https://github.com/rsalmei/alive-progress/issues/49

**Comment by shadowrylander** [comment]
@rsalmei Got it! Thanks for all the help!
@TheTechRobo Issue 49 is the key! ... Or the lock! 😹
