### ISSUE TITLE
Show local file upload progress

### ISSUE THREAD

**Issue by 411A** [rsalmei/alive-progress#138]
Hi, I just found `alive-progress` and read about its great features, but I don't know how to implement a local file upload progress using it; if there was a simple example for newbies on the `readme` page, that would be so helpful.

And I had a question, is there any way to show how many tiles remained to be complete visually? like this:
```
████▓▓▓▓▓▓
▪▪▪▪▫▫▫▫▫▫
```
thanks.

**Comment by rsalmei** [comment]
Hello @411A,

Thanks.
I'm not sure what you've asked... `alive-progress` renders a visual feedback of any processing of yours. So, if you have a local file upload system, you can easily include a `with alive_bar() as bar:` wrapping it, and you'll have a visual progress bar, position, elapsed time, throughput, and ETA for free! It should just work.

Regarding the bar styles, you sure can! Try to call `showtime()` in a python terminal, as explained in the readme, and you'll surely find some as you wanted. Also, you can create your own!

I'll close this one, but feel free to continue replying if you need it 👍
