### ISSUE TITLE
directly viz percentage to bar 

### ISSUE THREAD

**Issue by siddht4** [rsalmei/alive-progress#14]
I liked your viz project for progress bar.  But I am confused as your examples show int iteration to progress bar using a dummy data. 

I would like to know that how i can directly provide percentage to progress bar as it generates the bar for me. 

example

` a='0%'

# percentage 0 to 100 %
a= '100%'
`
now how `a`  should be passed to `alive_bar `

**Comment by rsalmei** [comment]
Hello @siddht4!

I'm not sure I got your doubt, but I assume you meant manual mode. That is the mode you can control the bar whatever you want.

To use it, just do:

```python
from alive_progress import alive_bar
import time

with alive_bar(1000, manual=1) as bar: 
    for i in range(1000): 
        time.sleep(.01) # process 
        bar((i+1)/1000.) 
```

Note the `bar` call. This is the place you send your percentage. The format is a float number between 0 and 1. For exemplo to send 15%, you would send `0.15` or `15/100.` as I did in the example code.

Was that your doubt?

**Comment by siddht4** [comment]
@rsalmei       Thank you for  mentioning the above.      

Can you add this to your readme/usage guide.  (its partially explained,so can you also elaborate in your readme for the usage of manual mode there. 


> Was that your doubt?

I am obtaining the percentage through an api so I wanted to use that directly .  

Looks like there is no direct usage . Can you add this mode i.e to directly provide percentage to `bar` 

example : As how now i understand

`bar(perc_str)

where  perc_str is  percentage in string format  like  80.01% 
`

**Comment by rogerio-geru** [comment]
No problem @siddht4 

But there is support for direct usage, you are not forced to calculate it yourself.
You just need to call `bar(0.15)` for example.

If that number comes from an API, it would be something like:
```python
with alive_bar(total) as bar:
    perc = requests.get('/api/completion')
    bar(float(perc))
```

**Comment by rsalmei** [comment]
Hey @siddht4,

I've updated the documentation about the float argument, hope it is clearer now.
