### ISSUE TITLE
Problems with pyinstaller

### ISSUE THREAD

**Issue by m1ch4elx** [rsalmei/alive-progress#143]
Previously I was getting error like #123  did. I downgraded to version 1.6.2 like he said but now I'm getting error like this:
```
File "C:\Users\Micha\AppData\Local\Programs\Python\Python310\Scripts\tkt.py", line 15, in <module>
    from alive_progress.styles import showtime, Show
ImportError: cannot import name 'showtime' from 'alive_progress.styles' (C:\Users\Micha\AppData\Local\Programs\Python\Python310\lib\site-packages\alive_progress\styles\__init__.py)
```

**Comment by Shivam-Shrivastav** [comment]
Please visit:
```
(C:\Users\Micha\AppData\Local\Programs\Python\Python310\lib\site-packages\alive_progress\styles\__init__.py)
```
and check if there is an element name 'showtime' in tuple or not
if not present then, let it be as:
```

__all__ = (
    'BARS', 'SPINNERS', 'THEMES', 'Show', 'showtime', 'show_spinners', 'show_bars', 'show_themes',
)
```

**Comment by m1ch4elx** [comment]
> Please visit:
> 
> ```
> (C:\Users\Micha\AppData\Local\Programs\Python\Python310\lib\site-packages\alive_progress\styles\__init__.py)
> ```
> 
> and check if there is an element name 'showtime' in tuple or not if not present then, let it be as:
> 
> ```
> 
> __all__ = (
>     'BARS', 'SPINNERS', 'THEMES', 'Show', 'showtime', 'show_spinners', 'show_bars', 'show_themes',
> )
> ```

I realised that I don't need showtime and Show at all but I need to have function to hide receipt, it comes with version 2.2.0 but when I install it I again get error like mentioned at #123

**Comment by m1ch4elx** [comment]
> 

And yes, it is in __init__.py
![image](https://user-images.githubusercontent.com/50585156/156788582-8f0cce0d-3a72-4cdf-aba7-efd3a261c580.png)

**Comment by rsalmei** [comment]
That's weird, I don't know yet what that could be.
But to hide the receipt you do not need to import anything, just send to `alive_bar` the param `receipt=False`.

**Comment by m1ch4elx** [comment]
> 

It does come with version 2.2.0 and besides that I need customizable monitor, elapsed, and stats core widgets which comes with version 2.3.0. Something wrong with grapheme

**Comment by Mettwasser** [comment]
I have the EXACT same problem. I don't know what to do..

**Comment by rsalmei** [comment]
But what problem??
Show me the command you used, and the outcome.
The only exception in this thread is one trying to import `showtime`.

**Comment by Mettwasser** [comment]
Oh I just realised this was issue #123 I had.. I have the problem mentioned in issue #123. I'm sorry. I got 1:1 the same error as pranjay there.

**Comment by rsalmei** [comment]
I see, no problem!
I'm going to close this one and reopen that one then.
