### ISSUE TITLE
output problem in jupyterLab

### ISSUE THREAD

**Issue by hamzabha** [rsalmei/alive-progress#145]
Hey! First I wanted to say that the project is really cool! 

I'm working on a code in jupyter lab and wanted to integrate alive-progress in a preprocessing step and for this for loop:

```
    print("Extracting information from the files...")
    with alive_bar(len(response_files), force_tty=True) as bar:
        for file in response_files:
            exp_id = file[16:20]
            lmu_id = file[21:26]
            temp = pd.read_csv(file)
            exp_lmus.append([exp_id, lmu_id, temp["ue_id"].values[0], temp["pps_counter"].values[0]])
            bar() 
    print("-----Information retrieved-----")

```
and somehow while the bar progresses it keeps on printing the text over and over again... Can you help me fix that?
Thanks a lot!

![image](https://user-images.githubusercontent.com/49587490/159123170-9fcbe1fe-440c-4438-aacd-95dae9bc4207.png)

**Comment by rsalmei** [comment]
Hey @hamzabha, thanks!

I've never used this jupyter lab, I'm gonna take a look to see what it does differently.

**Comment by rsalmei** [comment]
Hey @hamzabha, I did find a bug that I've missed previously.
It seems to work now, both in jupyter notebook and in jupyter-lab.
It is awesome, it looks just like in a terminal, very smooth and fluid!

https://user-images.githubusercontent.com/6652853/159354221-7fe4dceb-8ba6-4e4e-9f17-642dfa3a74d7.mov

**Comment by rsalmei** [comment]
It's published!! 2.4.0
Could you please test it again?

**Comment by hamzabha** [comment]
Hey @rsalmei Thanks for the replies! I upgraded to 2.4.0 but sadly the output problem still persists...

**Comment by rsalmei** [comment]
Ohh, that's unfortunate 😕
It does work beautifully here.
Please create a new venv, install only `alive-progress` and `jupyterlab`, and test with a simple example:
```python
from alive_progress import alive_bar
import time

with alive_bar(1000, monitor=0, force_tty=1) as bar:
    for i in range(1000):
        time.sleep(.005)
        if i and i % 300 == 0:
            print('cool!')
        bar()
```

**Comment by rsalmei** [comment]
Hey, any news here?
I'm going to close this one, please reply if anything new arises.

**Comment by matnguyen** [comment]
@rsalmei I'm on 2.4.1 and I have this problem on both Jupyter Notebook and Jupyter Lab
