### ISSUE TITLE
How to use this with scrapy?

### ISSUE THREAD

**Issue by softmarshmallow** [rsalmei/alive-progress#146]
I cannot find a proper way to use this in a event listening pattern.

```py
    bar = None
    def __init__(self):
      super()
      with alive_bar(self.total_c, ctrl_c=False, title=f'crawling') as bar:
        self.bar = bar


    def item_scraped(self, item):
      self.bar()
```

how do i assign bar on to a variable witout destroying it?
how do i use the api without `with ... as bar: `?

**Comment by rsalmei** [comment]
Hey @softmarshmallow, it's not hard to use it without a context manager.
See examples here: #44, #3, #103, and #116.

**Comment by softmarshmallow** [comment]
Thanks for such a quick answer!
