### ISSUE TITLE
What font do you use in the gif demonstrations?

### ISSUE THREAD

**Issue by Tosh0kan** [rsalmei/alive-progress#147]
I'm asking because I'm using Fira Code, and I'm lacking some of the symbols used in the animations.

**Comment by rsalmei** [comment]
Hey @Tosh0kan,

Personally, I love [Victor Mono](https://rubjo.github.io/victor-mono/), this is the one I use in both my coding editors and my terminal.

For the symbols, you should get a [Nerd Font](https://www.nerdfonts.com/).
They have already patched fonts with tons of symbols, highly recommended!
(there's `VictorMono Nerd Font` of course)
<img width="522" alt="image" src="https://user-images.githubusercontent.com/6652853/159411005-8cdd245e-6f6e-46c8-bc83-5a2fa1d35d7e.png">

**Comment by Tosh0kan** [comment]
I got fonts from the site you linked, both FiraCode Nerd and VictorMono Nerd, and I still have missing characters. This gif(https://i.imgur.com/pUIQH5E.gif) was with me using VictorMono Nerd Font.

**Comment by rsalmei** [comment]
Ohh, you seem to be using Windows...
I don't know exactly what happens in there, but it is really different.

I've received some issues about this, please read #101, #97, #96, and #88 at least.
Also, which versions of `alive-progress` and Python are you using?

**Comment by Tosh0kan** [comment]
I saw the issues you linked and none of them really is relevant to my situation I think, apart from #88 for the workaround. I do have a a few more info to give.  On both the a prompt window and powershell, I have this problem. However, in my IDE, which uses powershell as its terminal, and in the new windows terminal, they work fine.

My `alive-progress` version is 2.4 and Python's is 3.9.10

**Comment by rsalmei** [comment]
Yeah, I really don't know what happens within Windows' terminals, you have much more information than me...

I don't know what are "prompt window", "powershell" or "new windows terminal" as you've told me, but it seems that are a lot of options.
If you'd want it to work in some more than others, you'd have to help me: what do I need to do to make it work? I know nothing about developing in Windows...

If you tried that workaround and it didn't work, I don't know what else to try.
I've heard `colorama` could be of some help, I'd like to hear if it does improve anything.

**Comment by Tosh0kan** [comment]
I dunno it either haha. I just know what they work on and what they don't. I guess it's just Windows' idiosyncrasies at it again. Thank you for your attention.

**Comment by rsalmei** [comment]
Sure, you're welcome.
