### ISSUE TITLE
Possible to pipe output to other stdout?

### ISSUE THREAD

**Issue by jhonatan-lopes** [rsalmei/alive-progress#150]
Hello,

I am working on a custom [Django management command](https://docs.djangoproject.com/en/3.2/howto/custom-management-commands/), which requires the console output to be written to the `BaseManagement` class `self.stdout` and `self.stderr`. The official note reads:

> When you are using management commands and wish to provide console output, you should write to self.stdout and self.stderr, instead of printing to stdout and stderr directly. By using these proxies, it becomes much easier to test your custom command.

This, of course, is not a requirement, but since Django does not allow to return values when calling the custom commands, the way to test some situations is by printing to `self.stdout` and checking if the captured output string meets the expectation.

This current command parses through a file and updates the database based on its rows. Since it can take a while, I would like to have a progress bar to show while it is running.

My question is if I can pipe all the output of `alive_bar` to this `self.stdout` instead of writing directly to _stdout_?

**Comment by rsalmei** [comment]
Hello Jhonatan!

If I understand correctly, this `self.stdout` is an instrumented one by django, which makes it possible to be captured and monitored, right?
In that case, it seems to me it would be even better to _not_ make `alive-progress` go through there, since there isn't any sense capturing it's output. It would be:

```
sys.stdout <-- alive-progress stdout <-- django stdout
      |                         |                 |
      ↳ actual terminal one     |                 ↳ instrumented by django, which captures actual command output
                                ↳ instrumented by alive-progress, which hits terminal several times per second
```

What do you think? `Alive-progress`' output goes directly to system's stdout, while also listening to any output going through it. Django's stdout, if it happens to get `sys.stdout` **after** the `alive-progress` context manager is entered, everything should work I suppose.

**Comment by jhonatan-lopes** [comment]
Hi Rogério, thanks for replying!

Yes, the `self.stdout` is instrumented by Django to be able to capture and monitor console output.

I think I get you point, the diagram is quite helpful. You are absolutely right, it doesn´t make sense to pipe `alive-progress` through this other `self.stdout`. There are no compatibility issues with Django's custom command and alive-progress when used together. It is possible to print inside the command using `bar.text` as well as using Django's `self.stdout.write` after `alive-progress` context manager is finished.

My thought now to make it easier to test this (the point of the question) is to wrap the insides of the Django command in a function that includes all of the `alive-progress` functionality and then call this function inside the Django command's `handle` method (main calling point).
