### ISSUE TITLE
Alive_bar crashes when using bar.text with disabled and dual_line options set to True

### ISSUE THREAD

**Issue by jhonatan-lopes** [rsalmei/alive-progress#151]
Hi rsalmei, check out this code:

```python
from alive_progress import alive_bar
import time

with alive_bar(1000, disable=True, dual_line=True) as bar:
    for i in range(1000):
        bar.text(f"Iteration no. {i}")
        time.sleep(.005)
        bar()
```
When I run it, I get this error:
```
Traceback (most recent call last):
  File "/home/jplopes/dev/Test-Houses/proto_alive.py", line 6, in <module>
    bar.text(f"Iteration no. {i}")
  File "/home/jplopes/dev/Test-Houses/.venv/lib/python3.10/site-packages/alive_progress/core/progress.py", line 141, in set_text
    run.text, run.suffix = ('\n', to_cells(str(text))), term.cursor_up_1.sequence
AttributeError: 'function' object has no attribute 'sequence'
```
which traces back to line 141 of `alive_progress/core/progress.py`:

```python
if text and config.dual_line:
    run.text, run.suffix = ('\n', to_cells(str(text))), term.cursor_up_1.sequence
```
only triggered when using `bar.text` with `dual_line=True` configuration.

**Comment by cpiment** [comment]
Hi jhonatan,

I stumbled with the same bug as you when using alive_bar inside a Jenkins pipeline. I developed the tool to be used in a terminal, but now we want to integrate it inside a Jenkins job. I used your fix to avoid the bar crashing at the beginning, but it now crashes while closing the alive_bar. 

This Jenkins is a Windows box. The error I get is this one:

```
Creating VMs Traceback (most recent call last):
  File ".\vm-deploy.py", line 135, in <module>
    break
  File "C:\Program Files\Python38\lib\contextlib.py", line 120, in __exit__
    next(self.gen)
  File "**\venv\lib\site-packages\alive_progress\core\progress.py", line 299, in __alive_bar
    alive_repr()
  File "**\venv\lib\site-packages\alive_progress\core\progress.py", line 135, in alive_repr
    run.last_len = print_cells(fragments, term.cols(), run.last_len, _term=term)
  File "**\venv\lib\site-packages\alive_progress\utils\cells.py", line 91, in print_cells
    _term.write(join_cells(fragment))
  File "C:\Program Files\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1-40: character maps to <undefined>
```

Is this because the terminal is VOID too?

**Comment by jhonatan-lopes** [comment]
Hi @cpiment, this is interesting. 

I simply introduced an empty string as the `term.cursor_up_1.sequence` for the `terminal.VOID` as you can see in the PR. It was kind of a simplistic patch, to be honest, as I don't fully know the side effects that this might introduce. This seems to work well with the context manager wrapper (when you run the minimal example above). Are you explicitly creating and closing the bar? Does the example above work for you after the patch?

Also, I'm on a Linux, so I'm afraid I'm not able to test the Windows implementation.

**Comment by rsalmei** [comment]
Hello @jhonatan-lopes!
Nice catch, this `term.sequence` field is new, I've introduced it exactly for the dual-line mode, and this detail has slipped me.
I'll release it now, thanks!

**Comment by jhonatan-lopes** [comment]
Hi @rsalmei, I'm glad I could help. Always happy to contribute.

Also check out @cpiment issue on Windows, though. I'm afraid that the fix missed that and I don't have access to a Windows environment to test it.

**Comment by rsalmei** [comment]
Yeah, regarding @cpiment, I'd ask you to open an issue for that.
I think it is not related to this at all.
