### ISSUE TITLE
alive_bar crashes on __exit__ when running inside a Jenkins job on Windows

### ISSUE THREAD

**Issue by cpiment** [rsalmei/alive-progress#153]
I'm running this powershell script inside a Jenkins job (Jenkins is running in Windows)

```powershell
cd F:\CPLTEST
& 'C:\Program Files\Python38\python.exe' -m virtualenv venv
& .\venv\Scripts\activate.ps1
& pip install alive-progress==2.4.1
& python -u .\alive_progress_test.py
```

The content of `alive_progress_test.py` is:

```python
from alive_progress import alive_bar
import time

with alive_bar(1000, disable=None, dual_line=True) as bar:
	for i in range(1000):
		bar.text(f"Iteration no. {i}")
		time.sleep(.005)
		bar()
```

As expected, since there is no terminal, the progress bar is not printed. I assume that the terminal is set to `terminal.VOID` because I also had the 2.4.0 bug found by @jhonatan-lopes in #151. But when the for loop ends, I get this error in the Output Console of the Jenkins Job:

```
Traceback (most recent call last):
  File ".\alive_progress_test.py", line 8, in <module>
    bar()
  File "C:\Program Files\Python38\lib\contextlib.py", line 120, in __exit__
    next(self.gen)
  File "F:\CPLTEST\venv\lib\site-packages\alive_progress\core\progress.py", line 299, in __alive_bar
    alive_repr()
  File "F:\CPLTEST\venv\lib\site-packages\alive_progress\core\progress.py", line 135, in alive_repr
    run.last_len = print_cells(fragments, term.cols(), run.last_len, _term=term)
  File "F:\CPLTEST\venv\lib\site-packages\alive_progress\utils\cells.py", line 91, in print_cells
    _term.write(join_cells(fragment))
  File "C:\Program Files\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1-40: character maps to <undefined>
```

As a workaround, I have modified the code so if it finds that it is running inside a Jenkins job, it sets the `disable` parameter of the `alive_bar` to `True`. That way the loop ends without crashing and the rest of the code is executed. I.e, with this alive_bar, the script doesn't crash:

```python
with alive_bar(1000, disable=True, dual_line=True) as bar:
```

I have not been able to reproduce the issue outside Jenkins.

Thanks for your great module!

**Comment by jhonatan-lopes** [comment]
Hi @cpiment, I got an old Windows 10 laptop here and was able to run the code without issues, both with `disable=None` and `disable=True`. I suspect that this is a Jenkins issue.

Note, however, that `disable=None` does not disable the bar as opposed to what you were expecting. Running on Windows 10, the bar still shows when `disable=None`. This can be confirmed from `core.progress` (lines 203 -> 208), where it can be seen that the terminal is set to `terminal.VOID` only if `config.disable` is `True` (None is not a True value):

```python
    if config.disable:
        term, hook_manager = terminal.VOID, passthrough_hook_manager()
    else:
        term = config.force_tty
        hook_manager = buffered_hook_manager(
            header if config.enrich_print else '', current, cond_refresh, term)
```
I'm afraid I'm not very familiar with Jenkins, so I cannot comment any further.

Furthermore, I am not a maintainer of this repo, so it would be better to hear an official comment from @rsalmei.

**Comment by cpiment** [comment]
Hi @jhonatan-lopes, thanks for your review.

I wrongly understood reading the documentation that the default value of `disable` option was `None`, and that, with that value, `alive_bar` was able to detect the type of terminal and act accordingly (i.e. suppressing the output when there is no terminal). 

Reading the docs in more detail, I see that the default value is `False`, so I will try to modify my test case and run it from Jenkins again to see if the behaviour is still the same.

Anyway, what I'm trying to test is that with the default value of `disable` option, `alive_bar` sets the terminal to `terminal.VOID` (I know this because I got the same bug as you using version 2.4.0), thus it detects that it is not running inside a 'normal' terminal and suppresses the output automatically, which is expected, but it does not fully work because it crashes at the end of the loop.

On the other hand, if I force `disable` to `True`, the output is suppressed AND the program does not crash at the end of the loop.

So it seems that something works differently when `disable` is set to `True` and when the module detects automatically that there is no terminal, but I think the behaviour should be the same in this case.

Thanks!

**Comment by jhonatan-lopes** [comment]
Hum, I see what you mean now, it makes sense. I don't know enough about the auto detection features to comment on that.

Regarding tests with the terminal, what I usually do on my end is to pass a `disable_progress_bar` kwarg to my functions that have progress bars with a default of `False`, i.e. the bars are shown if you do not specify this specific option. Now, on my tests I set `disable_progress_bar=True` and pass that on to `alive_bar`:
```python
def my_long_function(x, disable_progress_bar=False):
    with alive_bar(total, disable=disable_progress_bar) as bar:
       # do something
       bar()
```

This way, you manually force it to disable printing when running tests. It is a bit verbose having to pass the argument around all the time, but it does the job.

**Comment by rsalmei** [comment]
Hello @cpiment, and thanks @jhonatan-lopes!

@cpiment, you are mixing up `disable` with `force_tty`. The latter is the tri-state one, which defaults to `None` and auto-detects the terminal type.
The `disable` option is only to completely stop `alive-progress` from functioning, and yet leave its context manager set.

So, as you both had already figured out, your code was _not_ disabling the bar at all. And since you've used `dual_line`, there's an ANSI Escape Code sent to the terminal to send the cursor back up one line. I think **that** is what your Windows terminal didn't like...
You could try `colorama` for that. It converts these codes into Windows calls.

**Comment by rsalmei** [comment]
Well, closing this one, since it seems resolved, and there's no response in one month.

Please, do not confuse `force_tty` with `disable`.

`force_tty` is the tri-state one, defaults to None, which means "not set, thus auto-detect the tty type".
- True makes it always use the FULL terminal
- False makes it always use the VOID terminal

`disable` is a much more recent option. It's only purpose is to completely disable the `alive-progress`, and yet leave it in the code. It is used when you want to conditionally use or not the progress bar, hence it obviously defaults to `False`.
