### ISSUE TITLE
Iteration output during progress loop

### ISSUE THREAD

**Issue by GuardianMajor** [rsalmei/alive-progress#154]
Is there any way to get these `on 0:` (incremented for each item in the total) to stop printing out?

I have read the documentation hoping there was a switch that would do that, but nothing seems to work.

Am I missing something?

**Comment by rsalmei** [comment]
Yes, there is. It is documented in https://github.com/rsalmei/alive-progress#configurations
Look for `enrich_print`.

**Comment by GuardianMajor** [comment]
@rsalmei You might want to update your anchors as that link doesn't go where you think it does. But yes, I did see enrich_print but setting that to `false` removes everything including the bar and the receipt, it seems all or nothing which is bad design, no? Maybe take a second more with this than to just close it?

**Comment by rsalmei** [comment]
Are you kidding @GuardianMajor?
Yes, it does go to where I think it should: the Configurations, where this option is declared:
<img width="786" alt="image" src="https://user-images.githubusercontent.com/6652853/162626341-7bb981fd-75a6-4c20-b8c8-bb35e7573dab.png">

And NO, it DOES NOT remove everything, what are you talking about?
![Untitled](https://user-images.githubusercontent.com/6652853/162626541-307f8928-3b7b-48e7-922e-763f976a288b.gif)

Maybe you should try to ACTUALLY READ the documentation, which took me HUNDREDS of hours and I've made FOR FREE, and do not waste my time anymore.

**Comment by rsalmei** [comment]
> it actually works the way you think

I get **angry** with this kind of bullshit! I've MADE THIS PROJECT FROM SCRATCH, ALONE!
I don't "think" it works some way or another, I KNOW all the innards of it, and what each and every option do!
I smell troll, and won't reply anymore if you do not apologize and state your business.

**Comment by GuardianMajor** [comment]
You should be more professional and clearly a serious developer would be more open to listening to the user base then trying to act all high and mighty. Cleary not worth using this as the developer is a hostile unprofessional child.

**Comment by GuardianMajor** [comment]
By the way, this is where it goes, I was just telling you so you can make sure, not to throw a tantrum.

![image](https://user-images.githubusercontent.com/5274181/162799694-3d1e6a72-54f6-4006-8025-2f874cbb389f.png)

**Comment by GuardianMajor** [comment]
Also, maybe not test everything in Jupyter and make sure it runs in real environment Python as well. Good luck to you, as I don't think it is worth more time to try and support you.

**Comment by TheTechRobo** [comment]
Not sure what broken browser you're using where the anchor doesn't work. Works fine for me, as does enrich_print in a **vanilla Python REPL**:

![image](https://user-images.githubusercontent.com/52163910/162842283-3c7222fc-2918-4332-a4a4-251d40d62fe1.png)

(Also rsalmei doesn't use Jupyter, but ipython.)

**Comment by TheTechRobo** [comment]
Also, while most companies would be glad to support your every step, rsalmei is very busy IRL with a job, as are most people. Good day.

**Comment by rsalmei** [comment]
> and support you.

Really? When did you "support" me? Did you make a donation I'm not aware of? Of course not.

You are clearly a troll, unprofessional and childish, who are not capable of using even a browser, let alone using an advanced framework like `alive-progress` or apologizing when wrong. Please go bother someone else.
