### ISSUE TITLE
Crash when reusing logging Handlers with unhashable type: 'types.SimpleNamespace'

### ISSUE THREAD

**Issue by aviadfiant** [rsalmei/alive-progress#155]
Hello,
First of all thank you for all the effort you've put in to this project so far.

I am running into an issue I can't seem to resolve and would love it if you could give your opinion.

I am trying to use both alive-progress and sshtunnel together.
All I've done is create the sshtunnel definition before the alive example code as below, and I am getting the error from the headline :\
```
from alive_progress import alive_bar
import time
from sshtunnel import SSHTunnelForwarder

ssh_tun = SSHTunnelForwarder(
    "0.0.0.0",
    ssh_username="mooo",
    remote_bind_address=('127.0.0.1', 8080)
)

for x in 1000, 1500, 700, 0:
    with alive_bar(x) as bar:
        for i in range(1000):
            time.sleep(.005)
            bar()
```

Thoughts?
Thank you in advance for any reply.

**Comment by TheTechRobo** [comment]
Is this related to #107?

**Comment by rsalmei** [comment]
Hello @aviadfiant, thank you, man!

Well, it does seem similar to that one @TheTechRobo has reminded us of, but it is different.
This SSHTunnelForwarder uses `logging` internally, but in a kinda unusual way: it **reuses handlers**...

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/6652853/163533821-5f28c999-58ef-4f10-9afb-142e1a2a01ac.png">

Note the highlighted ids, they are the addresses of some object, all pointing to the same Handler `107c648c8`.
So, when `alive-progress` processes them, it tries to instrument again a ready handler, so it breaks like in a nested use case.

I'll support this case in a new version 👍

**Comment by aviadfiant** [comment]
Thank you for so much. Let me know if I can help with testing :)

**Comment by Zhaopudark** [comment]
Same with me. Conflict with `logging` when I set individual loggers. `unhashable type: 'types.SimpleNamespace`

**Comment by rsalmei** [comment]
Are you also reusing handlers?

**Comment by Zhaopudark** [comment]
@rsalmei  Yes. Here are my simplified codes:
```python3
import time
import os
import logging
import logging.handlers
import tempfile

from alive_progress import alive_bar

with tempfile.TemporaryDirectory() as temp_dir:
    logging.basicConfig()
    logger = logging.getLogger("main_logger")
    logger.setLevel(logging.DEBUG)
    file_handler = logging.handlers.RotatingFileHandler(os.path.normpath(f"{temp_dir}//temp_log.log"),maxBytes=1*1024*1024, backupCount=3)
    file_handler.setLevel(logging.DEBUG)
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s',datefmt="%Y/%m/%d %I:%M:%S")
    logger.addHandler(file_handler)
    with alive_bar(100) as bar:
        for item in range(100):
            logger.info("Bug info")
            bar()
            time.sleep(1)
```
with the bug `AttributeError: 'types.SimpleNamespace' object has no attribute 'seek'`

**Comment by rsalmei** [comment]
Hey @emanuelen5, thanks for the detailed report!!

Yes, it is the exact same problem, it is a code that reuses a **handler**...
Notice both your loggers reuse the handler named `console`, defined above:
```json
        'a': {'level': 'DEBUG', 'handlers': ['console']}
        'b': {'level': 'DEBUG', 'handlers': ['console']}
```

I need to somehow detect I've already instrumented it, so I do not try it again.
I was going to fix this together with another issue regarding seek support, which is way more difficult, but I'll try to look into this one separately. It seems way simpler.
As soon as I get some free time I'll take a look and fix this 👍

**Comment by rsalmei** [comment]
Hey @Zhaopudark, thanks man! Appreciate the words!

Yeah, loggers that use `seek` are not supported yet, the issue for that is #104 
It's on my list too.

**Comment by rsalmei** [comment]
Thanks for the example @emanuelen5, I'll use it to fix this!

**Comment by emanuelen5** [comment]
@rsalmei No problem. Thanks for the awesome work 😊

**Comment by rsalmei** [comment]
Thanks, man 👍

**Comment by rsalmei** [comment]
Hey, this is fixed!!
Should be available in the next release! 👍

**Comment by Crinibus** [comment]
Hi, is there an update to when the next release is with the fix?
I experience a similar issue.

Have a great day :)

**Comment by rsalmei** [comment]
Hi folks!

I'd just like to let you know I'm committing it at this exact moment!
Should be released soon!! 👍 

Thanks, @Crinibus, you have a great week!! 👋
