### ISSUE TITLE
Using alive_bar along with input()?

### ISSUE THREAD

**Issue by sortedcord** [rsalmei/alive-progress#156]
I was wondering if there was a way to be able to take input from user while alive bar was still running? To be clear:

```py
with alive_bar() as bar:
    foo = input("Enter some text")
    bar()
```

Simply running this doesn't give any issues and if you enter something, it does take in the values and carry on with the rest of the code, but while entering the value, it is not displayed properly...

**Comment by rsalmei** [comment]
Hey, you should use the `pause` mechanism... Look in the docs 👍
