### ISSUE TITLE
How to align multiple bars, when whitespace is stripped from bar_title

### ISSUE THREAD

**Issue by BroodjeKroepoek** [rsalmei/alive-progress#158]
![Schermafbeelding 2022-04-27 134710](https://user-images.githubusercontent.com/85361152/165513329-99e5b455-87d4-49ae-973a-35fbf03a2524.png)

I've already tried string.rjust and string.ljust, but I think internally the whitespace is stripped from bar_title.
So my question is how do I align the bars?

I want something like this:
![image](https://user-images.githubusercontent.com/85361152/165513568-7bb8bf78-6377-4a13-9056-be2c5f744608.png)

**Comment by rsalmei** [comment]
Hello @BroodjeKroepoek,

It's easy, I've made an option called `title_length`, which makes all titles use that exact size, i.e. if less it gets spaces, if more it is truncated.

It is cited twice in the README, [here](https://github.com/rsalmei/alive-progress#displaying-messages):
<img width="871" alt="image" src="https://user-images.githubusercontent.com/6652853/165666539-f4da591e-af13-4680-be07-7a0797d4f3f2.png">

and [here](https://github.com/rsalmei/alive-progress#configurations):
<img width="641" alt="image" src="https://user-images.githubusercontent.com/6652853/165667372-592ef0d8-8074-42eb-a6bc-8c2505c11faa.png">
