### ISSUE TITLE
Alive Progress with jupyter notebooks

### ISSUE THREAD

**Issue by avlm** [rsalmei/alive-progress#16]
Is there a way to use alive-progress with jupyter notebooks?
I tried but it's printing in my command line instead of notebook, and the output is like this:

|████████▌                               | ▅▇▇ 214/1000 [21%] in 21s ...
|████████▌                               | ▆█▆ 215/1000 [22%] in 21s ...
|████████▋                               | ▇▇▅ 216/1000 [22%] in 21s ...

Update:
Python==2.7.15
Django==1.8.4

I'm using jupyter notebook with django-shell-plus to use django models

**Comment by rsalmei** [comment]
Hey @avlm, how are you?

Unfortunately there's no support for jupyter notebook.
It may have someday, but it is not in the short term plans.

**Comment by avlm** [comment]
Ok, @rsalmei.
Você é brasileiro? kkk
Me avisa se eu puder ajudar com isso, seria um prazer.

**Comment by rogerio-geru** [comment]
Opa, sou sim!
Como vc percebeu falando apenas em inglês?? :stuck_out_tongue_winking_eye:

**Comment by rsalmei** [comment]
Alô @avlm!

Então, sou brasileiro sim, mas como vc percebeu? hehehe

Enfim, adoraria alguma ajuda nisso, não faço ideia de como desenhar widgets (gráficos) num jupyter notebook. Já leu alguma coisa sobre?

**Comment by avlm** [comment]
opa! percebi pelo teu nome do github kkkk
eu consegui fazer usando uma lib chamada [tqdm](https://github.com/tqdm/tqdm), ela é bem simples também, vale a pena dar uma conferida.

O que poderia fazer era indicar ela no README caso a pessoa deseje usar num jupyter. Ou colocar ela como dependência do alive-progress e fazer uma verificacão do ambiente para caso seja um notebook fazer um "fallback" e usar o tqdm.
Só não sei se seria tão simples de fazer as customizacões que o alive-progress tem funcionarem no tqdm.

 qualquer coisa estamos aí. :D

**Comment by rsalmei** [comment]
Opa, eu conheço a tqdm, claro. É a mais antiga e conhecida de todas.
Mas este meu projeto **alive-progress** nasceu justamente porque eu não gosto dela, nem do uso básico nem do avançado. Não gosto da interface de customização e não tem features que eu precisava, como por exemplo _pause_ para voltar ao ipython e depois continuar, ou um spinner animado super legal para eu ver que a conexão SSH não caiu, o que deu um _wow factor_ todo especial né...

Enfim, eu não acho legal recomendar porque não tem o mesmo nível de features, e jamais vou incluir como dependência aqui pelo mesmo motivo, não faria sentido ter spinners animados em terminal e não ter no jupyter, quero manter o mesmo nível de qualidade em qualquer plataforma que eu suportar.

Mas eu vou fazer melhor, eu vou **implementar o suporte**! Teremos sim barrinhas coloridas e spinners animados no jupyter notebook! Algum dia... 😅
Já comecei a estudar um pouco como isso é feito, descobri os projetos [ipywidgets](https://github.com/jupyter-widgets/ipywidgets) e [ipycanvas](https://github.com/martinRenou/ipycanvas) que parecem ser o que preciso, está na minha lista!

Só estou muito ocupado no momento fazendo a v2 com outras coisas legais também, como possibilidade de reset e reconfiguração da barra a qualquer momento... Isto vai possibilitar calcular o total com a barrinha já na tela, com animações dando feedback ao usuário de que esse cálculo está sendo feito, e depois enviar esse total à barrinha em curso, que se reconfigura e apresenta total, velocidade e tempo normalmente, tudo em tempo real! Vai ser bem legal 👍

**Comment by avlm** [comment]
Massa! Vou dar uma olhada no ipywidgets e no ipycanvas pra tentar dar uma força nisso aí. Valeu!

**Comment by rsalmei** [comment]
Eu que agradeço! 👍 
(vou manter o ticket aberto)

**Comment by TheTechRobo** [comment]
@thorstenkampe (I suggest using this open issue for discussion)

https://github.com/tqdm/tqdm/blob/master/tqdm/notebook.py is the relevant TQDM file, FWIW.

**Comment by rsalmei** [comment]
Nice @TheTechRobo, I'm also going to move my reply here.

> Maybe that could get Alive-Progress started?!

Yeah, I know it does @thorstenkampe, thanks.
It has an adapter, to convert their bar to a GUI environment, as a jupyter widget.
Well, the goal in tqdm is just to see a process, the goal here is to see it in style. Tqdm only updates the bar passively, when there's any change. Here I refresh the bar dynamically, from 4 up to 60 frames per second based on the processing speed, and I don't know if that would even be supported in notebooks...
So, It's not an easy task at all.

Anyway, I did a quick look at their code, and it does not even draw the actual bar, it uses an internal ready-to-use component of ipywidgets:

https://github.com/tqdm/tqdm/blob/master/tqdm/notebook.py#L47

So, perhaps it really wouldn't be so hard to support something like it, using that same approach.
It surely wouldn't support all the bells and whistles that alive-progress does have, but it would be ok as an MVP...
Thanks 👍.

**Comment by radugrosu** [comment]
Hi Rogério, just wanted to mention that bare-bones (text based, not widget based) notebook support would be really important. I understand your concern about style, but having something show up in the notebook would be still very desirable. Thanks

**Comment by rsalmei** [comment]
Hey, version `2.1` is released!!
This should be fixed, please report back if anything new arises.

**Comment by samwelborn** [comment]
Hello! Looks like a great program. I am using JupyterLab, and this is my output from your code above:
![image](https://user-images.githubusercontent.com/55868530/143397640-1b4627ad-cc3a-498f-ae33-6bfee57367ae.png)

You can see my environment here:
[20211124requirements.txt](https://github.com/rsalmei/alive-progress/files/7600995/20211124requirements.txt)

**Comment by rsalmei** [comment]
Hey @samwelborn, I'm not familiar with this JupyterLab, I've never used it.
I just tested it on Jupyter Notebook.
Do you know if it have any major architectural differences?
By the look of your output, it seems `\r` is being ignored, which is critical...

**Comment by TheTechRobo** [comment]
@rsalmei JupyterLab is a web based UI for Jupyter Notebook.

That's the extent off my knowledge.

**Comment by samwelborn** [comment]
[Jupyter Lab is an enhanced version of Jupyter Notebook](https://stackoverflow.com/questions/50982686/what-is-the-difference-between-jupyter-notebook-and-jupyterlab). 

I just tried to do this on a fresh environment without jupyterlab: [alive-progress-testing.txt](https://github.com/rsalmei/alive-progress/files/7610424/alive-progress-testing.txt)

For whatever reason (old version of conda in my base env, maybe), doing "conda install -c anaconda notebook" gave me notebook version 6.1.4. This produced the same result (in notebook):
![image](https://user-images.githubusercontent.com/55868530/143623059-38db0eb7-6240-49e5-b2e0-7f0c822155c5.png)

I also tried this in notebook (v6.4.6), and it produced the same result.

What version of notebook did you test this out on @rsalmei? Would love to use your progress bars in my interactive notebook!

**Comment by rsalmei** [comment]
Humm I see, I can try to download it and test that sometime.

Anyway, that's very odd @samwelborn, mine is not that recent also...
I've been lazy and haven't updated my python env in a long time, this is what I'm running now (using dark reader):
<img width="596" alt="image" src="https://user-images.githubusercontent.com/6652853/143656225-40b7e408-1850-4f3b-a7af-c9daa5b0e8f8.png">

So you see, 6.1.1 in a python 3.8.2...
And it works flawlessly for the most part:
![asd](https://user-images.githubusercontent.com/6652853/143656369-eb6eb344-03b3-4b87-afc0-ada8b8fa5900.gif)

Well, and I don't think they would drop this support somehow in newer Jupyters, but I can update everything here if you feel that could be relevant...

Thanks! I also would love that *you* have used my `alive-progress` bar! 😃

**Comment by samwelborn** [comment]
:)

I tried to install your environment:
![image](https://user-images.githubusercontent.com/55868530/143666188-e6961eac-9283-4b53-96c7-af034a93be66.png)

and it's still doing the same:
![image](https://user-images.githubusercontent.com/55868530/143666193-181a2279-c569-430e-903a-512ae38a3bea.png)

Do you think it could be a windows issue? 

I just tried to run the same commands you have above inside a script from the command prompt on 2 different windows 10 machines:

![image](https://user-images.githubusercontent.com/55868530/143666240-25c35d54-43da-403c-a08c-386eff16f8db.png)
![image](https://user-images.githubusercontent.com/55868530/143666307-70052f9d-b7b7-4a67-a831-71dd4d13a11b.png)

And I get these ? symbols instead of the symbols for the bar. The repetitive printing stuff is gone, so it could be a new/different issue. 

Same with your demo:
![image](https://user-images.githubusercontent.com/55868530/143666547-2c3ea578-9bca-46a9-81f0-0854f757a40c.png)

**Comment by TheTechRobo** [comment]
That's just a bad font. Install a Nerd Font and configure cmd to use it.
