### ISSUE TITLE
ZeroDivisionError exception if progress is very fast

### ISSUE THREAD

**Issue by davido84** [rsalmei/alive-progress#165]
If the progress is very fast, then the elapsed time rate can become zero. This causes a zero division exception when computing the ETA.

For example, see line 21 in simple_eta():
return (logic_total - pos) / rate   # [No check for rate == 0]

**Comment by rsalmei** [comment]
Windows, am I right?

**Comment by davido84** [comment]
Correct, happens in Windows.

Best regards,
David

**Comment by rsalmei** [comment]
I thought so...
Windows has a crappy timer, I've seen something similar in another project of mine.
But actually, Python 3.7 is supposed to improve on that, which version are you using?
Do you have some code to simulate it?

**Comment by davido84** [comment]
Hmmm... I was using Python 3.10, but unfortunately I no longer have the
code which shows it since it was just a temporary hobby project which I
abandoned.

Should be reproducible however with just a very fast 0-100 progress in less
than a second -- I believe that's about how fast mine was running. Also it
would happen every time so it was very consistently reproducible.

Best Regards,
David

**Comment by rsalmei** [comment]
This is the fastest context we could ever build: one that executes no code at all:

```python
In [1]: with alive_bar(10) as bar:
   ...:     pass
   ...:
|⚠︎                                       | (!) 0.00/10.0 [0%] in 0.1s (0.00/d)
```

And even this doesn't break in macOS. I suppose in Linux it works the same.
So, as you see, I cannot simulate it here, that's why I'm wary of including any protection for this. Especially in a very hot statement that calculates the current rate in every single frame, up to 60 times per second...

But I'll think of something.

**Comment by rsalmei** [comment]
Thanks, I appreciate the more in-depth description.
But how unfortunate you've changed to another one...

Anyway, I don't think it has anything about that too.
Nothing different happens with abrupt skips like those, and my `alive-progress` isn't susceptible to them at all.
Here are two cases where this could happen: a progress with `total=1`, and a manual progress that goes to 100% in one step:
<img width="635" alt="image" src="https://user-images.githubusercontent.com/6652853/174213258-1e5f69a1-dc60-481e-8f07-daf5c5db435f.png">
Both work as expected.

But that's OK, if you change your mind and change to `alive-progress` again, we can sort it out.
