### ISSUE TITLE
Is there a way to query the stats()

### ISSUE THREAD

**Issue by MakeHer** [rsalmei/alive-progress#166]
Loving this library. However, I'm wondering if I can use it to query the eta or stats so I can use it with other methods of reporting like, say, a notifier.
```
with alive_bar(len(stuff)) as bar:
    notifier.send_msg(f"Started process")
    for item in list(stuff):
        bar()
        if bar.current == 10: # after the first 10 steps give an eta
          notifier.send_msg(bar.stats())
    notifier.send_msg(f"Process finished")
```

**Comment by rsalmei** [comment]
Hey, thank you!

Humm, that's a very interesting use... I do have all this info, but they are not externalized anywhere.
I surely can publish them for you, gonna think about it 👍

**Comment by rsalmei** [comment]
Does it work for you if I externalize the internal `eta` (either its string rendition, or the raw number of seconds), together with the `rate` (either rendered or raw too)? Those are the components of the stats widget.

**Comment by MakeHer** [comment]
Those two would be perfect. Appreciate you looking into this.

**Comment by rsalmei** [comment]
You're welcome.
It's done, it will be included in the next release!

<img width="689" alt="image" src="https://user-images.githubusercontent.com/6652853/173248268-5898f213-4ebb-43be-91a2-18b8954d844f.png">
👍
