### ISSUE TITLE
`tests` package is included in the package installation

### ISSUE THREAD

**Issue by jhonatan-lopes** [rsalmei/alive-progress#167]
Hi @rsalmei!

I've discovered that when installing `alive-progress`, the `tests` package is included in the pip installation erroneously.

When pip installing `alive-progress` on a clean venv, this was the directory structure of the venv's `site-packages` that I got:

```bash
├── about_time
├── about_time-3.1.1.dist-info
├── alive_progress
├── alive_progress-2.4.1.dist-info
├── _distutils_hack
├── grapheme
├── grapheme-0.6.0.dist-info
├── pip
├── pip-22.0.4.dist-info
├── pkg_resources
├── setuptools
├── setuptools-58.1.0.dist-info
└── tests
```
And the `tests` folder is the following:

```bash
├── animations
├── core
├── __pycache__
└── utils
```
which is the directory structure of `alive-progress/tests`.

I believe that this is caused by the `find_packages` function on `setup.py` not excluding the `tests` package:

https://github.com/rsalmei/alive-progress/blob/09125795c2758ea44688adb6c5c0ac9fe6eb1595/setup.py#L55

**Comment by rsalmei** [comment]
Hello, @jhonatan-lopes.

Yes, I do know the tests dir was included, but that has never stood as a problem to me.
Why do you think it is?

**Comment by jhonatan-lopes** [comment]
So, I was having this weird issue with `Tox`, `mypy` and `django-stubs`. My package dir structure is the following:

```bash
myproject
├── example/
├── myapp/
├── tests/
├── manage.py
├── poetry.lock
├── tox.ini
└── pyproject.toml
```
With `mypy` and `django-stubs`, it is necessary to provide the path to a Django settings file to be used on tests configuration. Initially, I was using a `settings.py` file from my `example` project. On my `pyproject.toml` I had:

```toml
[tool.django-stubs]
django_settings_module = "example.settings"
```
This configuration ran without issues.

Later, I wanted to keep the tests settings separate from the example settings, so I edited the `pyproject.toml` for the following:

```toml
[tool.django-stubs]
django_settings_module = "tests.settings"
```

When running `mypy` on this case, I ran onto the following error:

```
Error constructing plugin instance of NewSemanalDjangoPlugin

Traceback (most recent call last):
  File "/home/user/dev/myproject/.tox/mypy/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/home/user/dev/myproject/.tox/mypy/lib/python3.8/site-packages/mypy/__main__.py", line 12, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 96, in main
  File "mypy/main.py", line 173, in run_build
  File "mypy/build.py", line 180, in build
  File "mypy/build.py", line 231, in _build
  File "mypy/build.py", line 478, in load_plugins
  File "mypy/build.py", line 456, in load_plugins_from_config
  File "/home/user/dev/myproject/.tox/mypy/lib/python3.8/site-packages/mypy_django_plugin/main.py", line 70, in __init__
    self.django_context = DjangoContext(self.plugin_config.django_settings_module)
  File "/home/user/dev/myproject/.tox/mypy/lib/python3.8/site-packages/mypy_django_plugin/django/context.py", line 96, in __init__
    apps, settings = initialize_django(self.django_settings_module)
  File "/home/jplopes/user/dev/myproject/.tox/mypy/lib/python3.8/site-packages/mypy_django_plugin/django/context.py", line 78, in initialize_django
    settings._setup()
  File "/home/user/dev/myproject/.tox/mypy/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/jplopes/user/dev/myproject/.tox/mypy/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tests.settings'
ERROR: InvocationError for command /home/user/dev/myproject/.tox/mypy/bin/mypy test_houses (exited with code 1)
```
This is caused by `mypy` and `django-stubs` paths being configured first to `myproject/.tox/mypy` which finds the `tests` module installed from `alive-progress` in the `.tox/mypy` virtual environment before finding it on the project root.

We can use the following piece of code where `django-stubs` imports their modules to figure out the import precedence:

```python
# Print `tests` package location
import tests

for idx, path in enumerate(sys.path, 1):
    print(f'{idx} - {path}')

print(f'\ntests module location - {tests.__file__}')
```
which gives:
```bash
1 - /home/user/dev/myproject/.tox/mypy/bin
2 - /usr/lib/python38.zip
3 - /usr/lib/python3.8
4 - /usr/lib/python3.8/lib-dynload
5 - /home/user/dev/myproject/.tox/mypy/lib/python3.8/site-packages
6 - /home/user/dev/myproject

tests module location - /home/user/dev/myproject/.tox/mypy/lib/python3.8/site-packages/tests/__init__.py
```

Again, we can see that Tox's virtual environment takes precedence, with the project root being the last item on the path.

If I manually remove the `tests` folder from `.tox/mypy` virtual environment, everything works perfectly.

I understand that this is a very convoluted bug which is not completely related to `alive-progress`. It was just an unfortunate coincidence that the `tests` package was included here and caused this. However, this could have happened with any other python library that happened to include a `tests` folder with the pip installation.

I will try to raise this issue with `django-stubs` as well to see if the project-root can take precedence when importing modules.

I'm proposing the removal of the `tests` folder so that this import conflict does not repeat with other packages as well (however remote this might be), since `tests` is such a common name to be used on project roots. Also, since it is not required for the functioning of the library, I do not believe that it should be included in the pip installation.

**Comment by rsalmei** [comment]
WOW, thanks for this amazing and thorough analysis! 👏 

I have no words for you besides Sure, let's remove it!!
I'll include this in the next release, thank you, man!
