### ISSUE TITLE
Pycharm truncating the output line

### ISSUE THREAD

**Issue by macksjeremy** [rsalmei/alive-progress#173]
Hi, I'm running my code pretty similarly to the base methodology, but seem to lack an output ETA or any sort of runtime statistics other than the completion, which while not critical, would be a nice addition. There's no duration/eta checker showing in my output.

My output looks like: Running CRAFT Detection |█████████▌                              | ▆▄▂ 346/1466 

And the code chunk running it looks like
```python
    bartitle = 'Running CRAFT Detection'
    with alive_bar(len(results), force_tty=True, title=bartitle) as bar:
        for i in results:
            if '.jpg' not in i:
                continue
            count_k += 1
            i = res_path + i
            img = cv2.imread(i)
            if (img.shape[0] > 1600 or img.shape[1] > 1600):
                print(i, "is too big to be put into model currently. Skipping","Shape is", img.shape)
                oversized.write(i)
                time.sleep(0.05)
                bar()
                continue
            bounds = annotate_image(reader,i)
            if(bounds!= [[]]):
                output_dict[i] = {}
                output_dict[i]["bbox"] = bounds
            time.sleep(0.05)
            bar()
```
I'm curious what I'm missing here.

**Comment by TheTechRobo** [comment]
Is your terminal wide enough to fit it?

Also, please wrap your code in backticks like this:

    ```
    def generate_random_number():
        return 4
    ```

**Comment by macksjeremy** [comment]
![image](https://user-images.githubusercontent.com/31860185/176031154-2a96fb84-204a-4e36-a692-d27b54841ce6.png)

As far as I can tell it should be. I'm using a very recent version of pycharm, with plenty of room.

> Is your terminal wide enough to fit it?
> 
> Also, please wrap your code in backticks like this:
> 
> ```
> ```
> def generate_random_number():
>     return 4
> ```
> ```

**Comment by rsalmei** [comment]
Hi, it seems your pycharm is really truncating the line.
In your latest screenshot we can clearly see the monitor is there:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/6652853/176256282-2d1f97ca-769d-49cf-b8ca-de56ee04d689.png">
It should be `[0%]`, and the other widgets like elapsed time and ETA should be right next to it...

Anyway, I'm not sure what could be causing it. How is your terminal config?

**Comment by rsalmei** [comment]
That's what I thought too...
I went to investigate it, and found it!!
Just running an `alive-progress` script in Pycharm was not fluid at all, sluggish and slow, but on top of it, it was TRUNCATING the line!

It is an easy fix:
<img width="281" alt="image" src="https://user-images.githubusercontent.com/6652853/176361520-f627cd74-11dc-4de6-8a1d-34ad44462cda.png">

I did know about that option, which I always turn on nowadays, but I'd never noticed that it truncates the line when turned off too... And since the terminal gets sluggish as hell on top of it, I don't know JetBrainsains made this option, at all...

**Comment by macksjeremy** [comment]
> That's what I thought too... I went to investigate it, and found it!! Just running an `alive-progress` script in Pycharm was not fluid at all, sluggish and slow, but on top of it, it was TRUNCATING the line!
> 
> It is an easy fix: <img alt="image" width="281" src="https://user-images.githubusercontent.com/6652853/176361520-f627cd74-11dc-4de6-8a1d-34ad44462cda.png">
> 
> I did know about that option, which I always turn on nowadays, but I'd never noticed that it truncates the line when turned off too... And since the terminal gets sluggish as hell on top of it, I don't know why JetBrains made this option at all...

This works, thanks for the help. Wondering why PyCharm works like that as a default. Definitely a closed issue. Now my loading  bar is very pretty :)

**Comment by rsalmei** [comment]
Awesome, glad to help!

**Comment by Schobs** [comment]
Did anyone solve the multiple line printing issue? I'm on Fedora, Linux. Thank you.

**Comment by Alexander-Serov** [comment]
I have had a similar problem in the pycharm Terminal (not console) and this issue made me realize it wasn't a problem with `alive-progress`, thanks!
