### ISSUE TITLE
alive_bar not working in Jupyter

### ISSUE THREAD

**Issue by Miladiouss** [rsalmei/alive-progress#178]
The alive bar does not show during Jupyter cell process and only outputs the final frame:

```py
from alive_progress import alive_bar
from time import sleep

x = list(range(50))
with alive_bar(len(x), title='Jupyter Alive Progress Bar:') as bar:
    for i in x:
        sleep(.1)
        bar()
```

```
Jupyter Alive Progress Bar: |████████████████████████████████████████| 50/50 [100%] in 5.0s (9.98/s) 
```
Things work properly in my terminal. 

Here is my system configuration if needed:

- Ubuntu 22.04

- Alive Progress:
```
alive-progress            2.4.1                    pypi_0    pypi
```

- Jupyter with Anaconda:
```
jupyter-server            1.18.1                   pypi_0    pypi
jupyter_client            7.2.2              
jupyter_core              4.10.0           
jupyterlab                3.4.3                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.15.0                   pypi_0    pypi
jupyterlab-widgets        1.1.0                    pypi_0    pypi
```

**Comment by rsalmei** [comment]
Well, if there was that output, it seems to be working to me.
What did happen?

**Comment by Miladiouss** [comment]
There is no progress bar. After the cell is finished, the output above is printed, with that warning sign emoji (⚠︎).

**Comment by rsalmei** [comment]
Exactly what @TheTechRobo said, thanks.
And, if it appears only after ending, this is intended behavior, since the jupyter does not report itself as interactive. You have to use `force_tty=True`.

Please show your code, then we would not have to be figuring things out by ourselves.

**Comment by Miladiouss** [comment]
Thank you @TheTechRobo. As your suggestion, providing the `force_tty=True` corrects the behavior :+1: 

```py
from alive_progress import alive_bar
from time import sleep

x = list(range(50))
with alive_bar(len(x), title='Jupyter Alive Progress Bar:', force_tty=True) as bar:
    for i in x:
        sleep(.1)
        bar()
```
