### ISSUE TITLE
with in with

### ISSUE THREAD

**Issue by dron3flyv3r** [rsalmei/alive-progress#181]
Hi I have a problem

when I make a alive_bar using "with alive_bar()" in a another "with alive_bar()", it try's to overwrite one another. Is it me that do something wrong or is it just how it is made??

**Comment by MathiasYde** [comment]
Hi, nested alive bars are not implemented as of now. (See https://github.com/rsalmei/alive-progress#:~:text=enable%20multiple%20simultaneous%20bars%2C%20for%20nested%20or%20multiple%20activities%20(this%20is%20always%20requested!)) but the tdqm module supports this.

**Comment by rsalmei** [comment]
Hello @dron3flyv3r, thanks @MathiasYde,

Yeah, I didn't implement this yet, see #98 for the latest trail on this subject.

In the meantime, please use only one `with alive_bar()` context.
You can simply sum up all the steps' sub-steps and monitor them here.
You can even use multiprocessing, as long as only the main thread enters the `alive_bar` context.
