### ISSUE TITLE
[Question] Git clone progress bar

### ISSUE THREAD

**Issue by MichaelPetersen22** [rsalmei/alive-progress#182]
Is it possible to use this for actions such as a git clone?
If so any pointers on how to do so?

**Comment by TheTechRobo** [comment]
I think you might have to parse git's progress output, but not 100% sure on that.

**Comment by rsalmei** [comment]
Please explain it better @MichaelPetersen22, I'm not sure what you're talking about.

**Comment by MichaelPetersen22** [comment]
When git cloning, it does not immediately copy a repo the the computer, (i.e. it takes time to clone) I was wondering if it would be possible to have a load bar for this process.

**Comment by rsalmei** [comment]
No, I don't think so. This is a Python library, intended for use in Python programs.
The `git` tool is a binary program, I can't see a way to integrate them.

**Comment by rsalmei** [comment]
Well, if you are writing a Python program, and all you want is a cool animated progress bar while you run `git clone` on the background, there's nothing preventing you from that. It is not hard.
In the extreme case, if you were really creating a new frontend for `git clone`, I guess you could parse its output from the background process, this is way harder, but possible too.
Anyway, you can do anything with `alive-progress`, as long as it's in a Python program 👍
