### ISSUE TITLE
Compact spinners ?

### ISSUE THREAD

**Issue by stuaxo** [rsalmei/alive-progress#183]
Does alive_progress allow for compact spinners ?

I want something to animate while my service waits to connect to celery, I noticed that there are some hourglass emojis, alternating between the 3 would make it look like the sand was moving ⏳⌛ there's also the classic spinning slashes I guess /-\|

**Comment by rsalmei** [comment]
Sure! 

You could choose one ready to use from showtime (send its name in `spinner` argument):
```python
from alive_progress.styles import showtime

showtime()
```

Or, you can even create your own! I've made several advanced tools to create and visualize custom spinners.
For example, look at the `radioactive` spinner in showtime. If you wanted to use something like that sparkling circle, you could:
```python
from alive_progress.animations.spinners import frame_spinner_factory
spark = frame_spinner_factory('∙○⦿●')
```

And call with it with the actual instance: `with alive_bar(..., spinner=spark, ...) as bar:`

You can also evaluate your creations! Behold:
<img width="892" alt="image" src="https://user-images.githubusercontent.com/6652853/182670092-264ab177-bc31-4d08-b68a-0f0ece91790a.png">

Call `.check(3)` and you can even see it animating!
![Untitled](https://user-images.githubusercontent.com/6652853/182670299-37be83c8-7ac1-4ce4-b716-adbb4c52a95b.gif)

That's it, you have a lot more tools to generate whatever you need, read more details in the README [here](https://github.com/rsalmei/alive-progress#create-your-own-animations) 👍

**Comment by stuaxo** [comment]
Thanks, there's a lot of good info there.

Heh, maybe in the future Unicode will add some more animation to the hour glass so it's easy to achieve something like the old turning hour glass on Windows 95.
