### ISSUE TITLE
Alive Bar has constant Enter throwing off terminal

### ISSUE THREAD

**Issue by AliceFischer96** [rsalmei/alive-progress#186]
![image](https://user-images.githubusercontent.com/34352127/188235868-268b538b-40bb-4474-b93c-515a75892e2f.png)
When Trying to use alive bar I am running into a very frustrating issue where it is displaying the counter every line ( appears to be part of progress.py line 188), thus separating out giant chunks of my prints. Even if I set enrich_print to false it just has empty lines. 

I can't find a single mention of this bug or how to fix it, please resolve

**Comment by TheTechRobo** [comment]
That's probably because you're accidentally using a print statement. Otherwise, why would `enrich_print` fix it?

**Comment by rsalmei** [comment]
Which version are you using?
I've seen once enters being sent to the Python terminal once, but it was with a very old `alive-progress` version, pre-2.0 if I'm not mistaken.

Anyway, there isn't any "mention of this bug" but there isn't any bug like this. I think it is something in your environment, and I'll help you find what it is.

Please test the most simple one too:
```python
with alive_bar(1000) as bar:
    for i in range(1000):
        time.sleep(.01)
        bar()
```
Does the same thing happen?

**Comment by AliceFischer96** [comment]
@rsalmei I'm using the latest alive-progress version as far as I'm aware, pip3 installed it this month.

The most simple one doesn't have the issue, but I can't find a single print in my function to cause the error I'm seeing. 

I do have a logger writing to a file, but not to the terminal. That shouldn't affect this, should it?

**Comment by TheTechRobo** [comment]
Try stripping down your code until it's the bare minimum that causes the problem. That should help you narrow it down.

**Comment by rsalmei** [comment]
Yes, exactly was I was going to say now, thanks @TheTechRobo.

@AliceFischer96, if the simplest one does work, I think we can be sure it is not `alive-progress`.
You could either show us how are you calling it, or the best would be to narrow it down so the root cause becomes apparent.

No, the logger to a file should not mess with this in any way.

**Comment by AliceFischer96** [comment]
Alright after testing it appears that alive_bar has an issue with await.
If I comment out any coroutine checks using the await keyword this error doesn't appear.

**Comment by TheTechRobo** [comment]
Check the coroutine that it's calling. That could very well be causing print satements

**Comment by AliceFischer96** [comment]
@TheTechRobo I'm using await asyncio.sleep(0.01) for testing the simple loop versus mine, so no prints

**Comment by TheTechRobo** [comment]
Interesting. Let's see if I can reproduce.

**Comment by TheTechRobo** [comment]
Can't reproduce:

```
from alive_progress import alive_bar

import asyncio

async def test():
    return "Hi"

async def hello():
    with alive_bar(total=60) as bar:
        for i in range(60):
            bar()
            await asyncio.sleep(0.1)
            assert await test() == "Hi"

asyncio.run(hello())
```
![image](https://user-images.githubusercontent.com/52163910/189448323-5a0599e6-345d-4eca-a5a0-07320b81498c.png)

**Comment by AliceFischer96** [comment]
If I run this:
![image](https://user-images.githubusercontent.com/34352127/189448564-bcc6b23c-bf10-4a0f-a5ad-4f2abe90f1ac.png)
I get the enter issue, but removing the await resolves it.

Maybe its a combination of using the serial port and having coroutines?

**Comment by rsalmei** [comment]
As far as I'm aware, I think It can't be anything related to `await` or coroutines.
See, these functions only move from the main thread into an async engine, which can be interrupted and recalled at any time (when there's pending I/O).
`alive-progress` **does not** use any async function, it is completely sync. The refresh is performed on a Python Thread from the `multithreading` module. This means I leave the main thread free for the user, and make the magic happen in a background thread, which is not affected at all by async processing.

All I can see til now is that, if you remove that await, you are removing the sleep from the loop. I can't possibly know how that messes up your program, but that's it.

I loved the example @TheTechRobo came up with!
Please, try to break it! Try to understand in your system how that code could trigger this weird behavior.

**Comment by rsalmei** [comment]
Hey @AliceFischer96, please any news on this?
I'd really to understand what is causing these linefeeds on your system...

**Comment by rsalmei** [comment]
Well, new year, no response for months, closing this as stale.
