### ISSUE TITLE
Run incorrectly in cmder in windows

### ISSUE THREAD

**Issue by flt6** [rsalmei/alive-progress#193]
In windows, it runs like this.
![image](https://user-images.githubusercontent.com/42725841/193997786-3a1483c1-a9ac-44f4-bbf6-3a38a6f78d04.png)

**Comment by rsalmei** [comment]
I've explained in other issues that windows do not support ANSI Escape Codes, which are necessary to read the number of columns available and to control the cursor.

But I think windows users can do something to counter those, like installing `colorama` and/or using another terminal, but I'm not sure as I've never used windows for python programming.
Please search for closed issues regarding windows here.

**Comment by flt6** [comment]
I have checked that ***ANSI Escape Codes is available in console cmder***.

I have checked with the following ways:
1. print "\033" directly in cmder:
```python
print("\033[1;31mColorful text.\033[0m")
```
![image](https://user-images.githubusercontent.com/42725841/194315110-8aae8d85-0a29-4660-8649-76d3df5ebfe0.png)
2. run `colorama.init` before using alive_progress
```python
from alive_progress import alive_bar
from colorama import init
from time import sleep

init()
with alive_bar(10) as bar:
    bar.text = "111111111111111111111111111111111111111111111111111111111111111111"
    for i in range(5):
        sleep(2)
        bar()
```
![image](https://user-images.githubusercontent.com/42725841/194315501-7235795f-8894-4fa7-910a-001703a79c6c.png)

**Comment by TheTechRobo** [comment]
Please provide your code or else we cant help you.

**Comment by flt6** [comment]
> Please provide your code or else we cant help you.

I have referenced at last commit.
```python
from alive_progress import alive_bar
from colorama import init
from time import sleep

init()
with alive_bar(10) as bar:
    bar.text = "111111111111111111111111111111111111111111111111111111111111111111"
    for i in range(5):
        sleep(2)
        bar()
```

**Comment by rsalmei** [comment]
That's excellent! Thanks for the additional info.
I'm glad it does support ANSI Escape Codes. Which terminal is this? I suppose it is not the default one.

It seems it is not retrieving the terminal size, that's why `alive-progress` does not know where to clip the row.
A few months ago, to support some unusual environments, I started using the `shutil` version, which does not fail ever and just returns 80 columns in these cases...
Please test this:
```python
In [2]: import os

In [3]: os.get_terminal_size()
Out[3]: os.terminal_size(columns=120, lines=40)
```

**Comment by TheTechRobo** [comment]
They said cmder, so from a quick google looks like https://cmder.app/

**Comment by flt6** [comment]
I have run your test code.
```python
>>> os.get_terminal_size()
os.terminal_size(columns=149, lines=41)

>>> os.terminal_size(columns=120, lines=40)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: structseq() missing required argument 'sequence' (pos 1)
>>> os.terminal_size((120,40))      # maybe it should be like this
os.terminal_size(columns=120, lines=40)
```
