### ISSUE TITLE
Remove "on: %d" before output

### ISSUE THREAD

**Issue by RedStylzZ** [rsalmei/alive-progress#195]
Hey there,

would it be possible to add an option to remove the prefix "on %d" before a print message when using alive-progress?
Or is there already an option? If yes I wasn't able to find it.

**Comment by TheTechRobo** [comment]
https://github.com/rsalmei/alive-progress#configurations

Use `enrich_print=False`

**Comment by rsalmei** [comment]
Hey @RedStylzZ,

Yes, it is clearly (?) there in the configurations:
> enrich_print: [True] enriches print() and logging messages with the bar position

Thanks @TheTechRobo 👍

**Comment by RedStylzZ** [comment]
Oh wow, I'm sorry, thank you
