### ISSUE TITLE
AttributeError: 'function' object has no attribute 'flush'

### ISSUE THREAD

**Issue by jhmenke** [rsalmei/alive-progress#2]
I am trying a simple example to replace tqdm with the alive_bar
`with alive_bar(int(self.ann_params["epochs"])) as pbar:`

Unfortunately, this line raises an Exeption: 
```NameError: free variable 'event' referenced before assignment in enclosing scope
Exception ignored in: <function alive_bar at 0x7fefe58f6ae8>
AttributeError: 'function' object has no attribute 'flush'```

I am using Python 3.7.3 on elementaryOS (Ubuntu derivative). Am i doing something wrong?

**Comment by jonturneratduke** [comment]
If my experience on MacOS is any guide, you're sending some output to the console which interferes with alive_bar's call to sys.stdout.flush().

**Comment by rsalmei** [comment]
Hey @jhmenke, I'm using 3.7.3 myself and this error is not triggered.
Could you help me debugging this?
I didn't try it on ubuntu, but should work.
Is this Python CPython?

**Comment by rsalmei** [comment]
I was looking into Python Streams (https://docs.python.org/2.7/library/io.html#module-io), and really there are other methods a stream should have.

Are your code by any chance calling `flush()` directly?

**Comment by jhmenke** [comment]
Okay, so it works in the regular terminal.

I was using PyCharm and i guess that somehow has a different terminal which does not work. Interestingly, tqdm works just fine so i guess something has to be checked and done differently.

Thanks for your comments though!

**Comment by rogerio-geru** [comment]
No problem!

I can release a version with `flush` support, maybe it would work.
Anyway, I was not aware of this pycharm terminal problem. I'll try it there and report back.

**Comment by rogerio-geru** [comment]
Great news @jhmenke, I've made it work in Pycharm! At least in the latest 2019.2 it did work.
Tonight I'll release the 1.1 version with pycharm support.

**Comment by rogerio-geru** [comment]
It's curious I did not have the `flush` error you reported.
I'll let you know when it's available, and please tell me if it does work  for you.

**Comment by rsalmei** [comment]
Fixed and released in #5.
Could you please confirm it does work for you now? @jhmenke

**Comment by jhmenke** [comment]
It works in the sense that there is no Exception thrown anymore, but i cannot see the progress bar. There is no output at all weirdly.

But if i activate "Emulate terminal in output console" it works fine (as before), so i guess that's already an adequate solution. Thanks for your time!

**Comment by rsalmei** [comment]
You're welcome. 👍
