### ISSUE TITLE
How to use the progress bar without the context manager?

### ISSUE THREAD

**Issue by Advik-B** [rsalmei/alive-progress#200]
I dont want to use the `with` context manager

```py
from alive_progress import alive_bar

bar = alive_bar()
# Set the total number of steps
bar.total = 100
# Increment the progress bar
???
```

**Comment by rsalmei** [comment]
Why not? I made it that way so it could be always correctly initialized and finalized, there isn't much sense trying to not use it.

**Comment by Advik-B** [comment]
Cause of this
<img width="358" alt="Screenshot 2022-10-30 at 12 26 46 AM" src="https://user-images.githubusercontent.com/86160411/198848322-1c002231-96d9-4e21-be05-6fe163a3caf6.png">

**Comment by rsalmei** [comment]
Ok, you'd do it like this:
```python
class ProgressBar:
    def __init__(self, value: int = None):
        self.cm = alive_bar(total=value)
        self.bar = self.cm.__enter__()

    def step(self):
        self.bar()

    def close(self):
        self.cm.__exit__(None, None, None)
```

To use it:
```python

progress = ProgressBar(1000)
for i in range(1000):
    time.sleep(.01)
    progress.step()
progress.close()
```

**Comment by Advik-B** [comment]
Thank you will. Try this. Please keep the issue open

**Comment by Advik-B** [comment]
Okay, will try this

**Comment by rsalmei** [comment]
Ok, I'm closing this one, but feel free to reply here if you need any more help 👍
