### ISSUE TITLE
Not an issue, a how-to request...

### ISSUE THREAD

**Issue by MrTribbs** [rsalmei/alive-progress#204]
Disregard.

**Comment by TheTechRobo** [comment]
https://github.com/rsalmei/alive-progress#displaying-messages 

You probably want `bar.text = "..."`

**Comment by MrTribbs** [comment]
Ok I get that, what I was meaning from my noobish post, was how to incorporate the following into my code.

> from alive_progress import alive_bar: import time, logging
> 
> logging.basicConfig(level=logging.INFO)
> logger = logging.getLogger('alive_progress')
> 
> with alive_bar(1000) as bar:
>     for i in range(1000):
>         if i and i % 300 == 0:
>             print('found')
>         if i in (450, 750):
>             logger.info('cool!')
>         time.sleep(0.01)
>         bar()    

     
So for example:

> from alive_progress import alive_bar: import time, logging
> 
> logging.basicConfig(level=logging.INFO)
> logger = logging.getLogger('alive_progress')
> 
> with alive_bar(1000) as bar:
>     for i in range(1000):
>         if i and i % 300 == 0:
>             print("Starting Migration.")
>             m.click(740, 1008)
>             time.sleep(2)
>         if i in (450, 750):
>             print("Selecting Source Connection.")
>             m.click(828, 507)
>             time.sleep(2)

            
So I get the 1000 is the total time and the prints will happen at 300, 450, 750,

Do I just need to time it out, because the overall script of mine takes about 12-16 minutes to complete, or is there a more efficient way for a longer script?

**Comment by TheTechRobo** [comment]
What do you mean?

**Comment by MrTribbs** [comment]
@TheTechRobo 

so my python script is long and overall it takes 12-16 minutes to finish.

so for each print() I want to do along do along the length of the full script do I need to time how long the script runs to get to print(1) then how long the script runs to get to print(2) or is there an easier way?

to over simplify so hopefully i can ask this right:

```
with alive_bar(1000) as bar:
for i in range(1000):

if i == 0:
print('Start')

if i in (250):
print('Running')

if i in (500):
print('Still Running')

if i == 1000:
print('Done')
```

Do I need to time my script while it runs to get the proper "time" where print('Running'), print('Still Running'), etc actually starts, or is there a simpler way, I'm sure most of you don't go through and time everything to the millisecond.

**Comment by TheTechRobo** [comment]
So do you want to change the message when a certain amount of time elapses?

**Comment by rsalmei** [comment]
Ok, I hope you've achieved what you needed @MrTribbs 👍
