### ISSUE TITLE
Unknown mode always end with a warning `(!)`

### ISSUE THREAD

**Issue by divulgacheur** [rsalmei/alive-progress#211]
According to [README gif](https://github.com/rsalmei/alive-progress/raw/main/img/alive-demo.gif) alive_bar in `unknown` mode must end without warning character `(!)` :thinking: 

Example :
```python3
with alive_bar(total=0, title='Searching', stats=False, disable=opts.quiet, monitor="Page {count}") as progress_bar:
    while ... is False:
        progress_bar()
    progress_bar.title = 'Search has finished'


```

Output (Python 3.10)
```python3
Search has finished |████████████████████████████████████████| (!) Page 1 in 4.0s 

```

Expected output:
```python3
Search has finished |████████████████████████████████████████| Page 1 in 4.0s 

```

**Comment by TheTechRobo** [comment]
Why is your `total` set to 0? That is likely the root of the problem.

**Comment by divulgacheur** [comment]
I thought it was the mandatory value in order to run in `unknown` mode, but the result is the same without `total=0`.

**Comment by TheTechRobo** [comment]
I'm not sure then. @rsalmei will probably be able to figure it out.

**Comment by TheodoreHua** [comment]
Can confirm that this occurs on the latest version (`v2.4.1`) with or without a value passed into total. Seems to always have a warning character even in unknown mode. From a quick test, it doesn't occur in version `v2.2.0` but does occur in all versions above. Maybe I forgot to port something when updating from 2.2.0 -> latest but it does seem to match the documentation.

**Comment by rsalmei** [comment]
Humm, I'll take a look as soon as I can, thank you all for reporting it.

**Comment by rsalmei** [comment]
Hi, it is really a small bug, should be fixed in the next version 👍
