### ISSUE TITLE
README: GIFs don't show showtime being imported from styles subpackage

### ISSUE THREAD

**Issue by Alexander-Wilms** [rsalmei/alive-progress#214]
At first I tried `from alive_progress import showtime, Show`, but that fails with `ImportError: cannot import name 'showtime' from 'alive_progress'`

![image](https://user-images.githubusercontent.com/3226457/209135091-97ddfcf5-6387-457d-885b-6b8570db3ba7.png)

In the _Try it_ section, the following, working import command is given: `from alive_progress.styles import showtime`

**Comment by rsalmei** [comment]
Oh yes, that's because it is very complicated and time-consuming to regenerate these long gifs, so I won't unless I have something very different to display.
But I'll put a note right next to it, thanks.
