### ISSUE TITLE
How to use with requests.get

### ISSUE THREAD

**Issue by Acalann** [rsalmei/alive-progress#218]

**Comment by TheTechRobo** [comment]
Do you mean to show download progress? If so, I'm not sure Requests can do that.

**Comment by Acalann** [comment]
tqdm can do it

**Comment by rsalmei** [comment]
I'm not aware too of how this would work.

**Comment by rsalmei** [comment]
Ahh, it seems very easy. Requests support downloading in streaming mode, then you just open a progress bar for the chunks. I'll give an example later.

**Comment by rsalmei** [comment]
Here it is:
```python
from alive_progress import alive_bar
import requests

chunk_size = 1024
resp = requests.get('https://releases.ubuntu.com/22.10/ubuntu-22.10-desktop-amd64.iso', stream=True)
total = int(resp.headers.get('content-length', 0))
with open('ubuntu.iso', 'wb') as file, alive_bar(total, unit='B', scale=True) as bar:
    for data in resp.iter_content(chunk_size=chunk_size):
        size = file.write(data)
        bar(size)
```

And with the beauty `alive_progress` is known for:

https://user-images.githubusercontent.com/6652853/210184357-28ba8e0f-b66f-45d1-823a-2419f7377800.mov

**Comment by rsalmei** [comment]
Ahh, the best would be to use a chunk of 1000 with the SI scale I've used above, with also uses 1000 as it is becoming the new common in modern operational systems like macOS.
Using chunks of 1024, the ideal would be to use either the IEC scale (that uses 'i' kibibytes), or the modified SI2 I've created just for this, which retains normal SI units but uses 1024 as divisor.
