### ISSUE TITLE
Missing font symbols AND terminal ignoring ANSI Escape Codes on windows

### ISSUE THREAD

**Issue by baterflyrity** [rsalmei/alive-progress#220]
Hi! I'd like to use this library but unfortunately it does not work on my machine. 

Can you please point out missing requirements or fix this bug? 

![изображение](https://user-images.githubusercontent.com/15788974/211075276-36f02dc6-95d3-4e2e-b406-d83f06ca47bc.png)

**Comment by rsalmei** [comment]
Hi @baterflyrity,

That's weird since you seem to have a powerlevel prompt right in there!
Which font is your terminal using?
And which terminal is it? Perhaps the terminal does include its own set of powerlevel glyphs, but misses on other content... The usual fix for this is for you to install a nerdfont: https://www.nerdfonts.com/

**Comment by baterflyrity** [comment]
Hi! Thanks for reply.

My terminal characteristics are:
System: Windows 10
Shell: cmd.exe
Console: ComEmu
Terminal: Clink
Prompt: oh-my-posh
Font: JetBrainsMono Nerd Font Mono
Encoding: 866 (and can not be changed since Windows)
Python encoding: utf8
Python version: 3.11

Hence I can not understand why some glyphs are show as _?_ symbol. Do you have any ideas on this?

**Comment by baterflyrity** [comment]
Hello!
I've studied in details and figured out that this was my misconfiguration 😞. Actually ComEmu utilizes dedicated font for such symbols. Thus one has to just disable **Alternate font** checkbox or adjust it to Nerd Font etc.

![изображение](https://user-images.githubusercontent.com/15788974/212645818-4b2a6a45-c75e-401e-bd11-b0b3c08f090a.png)

All in all thanks for reply and sorry for bother)

**Comment by rsalmei** [comment]
That's great! I'm glad you've made progress!
Well, I don't know what more you could try besides tweaking the font, but I think you should be at peace with it, it is working already!

In that "Display features" section you mentioned, I wanted to show my newest support for WIDE CHARS, which was very very hard to do since they should animate together with SINGLE CHARS like spaces. So, in there I use Emojis, which are very different Unicode chars that are WIDE, i.e. they occupy two columns on the screen. And perhaps your terminal doesn't even support them...
In any case, this is what should happen there:

https://user-images.githubusercontent.com/6652853/213095003-81a054f7-0b49-45b1-821f-77ec7ab5033b.mov

**Comment by zooplibob** [comment]
I have the same issue on Windows. None of the spinners show up properly in the console window. Any idea how to fix this?
Jeff


<img width="1066" alt="Screenshot 2024-03-04 at 9 20 08 AM" src="https://github.com/rsalmei/alive-progress/assets/14338584/ea3162b7-1bc6-4d78-9f1e-dd4af372c168">

**Comment by rsalmei** [comment]
Unfortunately, no. I do not have a windows machine for dev, so I can't test it.
But all linux environments should be perfectly supported, I mean macOS and windows wsl2.
Do you use WSL2?

**Comment by zooplibob** [comment]
We use this for our automated testers which only run Windows. It would be really great if you could provide a solution to this, as your library has the best feature set. Its just looks bad when the spinners are shown as ? blocks.

**Comment by rsalmei** [comment]
Sure, I understand.
Please, try to run it with `classic` spinner and bar. These won't use any fancy characters, so they should work now.

**Comment by zooplibob** [comment]
Yes I tried the classic ones and they seem to work. Sad not to be able to us the fancier ones though.

**Comment by luewh** [comment]
Hello,

I have also encounter is issue.

I duplicate sys.stdout to a web component div and use "monospace" as font-family, here the outcome :
![image](https://github.com/user-attachments/assets/c3fa1d94-c756-416d-8328-1ae3dec6b65b)
When I remove the font it becomes to this : 
![image](https://github.com/user-attachments/assets/59a5efb5-41ad-459c-a672-c58410f6b110)
But it still has the weird "[?25l" character...

On the command line side, the outputs are normal :
![image](https://github.com/user-attachments/assets/74311f30-e00e-4ff5-96fb-696838694a99)

**Anyone knows css font-familly that would work correctly ?**

if need more detail herer the repo of the codes : https://github.com/luewh/Video-Script

**Comment by luewh** [comment]
> Hello,
> 
> I have also encounter is issue.
> 
> I duplicate sys.stdout to a web component div and use "monospace" as font-family, here the outcome : ![image](https://private-user-images.githubusercontent.com/85931693/382483329-c3fa1d94-c756-416d-8328-1ae3dec6b65b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NzM4ODAsIm5iZiI6MTczMDU3MzU4MCwicGF0aCI6Ii84NTkzMTY5My8zODI0ODMzMjktYzNmYTFkOTQtYzc1Ni00MTZkLTgzMjgtMWFlM2RlYzZiNjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDE4NTMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZmRmMWFiYTIzODg1YzFiMzQ4MWUyYjg3N2YxZjZjNDdiNDkzN2Q0NTJkZDc5ZTYxYWY0ZGI4YmEzYzdkNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lpA3hQ3unVsMvPH2gLzYGAfxVIuxsUQQfMAT72krjKw) When I remove the font it becomes to this : ![image](https://private-user-images.githubusercontent.com/85931693/382483646-59a5efb5-41ad-459c-a672-c58410f6b110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NzM4ODAsIm5iZiI6MTczMDU3MzU4MCwicGF0aCI6Ii84NTkzMTY5My8zODI0ODM2NDYtNTlhNWVmYjUtNDFhZC00NTljLWE2NzItYzU4NDEwZjZiMTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDE4NTMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNGMyNWYzNTkwZjVmNDUyMDc3OGZiMDQ3ZTc4Y2Y2ZGEwZTRiODYzZmM0MThkZDQwZjljN2VkZDg0NGM5ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.F3yJd3H2lj4mbLH8AapsVUTwRn9L8fRyFOEFDCUTG4I) But it still has the weird "�[?25l" character...
> 
> On the command line side, the outputs are normal : ![image](https://private-user-images.githubusercontent.com/85931693/382483894-74311f30-e00e-4ff5-96fb-696838694a99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NzM4ODAsIm5iZiI6MTczMDU3MzU4MCwicGF0aCI6Ii84NTkzMTY5My8zODI0ODM4OTQtNzQzMTFmMzAtZTAwZS00ZmY1LTk2ZmItNjk2ODM4Njk0YTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDE4NTMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMWMyODgzNmM5YTZmNWNjYjcxMGIzMDE2N2QzY2I4NjllN2ZiYTU2MjYzZTEzMjQ4NTVlNGFmNWEzNTg2M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rTmY1hTzOwh-yYviNdtxId9edT6iztQ9rTZrRRSBWSY)
> 
> **Anyone knows css font-familly that would work correctly ?**
> 
> if need more detail herer the repo of the codes : https://github.com/luewh/Video-Script

Error could comes from me, when I print("Stopped") asynchronously it fixes the issue... weird...
![image](https://github.com/user-attachments/assets/6dbd526f-c302-401d-b58f-ec048c2bf2d4)

**Comment by rsalmei** [comment]
> But it still has the weird "�[?25l" character...

It is not weird, it is called ANSI Escape Code. This one in particular is used to command the terminal to hide the cursor:
https://github.com/rsalmei/alive-progress/blob/35853799b84ee682af121f7bc5967bd9b62e34c4/alive_progress/utils/terminal/tty.py#L35

Your terminal does not understand these codes. When you printed something it didn't "fix" the issue, that happened because I only need to send the "hide cursor" command once to the terminal, when the `alive_bar` starts spinning.

I'd suggest trying `colorama`. It is supposed to make these codes work on windows.
Let me know if it does fix your issues.

**Comment by luewh** [comment]
> > But it still has the weird "�[?25l" character...
> 
> It is not weird, it is called ANSI Escape Code. This one in particular is used to command the terminal to hide the cursor:
> 
> https://github.com/rsalmei/alive-progress/blob/35853799b84ee682af121f7bc5967bd9b62e34c4/alive_progress/utils/terminal/tty.py#L35
> 
> Your terminal does not understand these codes. When you printed something it didn't "fix" the issue, that happened because I only need to send the "hide cursor" command once to the terminal, when the `alive_bar` starts spinning.
> 
> I'd suggest trying `colorama`. It is supposed to make these codes work on windows. Let me know if it does fix your issues.

Here is the result by using colorama as font-family
![image](https://github.com/user-attachments/assets/1dccb76f-52da-4c15-a464-021bb6be9133)

I solved the issue. Mine atleast.
I removed the ANSI Escape Code **?25l** from my web div and it works:
![image](https://github.com/user-attachments/assets/89e73601-971d-4136-8b4a-5b4b25ff7c52)
Something you missed is that when I printed (removes the **?25l**), the wave characters '▁▂▃▄▅▆▇█' become decodable.
I think it's the ANSI Escape Code that cause the entire line, especially those wave characters being wrong "encoded".

**Comment by luewh** [comment]
And, on my wondows terminal, your alive-pregress works perfectly, no render issue.
The issue appear when I duplicate the stdout on a web interface which is not a terminal.

**Comment by luewh** [comment]
New update:

'\x1b' is the real culprit, maybe.
I removed the '\x1b' from '\x1b?25l', also from '\x1b[K' :
during
![image](https://github.com/user-attachments/assets/b061b980-da72-4e51-bc84-32f563de6164)
end
![image](https://github.com/user-attachments/assets/63e1c69c-0650-4156-b6dc-69c9b0afe539)
It worked on '?25h' but not 'K'...

> https://github.com/rsalmei/alive-progress/blob/35853799b84ee682af121f7bc5967bd9b62e34c4/alive_progress/utils/terminal/tty.py#L26

**Comment by rsalmei** [comment]
Like I said yesterday, your terminal does not understand escape codes. `\x1b` is the ESC code, which prepends all commands.
How are you removing these codes?

**Comment by luewh** [comment]
> How are you removing these codes?

str.replace("\x1b","")

**Comment by rsalmei** [comment]
Yes, but that's not what I mean. I mean I'm printing them directly to stderr, so how are you capturing the strs I print?

**Comment by luewh** [comment]
> Yes, but that's not what I mean. I mean I'm printing them directly to stderr, so how are you capturing the strs I print?

My bad xD

```
class StdoutIntercept(object):
    def __init__(self):
        self.stdoutW = sys.stdout.write
        self.stderrW = sys.stderr.write
        sys.stdout.write = self.write
        sys.stderr.write = self.write
        self.queue = []
        self.carriage = False

    def __del__(self):
        sys.stdout.write = self.stdoutW
        sys.stderr.write = self.stderrW

    def write(self, msg):
        self.stdoutW(msg)

        if msg == "\r":
            # init carriage line
            if not self.carriage:
                # alive-progress remove ANSI Escape Code (hide the cursor on terminal)
                if "\x1b" in self.queue[-1]:
                    self.queue[-1] = self.queue[-1].replace("\x1b", "")
                else:
                    self.queue.append("")
            # rewrite carriage line
            else:
                self.queue[-1] = ""
            
            self.carriage = True
            return
        
        # stop carriage
        if msg == "\n":
            self.carriage = False
            # alive-progress remove ANSI clears line from cursor
            if "\x1b[K" in self.queue[-1]:
                self.queue[-1] = self.queue[-1].replace("\x1b[K", "")

        # append carriage line
        if self.carriage:
            self.queue[-1] += msg
        # append line
        else:
            self.queue.append(msg)

stdout = StdoutIntercept()

...

def logConsole(_):
    return ''.join(stdout.queue)

```

**Comment by rsalmei** [comment]
Yikes, you're capturing the hottest path of `alive-progress` and on top of that searching for strings in it... I can refresh the screen up to 60x per second, so that must be using a lot of processing power but I'm glad it works for you.

**Comment by rsalmei** [comment]
If there is a growing interest in this scenario, I could potentially implement a configuration that avoids emitting any ANSI Control Codes, with the expected limitations.

I'm closing it for now, thanks, everyone.
