### ISSUE TITLE
[Bug]: bar.text() breaks when inserting different lenght of strings

### ISSUE THREAD

**Issue by sergargar** [rsalmei/alive-progress#228]
The bar.text() breaks when inserting different length of strings:
<img width="404" alt="Screenshot 2023-03-02 at 16 24 36" src="https://user-images.githubusercontent.com/38561120/222471997-0be717ea-238a-41f8-97c0-7a6df2d1c1cb.png">
It should be `ap-south-east-1`
<img width="345" alt="Screenshot 2023-03-02 at 16 24 41" src="https://user-images.githubusercontent.com/38561120/222471902-a4690411-1f4c-4bfb-b819-0c5510cd9f5a.png">
It should be `ap-south-1`

**Comment by rsalmei** [comment]
It doesn't break, there isn't any bug in texts that I know of. Look:

https://user-images.githubusercontent.com/6652853/222478337-cacefa53-f316-4e67-b7d9-0aa5fa90e0c0.mov

Here is the code, if you'd like to try in your terminal:
```python
with alive_bar(1000) as bar:
    for i in range(1000):
        time.sleep(.01)
        bar()
        if i // 100 % 2 == 0:
            bar.text = f'A long text, that could take your whole line! {i}'
        else:
            bar.text = f'short text {i}'
```

**Comment by rsalmei** [comment]
Just for completeness, dynamic titles work too:

https://user-images.githubusercontent.com/6652853/222864167-504f33f6-b51c-4c46-8992-f36726cc3024.mov

**Comment by rsalmei** [comment]
And even both at the same time!!

https://user-images.githubusercontent.com/6652853/222864423-3feddab0-0ae7-43aa-9413-92ffe1155cdf.mov

That's it, man, there isn't any bug in these mechanisms.
