### ISSUE TITLE
loosing vscode syntax highlighting on a certain object using "alive_it" function

### ISSUE THREAD

**Issue by Illegal-Services** [rsalmei/alive-progress#233]
I've got an issue where "thread" loose it's [vscode](https://code.visualstudio.com/) syntax highlighting.

Here is my code, and my Python version, if needed: Python 3.11.2

```py
from typing import List

threads: List[threading.Thread] = []

for thread in alive_it(threads, theme="classic", bar="classic2", enrich_print=False):
    thread.join()
```

[vscode](https://code.visualstudio.com/) result:

![Code_2023-03-25_23-20](https://user-images.githubusercontent.com/62464560/227745103-15ca7a78-4d61-4a43-9aa0-ec296c763fd9.png)
![Code_2023-03-25_23-20 (2)](https://user-images.githubusercontent.com/62464560/227745105-7fe7b02a-546b-493f-9b09-2deb6cfa8e1c.png)
![Code_2023-03-25_23-20 (3)](https://user-images.githubusercontent.com/62464560/227745108-41149725-4cf7-4ece-9394-770e1b0b293c.png)

**Comment by rsalmei** [comment]
Hello again.
You're right, I do not annotate `alive_it` at all, and I really should.
But I'm not an expert in typing, would you know how to express this kind of "generics" in Python, I mean, a function that receives a `List[T]`, and yields exactly those `T` whatever they are?

**Comment by rsalmei** [comment]
I think I got it. With this, your example does get the correct type.

```python
T = TypeVar('T')

def alive_it(it: Collection[T], total: Optional[int] = None, *,
             finalize: Callable[[Any], None] = None,
             calibrate: Optional[int] = None, **options: Any) -> Iterable[T]:
```
