### ISSUE TITLE
Does the pycharm terminal not support alive-progress？

### ISSUE THREAD

**Issue by Chsongcumt** [rsalmei/alive-progress#234]
Hello rsalmei,

When I use `alive-progress` in the `pycharm`, it will prompt **"UserWarning: This must be run on a tty connected terminal"**. How can I solve this problem?

**Comment by Chsongcumt** [comment]
Code:
```
from alive_progress.styles import show_themes

show_themes()
```

**Comment by VanSHOE** [comment]
Go into pycharm run configurations. 
Run > Edit Configurations 

Tick `Emulate terminal in output console`

If you want it to apply to all python files you create from now, I believe you can also tick it after clicking on `Edit configuration templates`

**Comment by rsalmei** [comment]
Hello @Chsongcumt.

Exactly what @VanSHOE has said, thanks!
There were other tickets about this, please always search in the Closed section before creating a new one.

**Comment by rsalmei** [comment]
Oh sorry, I just noticed that you tried to run `show_themes()`...
That one, as well as the other show variants, I purposely do not run in anything but an actual interactive terminal. They are heavy, and would be sluggish in a heavily instrumented console like PyCharm's.
Only `alive-progress` itself runs in it, with `force_tty`.

**Comment by Chsongcumt** [comment]
> Go into pycharm run configurations. Run > Edit Configurations
> 
> Tick `Emulate terminal in output console`
> 
> If you want it to apply to all python files you create from now, I believe you can also tick it after clicking on `Edit configuration templates`

Great thanks.
