### ISSUE TITLE
tagging releases

### ISSUE THREAD

**Issue by nekopsykose** [rsalmei/alive-progress#236]
you currently publish releases to pypi: https://pypi.org/project/alive-progress/  

these coincide with the version increments in `__init__.py`.

however, it would also be nice to push tags to the repository when that is done, so they show up on github too, and it's possible to get e.g. `3.1.1` directly from the tags, instead of a commit hash.

**Comment by rsalmei** [comment]
Humm yeah, I could, I simply have never needed to find the code of some older version...
Perhaps if I ever needed to fix a bug retroactively? But even then, I'd simply get my CHANGELOG.md and look for the date I published it.
Why would you want such tagging?

**Comment by nekopsykose** [comment]
to be able to get the releases from github via just `https://github.com/rsalmei/alive-progress/archive/refs/tags/$version.tar.gz`, instead of needing to find the commit hash every time.

half of the reason for this is that the `sdist` on pypi does not contain the tests. it is not possible to fetch a versioned tarball from pypi and also run tests on it; a github source tarball is needed instead. but personally i prefer to use github tags regardless

**Comment by nekopsykose** [comment]
(putting tests in the sdist itself would allow for easy change-the-version-only upgrading too when using that source, of course, but it's nice to have symmetry between the repository and releases anyway, allowing someone to just click the tags in the ui here and see what is in what commit, diff two tags for changes, etc)

**Comment by TheTechRobo** [comment]
It would also allow you to use `setuptools_scm` to automatically detect the version from the latest Git tag, rather than having to commit a new version number.

**Comment by sodul** [comment]
Creating a new release tag from the GH UI is trivial. With the use of Actions you could even have the process automatically publish to pypi.org when you are ready to publish (although I do not have any experience with publishing to pypi myself).

**Comment by rsalmei** [comment]
Hey @nekopsykose,
Just a tag (annotated or not) would be OK?
I've just realized that a git tag does not automatically create a github release.

**Comment by nekopsykose** [comment]
yep, that would work great :)

**Comment by rsalmei** [comment]
Done, from now on, every new release will include an automatic annotated tag! 👍

**Comment by nekopsykose** [comment]
thank you very much! greatly appreciated :)

**Comment by rsalmei** [comment]
You're welcome 👍
