### ISSUE TITLE
Comment error

### ISSUE THREAD

**Issue by TyMost** [rsalmei/alive-progress#237]
You used function “bar.title()” to change the title , but probably forgot to update the comment in the next file. This caused me a bit of a hassle.
https://github.com/rsalmei/alive-progress/blob/5d4a62ee81b6ba44ac0afbc33856d68567f3440c/alive_progress/core/progress.py#L39

**Comment by rsalmei** [comment]
You're right, that is very old, from 2020, and has slipped...
Thanks. I'll commit it now as
```python
     ... with alive_bar(123, title='Title') as bar:  # <-- expected total and bar title 
```

**Comment by rsalmei** [comment]
You can always set/change the title like:
- bar.title('title')
- bar.title = 'title'
- with alive_bar(title='title')
👍
