### ISSUE TITLE
Print Enrichment Optional

### ISSUE THREAD

**Issue by reustle** [rsalmei/alive-progress#24]
In the documentation regarding `print()`, I haven't been able to find any way to turn off this "enriching". I would like to print something without including the count on each row. Is this currently supported?

Thank you!

> a print() hook, which allows print statements in the midst of an alive-bar context, nicely cleaning the output of any garbage, and even enriching with the current count when it occurred;

and

> calling the usual Python print('message'), which will print an enriched message that includes the current position of the alive bar, thus leaving behind a log and continuing the bar below it.

**Comment by rsalmei** [comment]
Hello @reustle ,

It's not supported, but shouldn't be too hard to implement.
May I ask why you'd like to turn it off? You don't like it for some reason? Maybe I could improve it instead of removing it...

**Comment by reustle** [comment]
> May I ask why you'd like to turn it off?

Thanks for the reply! One use case I use it for is a script that slowly prints CSV data as it works its way through a dataset. I like to visually monitor this, and have the ability to copy/paste the returned CSV data into other places. Because of this print prefixing, I have to manually scrub the row count at the beginning of each row.

Thanks

**Comment by rsalmei** [comment]
Humm, I see...
I'm gonna implement it for you!

**Comment by reustle** [comment]
Thanks!

**Comment by rsalmei** [comment]
Hey @reustle, I've finished it!
It is implemented in #27, along with a few other things...
I'm going to release it today!

**Comment by rsalmei** [comment]
Released! 😉

**Comment by reustle** [comment]
Thanks so much!

**Comment by rsalmei** [comment]
You're welcome!
