### ISSUE TITLE
Commas in the numbers?

### ISSUE THREAD

**Issue by xevg** [rsalmei/alive-progress#240]
Is there a way to put commas into the number? I tried passing in a formatted string as monitor, but that didn't work.

**Comment by rsalmei** [comment]
I didn't quite get what you're asking.
Please send some code example of what you tried, so I can help you.

**Comment by rsalmei** [comment]
Well, I'm closing this. Please reply if still needed.

**Comment by xevg** [comment]
I apologize, I did not see your original reply. I simply mean I would like the numbers to be 1,234,567 instead of 1234567. When dealing with large number of loops, it’s easier to see where it is with those indicators.

**Comment by rsalmei** [comment]
Hey, no problem.

Humm, now I got it. That's kinda tricky actually, because of internationalization/locale issues.
I can try to find out what Python provides in this regard.

**Comment by rsalmei** [comment]
Oh, have you seen my latest version, which supports SI scaling? In this mode the comma/dot does appear, together with a prefix like k or M. Wouldn't that work for you?

**Comment by xevg** [comment]
It might. Is there any more documentation on the scale and precision? I don't know what SI, IEC, SI2 are.

**Comment by TheTechRobo** [comment]
@xevg I think the prefixes used are here: https://en.wikipedia.org/wiki/Binary_prefix

See the sidebar:

![image](https://github.com/rsalmei/alive-progress/assets/52163910/03bf63d1-9035-4ead-a11c-b80a34b5980c)

**Comment by rsalmei** [comment]
You're welcome.

**Comment by xevg** [comment]
I decided that I still wanted the commas, so I made the changes to the code and made a pull request. :)

**Comment by rsalmei** [comment]
Thanks, but the code was pretty far from what would be needed, andI closed it.
If you really want to contribute, we could think together on the best naming and approach to achieve consistency and performance. Actually, even if such a feature actually makes sense, because one can get this effect pretty easily by simply customizing the widgets (now we know all it takes is a single comma within the format string).
