### ISSUE TITLE
Specifying the `unit` argument displays unit without a space within the bar

### ISSUE THREAD

**Issue by takanuva15** [rsalmei/alive-progress#244]
There seems to be no space before the unit when I customize the unit in the progress bar, so the unit output gets scrunched-up like which looks unpleasant. Am I missing something?
```
with alive_progress.alive_bar(unit="batches") as bar:
    time.sleep(2)
    bar()
```
Output:
`|████████████████████████████████████████| 1batches in 2.1s (0.48batches/s)`
^(note there is no space between the number 1 and the custom unit "batches")

**Comment by rsalmei** [comment]
Yes, I did not support spaces before, but I've just released a new version that does.
Just update `alive-progress` 👍
