### ISSUE TITLE
Example of using alive-progress in tkinter?

### ISSUE THREAD

**Issue by MichaelCurrie** [rsalmei/alive-progress#248]
I see that your competing library can do this.  https://github.com/tqdm/tqdm

[![name](https://i.stack.imgur.com/deptN.png)](https://i.stack.imgur.com/deptN.png)

I'd love to have my favorite Python library alive-progress also be able to do this...

**Comment by rsalmei** [comment]
Thanks, man. But it is not on alive-progress' horizon at all.
I'm not sure how to explain it, but think I do not want to lose the personality of the project. Alive-progress appeal is its aliveness and smoothness, and I want to only provide it where I can guarantee it.
Take jupyter for example. I could implement it only by using the text console interface. There it does work as intended, but what if I tried to implement it graphically like that competing library? For that, I'd have to use other frameworks that provide ready-made progress bars, plain and dull of course, to be able to draw on some window. They do not mind it, that is what they did, but I won't. They want availability, I want experience.
