### ISSUE TITLE
pylint complains that alive_bar contextmanager is not callable

### ISSUE THREAD

**Issue by manvithn** [rsalmei/alive-progress#249]
This might be a pylint issue, but on any code like this
```
    with alive_bar() as progress:
        for ... in ...:
                progress()
```
pylint-2.17.4 will give the message that progress is not callable: [E1102:not-callable](https://pylint.readthedocs.io/en/latest/user_guide/messages/error/not-callable.html). I did see https://github.com/pylint-dev/pylint/issues/1746 which was closed a while ago, or it might be that we need some type hint in alive_bar.

**Comment by rsalmei** [comment]
Closing this one, but feel free to reply if there's any news.
