### ISSUE TITLE
Customize the 'on x:' prefix message from print statements (header?)

### ISSUE THREAD

**Issue by L0Lock** [rsalmei/alive-progress#251]
Scenario: I'm using alive-progress to make a somewhat user-friendly file processer. Right now the output looks like this:

![image](https://github.com/rsalmei/alive-progress/assets/16049822/c52a3fe7-00e3-4779-be02-38e66a278cb9)

It looks cool for the progress bar and the file-printing part. BUT, i'd love to be able to change the print statements prefix added by alive-progress:

I.E. in my case if i was able to do something like `bar.header = (f"File {(:d+1):03} :    ")` 

It's only some small quality of life of course, nothing showstopper x)

**Comment by rsalmei** [comment]
I could do something like that, but on your case, you could just torn off this enrichment and do your own.
Just set `enrich_print=False` and you're good to go, no "on X: " headers will be printed, and you can insert your own.
Wouldn't that work better for you?
