### ISSUE TITLE
Does this library support using many spinners and/or bars simultaneously?

### ISSUE THREAD

**Issue by abrahammurciano** [rsalmei/alive-progress#252]
My app is tracking several different tasks that are happening simultaneously, and I'd like to have a different progress bar/spinner for each task, stacked one above the other, all running simultaneously. I couldn't find any examples of this in the docs. Is this supported? If so, can someone please point me in the right direction?

**Comment by rsalmei** [comment]
No, it is not supported yet. I want to support it eventually, but it is very complex.
See #20, it is a long-requested feature.

You could collect the updates of the tasks, and present them in a single alive-progress bar in the main thread.
You can search for other issues here about ThreadPoolExecutor and Multiprocessing.
