### ISSUE TITLE
bar.current() fails with TypeError: 'int' object is not callable

### ISSUE THREAD

**Issue by jspilinek** [rsalmei/alive-progress#253]
My script is parsing through log files. Script worked fine on my old machine with alive-progress 2.4.1. My new machine is using alive-progress 3.1.4

**TotalFileSize** is the total bytes of all files to be parsed.

My 2.4.1 alive_bar:
`with alive_bar(TotalFileSize, title=f'Processing {TotalMB} MB',monitor='[{percent:.0%}] {count}/{total} Bytes') as bar:`

I see in 3.0 there was support added for units. My new alive_bar:

`with alive_bar(TotalFileSize, title=f'Processing Files', unit='B', scale='SI', precision=1) as bar:`

My code loops throught the files, reading one line at a time. For each line processed I calculate the line size and update the bar:

`bar(sys.getsizeof(line)-sys.getsizeof('\n'))`

I never quite reach 100%. Must be math is slightly off. After processing all files I bump the bar to 100% with:
`bar(TotalFileSize-bar.current())`

This worked in alive-progress 2.4.1, but no longer works in 3.1.4. 

bar.current() fails with error:
**TypeError: 'int' object is not callable**

**Comment by TheTechRobo** [comment]
Have you tried just `bar.current` (without the brackets)?

**Comment by jspilinek** [comment]
`bar.current` works. Thanks!

README.md should be updated as it references `bar.current()` twice

**Comment by rsalmei** [comment]
Thanks @TheTechRobo.

Yep, the readme is not up-to-date. I'm going to fix it, thanks @jspilinek.

I just wanted to let you know that the auto-suggestions of ipython do show `current` is not a method:
<img width="657" alt="image" src="https://github.com/rsalmei/alive-progress/assets/6652853/d6c55578-3efb-4797-b65d-e92d74ec85a4">
