### ISSUE TITLE
Override time, item/second and ETA time

### ISSUE THREAD

**Issue by Xferno2** [rsalmei/alive-progress#256]
Hello,

I'm using the progress bar in a while loop, it works great using bar skipped and i just have to keep the count of the items that I have already processed. After each iteration I just clear the console to see the bar always on top.

My question is if it's possible to implement a override for time that was elapsed since start to be able to copy the time from the last loop iteration and put it in to the next iteration? Same goes for the eta, if it's possible to adjust the eta based on the last loop time and last loop items/second?

**Comment by rsalmei** [comment]
Hi,

I'm not sure what you're asking here, could you try to explain it better?

**Comment by rsalmei** [comment]
I'm closing this one, but feel free to reply if you still want something here.
