### ISSUE TITLE
Usage with loguru

### ISSUE THREAD

**Issue by nzqo** [rsalmei/alive-progress#257]
Hi!

I really like alive-progress, but I can't seem to get it to work with loguru without breaking formatting. Is there a method to hook similar to what is already done for the standard logging module, but maybe enable that for third-party logging libraries as well?

Just as a showcase of how logging output is broken when done concurrently to using a bar:

```log
|██████████████████████▌                 | ▄▂▂ 282/500 [56%] in 2s (~1s, 150.4/s) 2023-11-08 09:47:14.490 | DEBUG    | __main__:<module>:10 - Happy logging 282
2023-11-08 09:47:14.497 | DEBUG    | __main__:<module>:10 - Happy logging 283
2023-11-08 09:47:14.503 | DEBUG    | __main__:<module>:10 - Happy logging 284
2023-11-08 09:47:14.509 | DEBUG    | __main__:<module>:10 - Happy logging 285
2023-11-08 09:47:14.516 | DEBUG    | __main__:<module>:10 - Happy logging 286
2023-11-08 09:47:14.523 | DEBUG    | __main__:<module>:10 - Happy logging 287
2023-11-08 09:47:14.530 | DEBUG    | __main__:<module>:10 - Happy logging 288
2023-11-08 09:47:14.536 | DEBUG    | __main__:<module>:10 - Happy logging 289
|███████████████████████▎                | ▃▁▃ 290/500 [58%] in 2s (~1s, 150.4/s) 2023-11-08 09:47:14.543 | DEBUG    | __main__:<module>:10 - Happy logging 290
```

**Comment by rsalmei** [comment]
Hi @nzqo,

Please, give me some test code so I can run it here.

**Comment by nzqo** [comment]
Sure, here you go:

```python
from loguru import logger
from alive_progress import alive_bar
import time

with alive_bar(500) as bar:
   for i in range(500):
       time.sleep(.005)
       logger.debug("uh oh")
       bar()
```

**Comment by rsalmei** [comment]
Okay, I got it.
It seems `loguru` does things very weirdly: it 1. initializes `logger` on import time, 2. captures the real `stdout` within it, and 3. it does not use `logging.getLogger()`!!
This means `alive-progress`, when it gets to initialize the print and logging hooks, cannot find `loguru`'s logging handler since it is not registered in Python's logging...

Look what happens if I import it only within `alive-progress`'s context manager (it works!):

https://github.com/rsalmei/alive-progress/assets/6652853/b8cb88dc-ee5f-4780-952d-1a99e8eaba9b

I'm not sure yet how to proceed, gonna think about it.

**Comment by rsalmei** [comment]
After some research, it seems I can't do anything to properly support it. According to https://github.com/Delgan/loguru/issues/376, the maintainers do not want to expose the internal handlers, so I can't fetch and instrument them...

What you have to do in case you can't avoid importing loguru's logger at the top, is to reinitialize it by removing previous handlers and reinserting them (the default one plus any others you're using). When the `alive-progress`' context finishes, you have to reinitialize loguru's handlers again.
This works:

https://github.com/rsalmei/alive-progress/assets/6652853/bb2f321e-2136-4432-86f4-bafc8f9f7ab2

**Comment by rsalmei** [comment]
I've just realized that, in the first video, all indexes were outputted as `500` 😂 
It did work, I assure you. But when we try it the second time onward it doesn't, loguru maintains cached the instrumented stderr from the first `alive_bar`!!
So, even in that case, you would have to reinitialize handlers, exactly as the above...

<img width="802" alt="image" src="https://github.com/rsalmei/alive-progress/assets/6652853/b518a809-ce6e-4faf-b6f2-f160d308b054">

**Comment by rsalmei** [comment]
So, here is the code to reinitialize loguru's handlers:
```python
def reinitialize_loguru():
    logger.remove()
    logger.add(sys.stderr)
```

Then just call it within and after `alive_bar`'s context manager:
```python
with alive_bar(500) as bar:
    reinitialize_loguru()
    for i in range(500)
        ...

reinitialize_loguru()
```

I'm afraid it's the best we can do.

I'm closing this one, but feel free to continue if you want.

**Comment by nzqo** [comment]
> So, here is the code to reinitialize loguru's handlers:
> 
> ```python
> def reinitialize_loguru():
>     logger.remove()
>     logger.add(sys.stderr)
> ```
> 
> Then just call it within and after `alive_bar`'s context manager:
> 
> ```python
> with alive_bar(500) as bar:
>     reinitialize_loguru()
>     for i in range(500)
>         ...
> 
> reinitialize_loguru()
> ```
> 
> I'm afraid it's the best we can do.
> 
> I'm closing this one, but feel free to continue if you want.

thanks for looking into this, a pity there wasnt a simple way to do this 😢 
Reinitializing could have unwanted side effects (in the case of developing a library, this would also remove the user-added handlers), I'm not sure I can use that. There seems to be some guidance on using [loguru with tqdm](https://github.com/Delgan/loguru/issues/135), but no idea if there is something fundamentally different at play there

**Comment by rsalmei** [comment]
You're welcome!

tqdm does not generate and install logging hooks like `alive-progress` do, and even using an internal `tqdm.write()` func they got similar problems.
It seems they had to remove all handlers, add another one writing into that internal func, and certainly reinitialize everything after the bar is gone, exactly like I did here.

Unfortunately, there's nothing I can do, it's the poor loguru's API fault.
