### ISSUE TITLE
Package manager migration from  `setuptools` to `poetry`

### ISSUE THREAD

**Issue by brunolnetto** [rsalmei/alive-progress#259]
Hi,

As an old-school guy, you are comfortable with setuptools, wheels and tox. My suggestion is to migrate current package managing to `poetry`. Although not as popular as yours,  my library [`eule`](https://github.com/trouchet/eule) uses poetry as a package manager. I'd like to invite you to suggest improvements to my library as well. 

Thanks for  your response

**Comment by TheTechRobo** [comment]
Do you mean a `pyproject.toml`?

**Comment by brunolnetto** [comment]
Correct.

**Comment by rsalmei** [comment]
Hi @brunolnetto,

Thank you but I don't think poetry is useful, I think it is very cumbersome actually, and I don't like it. Setuptools works very nicely and is well-supported on every system and platform.

PS.: I don't use `tox`, I use `nox` which is much more modern 😜

**Comment by brunolnetto** [comment]
Ok. Computer science is very cardinal. I like poetry, though. It is clear, but I will avoid making the argument, I am tired of suggesting things.
