### ISSUE TITLE
Is it possible to update the progress bar by 0.5

### ISSUE THREAD

**Issue by Ravencentric** [rsalmei/alive-progress#260]
Something like this, where the count is definite. Each pass takes a while so instead of waiting for both passes to complete, update the progress bar after each pass
```py
from pathlib import Path

from alive_progress import alive_bar

files = list(Path.cwd().glob("*.txt"))
# Returns something like: ["/cwd/01.txt", "/cwd/02.txt", "/cwd/03.txt", "/cwd/04.txt", "/cwd/05.txt"]

with alive_bar(total=len(files)) as bar:
    for file in files:
        do_first_pass(file)
        bar(0.5)
        do_second_pass(file)
        bar(0.5)

**Comment by Ravencentric** [comment]
Currently, `bar(0.5)` gets treated the same way as `bar()` and it ends up overflowing

**Comment by rsalmei** [comment]
No, it isn't possible, I have to keep steps as integers internally or I'd run into floating-point rounding errors.

What you can do is declare the total as twice the number of files, and then you can call `bar()` twice within the loop as well. Doesn't that work for you?

**Comment by Ravencentric** [comment]
That sort of works, but gives the end user wrong info about how much files we are working on

**Comment by TheTechRobo** [comment]
It'd be slow, but the `decimal` module is always an option to avoid rounding errors.

**Comment by rsalmei** [comment]
> That sort of works, but gives the end user wrong info about how much files we are working on

In that case, you should really pass the real total, and just call bar once per iteration.

For the passes information, you could easily set a text message beside the bar. I think that would be the most appropriate. Call `bar.text('First pass')`, then with 'Second pass', and then finally `bar()` at the end of the loop.
WDYT?

**Comment by rsalmei** [comment]
> It'd be slow, but the `decimal` module in stdlib (https://docs.python.org/3/library/decimal.html) is always an option to avoid rounding errors.

Thanks, I'm aware, but this touches hot code, calculated at each refresh, so it isn't an option.

**Comment by rsalmei** [comment]
So, @Ravencentric, what do you think?
The most appropriate for you would be:
```python
with alive_bar(total=len(files)) as bar:
    for file in files:
        bar.text('First pass')
        do_first_pass(file)
        bar.text('Second pass')
        do_second_pass(file)
        bar()
```
I'm closing this one, but feel free to continue if you need anything more.

**Comment by Ravencentric** [comment]
The `bar.text()` solution after each pass does seem to be the best solution, so this can be closed as completed. Thank you.
