### ISSUE TITLE
Ubuntu package

### ISSUE THREAD

**Issue by thekswenson** [rsalmei/alive-progress#265]
I would love to use your progressbar, but it's currently much easier to use something like progressbar2 simply because there is an Ubuntu package to install it system-wide.  No need for an env.

**Comment by rsalmei** [comment]
What do you mean by no need for an "env", a virtual env?
AFAIK there isn't any need to install it in a venv, you should be able to install it system-wide.

Also, what does this "Ubuntu package" do differently?

**Comment by thekswenson** [comment]
Yes, sorry about the laziness, I meant a virtual env.
This is the message that I get, whether using sudo or not, when I try to install via pip on my Ubuntu 23.10 system:

```
=> pip3 install alive-progress
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

```

**Comment by TheTechRobo** [comment]
You can use --break-system-packages, but that will of course potentially lead to conflicts.

**Comment by rsalmei** [comment]
No problem, don't worry.

> You can use --break-system-packages

Yep, that's what I was going to say. It won't cause any problems, `alive-progress` is a small package with very few dependencies, totally contained, and impossible to cause any conflicts.
Just `pip3 install alive-progress --break-system-packages` and you should be good.

I'm going to close this, but please let me know whether `alive-progress` works in any venv after this or not.
