### ISSUE TITLE
Usage with np.arange()

### ISSUE THREAD

**Issue by zooplibob** [rsalmei/alive-progress#266]
I have some code doing a sweep using np.arrange:

for variable in np.arange(10, 20, 0.1):
   ...

I can use manual mode can calculate the percentage, but how can I have it display the actual value of variable next to the bar (rather than just percent)?

**Comment by TheTechRobo** [comment]
Check out the [Displaying messages](https://github.com/rsalmei/alive-progress?tab=readme-ov-file#displaying-messages) section of the README - `bar.text` might be what you're looking for

**Comment by rsalmei** [comment]
You have two ways. One is like you and @TheTechRobo have said: use manual mode to directly calculate the percentage, and `bar.text` to display it on the bar.
Another is to just use the variable range as the total, which would automatically calculate the percentage for you. You could also show it the same way.

range = (20 - 10) / .1 = 100 steps
