### ISSUE TITLE
The show_bars() demo has scrolling text at the top, how do I do that?

### ISSUE THREAD

**Issue by 3cha1n** [rsalmei/alive-progress#267]
I can't see in the documentation how to achieve the scrolling text like we see when running the show_bars() demo. Is this scrolling text facility part of alive-progress?

**Comment by rsalmei** [comment]
Yes, it is! It is one of the animation effects I've made into `alive-progress`.
There are some details in the documentation [here](https://github.com/rsalmei/alive-progress?tab=readme-ov-file#create-your-own-animations).
Note the images with scrolling emojis, it works the same with text.

In a nutshell, you can just call:
```python
    wait = scrolling_spinner_factory('please wait...')
```
and then use it directly as the spinner.

For the complete function help, just call it with a `?`:
<img width="1097" alt="image" src="https://github.com/rsalmei/alive-progress/assets/6652853/bd294c20-13f3-4d46-a730-45f97571e77c">

And finally, don't forget to try it with the `.check()` tool!
It's one of the parts I'm most proud of in this project.
