### ISSUE TITLE
Jupyter environment

### ISSUE THREAD

**Issue by brunolnetto** [rsalmei/alive-progress#270]
How to make this great tool work on jupyter notebook cells?

**Comment by rsalmei** [comment]
It should work already. Is it not working for you?

**Comment by brunolnetto** [comment]
I tried to apply on a future.concurrent application without much of a success. Is the library suitable for such cases?

**Comment by TheTechRobo** [comment]
Try adding `force_tty=True` to the `alive_bar()` function call: https://github.com/rsalmei/alive-progress?tab=readme-ov-file#forcing-animations-on-pycharm-jupyter-etc
