### ISSUE TITLE
Option for redirected print header to start at 1

### ISSUE THREAD

**Issue by m-haring** [rsalmei/alive-progress#277]
Could there be an option for the header of the redirected print output to start at 1, if there is a countable amount of items? 

e.g.
on 1: Message
Progress bar

instead of 
on 0: Message
Progress bar

**Comment by rsalmei** [comment]
Yes, that does make sense. Perhaps an offset parameter for the enriched output would actually be nice.
Thanks, this will go into the TODO list.

**Comment by rsalmei** [comment]
Hi @m-haring,
I'm finally releasing this, thanks for your patience.
