### ISSUE TITLE
Rounded ETAs for long tasks

### ISSUE THREAD

**Issue by magiraud** [rsalmei/alive-progress#278]
alive-progress is a fantastic tool, thank you!

On a long task, my bar display something like `101/456 [22%] in 26:09 (~1:32:15, 0.1/s)`

The current ETA provides a estimate with updates down to the second (1:32:15) and... this is constantly changing. This level of precision seems unnecessary and may draw undue attention to what is not really meaningful. A more rounded ETA could be more "stable" (here 1:32:00) and less distracting, as for example:
-  Round ETAs between 1 minute and 1 hour to the nearest 10 seconds.
-  Round ETAs above 1 hours to the nearest minute.

This would offer a more user-friendly and less intrusive display of time estimates.

**Comment by rsalmei** [comment]
> alive-progress is a fantastic tool, thank you!

Thanks, man!

Yeah, I see... That is actually a great suggestion!
I have been thinking about a similar request: https://github.com/rsalmei/alive-progress/issues/247, but I'm kind of stuck there. I know I do need to improve the ETA for long-running tasks.
I'll think about it.

**Comment by rsalmei** [comment]
Hi @magiraud,
 I'm finally releasing this, thanks for your patience.

**Comment by magiraud** [comment]
Excellent, thank you @rsalmei! So it was 21b88abd47d.

**Comment by rsalmei** [comment]
Yep, not that simple, but I liked the effect.
You're welcome!
