### ISSUE TITLE
"on X:" output on every line

### ISSUE THREAD

**Issue by DemonPandaz2763** [rsalmei/alive-progress#281]
"on X:" is being printed on every line while using "alive_bar(total)". Commenting this out (not using the bar anymore) fixes the problem.

with bar:
```
    bar = alive_bar(total_reqs, title="Name", spinner="dots")
    
    with ThreadPoolExecutor(max_workers=number_threads) as exe:
        future_to_url = {
            exe.submit(worker, session, base_url + word, parsed_codes, killer, output_queue): word for word in extended_wordlist
        }
        for future in as_completed(future_to_url):
            if killer.kill_now:
                exe.shutdown(wait=False, cancel_futures=True)
                break

            completed_reqs += 1
            bar()
```
![image](https://github.com/user-attachments/assets/393d141c-4b69-4eff-9ce9-33a933e1c336)

without bar:
```
    #bar = alive_bar(total_reqs, title="Name", spinner="dots")
    
    with ThreadPoolExecutor(max_workers=number_threads) as exe:
        future_to_url = {
            exe.submit(worker, session, base_url + word, parsed_codes, killer, output_queue): word for word in extended_wordlist
        }
        for future in as_completed(future_to_url):
            if killer.kill_now:
                exe.shutdown(wait=False, cancel_futures=True)
                break

            completed_reqs += 1
            #bar()
```
![image](https://github.com/user-attachments/assets/57cceae6-6318-4b62-947f-9ed8a035b754)

**Comment by TheTechRobo** [comment]
Set `enrich_print=False`.

**Comment by DemonPandaz2763** [comment]
Thank you, that worked. :D

**Comment by TheTechRobo** [comment]
For future reference, all of the configuration options are listed in the [Configuration](https://github.com/rsalmei/alive-progress?tab=readme-ov-file#configuration) section of the README.

**Comment by rsalmei** [comment]
Yep, that's a feature, not a problem.
It informs you where the bar was when the print happened.
Thanks @TheTechRobo 👍

**Comment by DemonPandaz2763** [comment]
> Glad to hear it!
> 
> For future reference, all of the configuration options are listed in the [Configuration](https://github.com/rsalmei/alive-progress?tab=readme-ov-file#configuration) section of the README.

Yeah, I didn't realize it was a part of logging.
