### ISSUE TITLE
using alive_bar without `with`

### ISSUE THREAD

**Issue by jonturneratduke** [rsalmei/alive-progress#3]
I spent some time with your progress bar today, making it work with MS Azure's blob storage. Perhaps others would find this useful?

I'm using alive_bar to display progress moving files to/from Azure blob storage. Azure has a callback which updates me on the progress of the upload (which could take minutes, to hours to complete). This callback needs to talk to your library from a different application context, so a `with/as` block won't work for me. 

The canonical usage, with/as: 
```
     with alive_bar(20) as bar:
         for i in range(20):
             bar("working")
             time.sleep(0.05)
```
translates into the equivalent:
```
 bar=alive_bar(20)
 updateMehod = bar.__enter__()  # start display thread
 for i in range(20):
     updateMehod.__call__("working")
     time.sleep(0.05)
 bar.__exit__(None, None, None)
```

So in the context of a callback, the following will work:
1. Calling Azure's threaded fire-and-forget upload method with the callback method:
```
                result = self.block_blob_service.get_blob_to_path(
                    container_name,
                    blobname,
                    filename,
                    progress_callback=AzureProgressCallback(filename),
                    max_connections=4,
                )
```
2. the callback handler in its own class
```
class AzureProgressCallback(object):
    def __init__(self, filename):
        self._filename = filename
        self._lock = threading.Lock()
        # for progressbar (pb)
        self._pb = None
        self._pbupdate = None

    def __call__(self, current, total):
        """update the progress bar"""
        with self._lock:
            if self._pb is None:
                self._pb = alive_bar(100)  # max 100%
                self._pbupdate = self._pb.__enter__()  # start display thread
                # progress bar is now running (until we call __exit__ on it)
            self._pbupdate(formattedprogress)

    def __del__(self):
        with self._lock:
            # dispose of the progressbar
            self._pb.__exit__(None, None, None)
```
hope this is useful.

**Comment by rsalmei** [comment]
That's very nice @jonturneratduke 👏

**Comment by rsalmei** [comment]
In this case, I'm thinking if this "context-less" use should be supported out of the box, or if this whole "Azure blob storage callback" could be in a `contrib` like package.

**Comment by rogerio-geru** [comment]
Does this `AzureProgressCallback` of yours improved with the new manual mode? I think you do not need to mimic the `100%` anymore...

**Comment by jonturneratduke** [comment]
yes, it works perfectly now with the callbacks, which are non-periodic/irregular  -- unpredictable both in time and volume of work accomplished since the last call. The progress bar just jumps up to the next percentage and your code recalculates the ETA perfectly. manual mode greatly simplifies the logic on my side. 👍

**Comment by rsalmei** [comment]
That's great, I'm glad you liked it... 😉
