### ISSUE TITLE
method to set progress to a percentage

### ISSUE THREAD

**Issue by jonturneratduke** [rsalmei/alive-progress#4]
It would be very useful to be able to set the progress of the bar to some percentage, rather than needing to call the update method (`alive_bar()`) X number of times which is based on the initialization value. Similarly, if the update method is not called the same # of times, when the progressbar is released, it indicates a warning. This causes difficulty for instances where the progress duration may not be known beforehand (such as uploading a large file), and callbacks are inconsistent.
What if we could pass in a float (percentage completion)?
```bar(50.25)``` or even ``` bar(100.00)``` Rather than display a progress message, it would set the bar to that % completion. Alternatively, a way to declare "successful completion" which would set the bar to 100% without error/warning indicators would be helpful.

**Comment by rsalmei** [comment]
Hello @jonturneratduke!
Yeah, I can do that, shouldn't be a problem to set a percentage, since internally I calculate one.

Only the bar() call gets the first positional argument as the message text. So I could do one of:

1. add a keyword argument to the bar() call;
2. add a sub-method to bar, like `bar.set(50.25)` for this use-case.

I'm tending to the second one, what do you think?

**Comment by rsalmei** [comment]
Actually, it's not that easy.
I also display in the alive-bar the observed throughput, it does not make much sense to know it's processing 18% per second. What does this represent? I need to know how much actual elements or transactions or bytes are being processed per second.

If the `total` is adequately declared, I could calculate that actual number too, but the two modes could not be mixed, which would need validations and so a little overhead.

**Comment by jonturneratduke** [comment]
Understood.
I don't want to break (or clutter) your usage model -- you have a nice clean (and refreshingly simple!) interface for _a priori_ well-bounded tasks, and I have a what may be an edge case.

**Comment by rsalmei** [comment]
Hey @jonturneratduke 
I'm still thinking about how to implement this, let's keep it open for a while.
I think, regardless of the overhead, it might be a good addition of functionality.

**Comment by rsalmei** [comment]
Hello again @jonturneratduke, great news!
I've finally found a solution for this, after studying it for this whole week!

I had to refactor almost all of the main code! 😅 
But I think I came up with a very neat implementation, it is almost ready in #6.

I only need to write the instructions in readme, bump version and release it!

**Comment by jonturneratduke** [comment]
That's great! Sorry for the extra work I've created for you, but it's exciting to hear you've found a solution. Looking forward to what you've cooked up. :)

**Comment by rsalmei** [comment]
No problem at all, you're welcome.
It's released! Version 1.1.0

Please give a look at the new readme and try it, let me know what you think!

**Comment by jonturneratduke** [comment]
Nicely done! There's a little bit of weirdness in calculating progress %, but overally that's exactly what I was hoping for.`    with alive_bar(100, manual=True) as bar:   # 100% = finished
        total = 0
        done = False
        while not done:
            total += 1
            time.sleep(0.02)
            if total > 100:
                total = 100
                done = True
            bar(total)
        return
`

**Comment by rogerio-geru** [comment]
Thank you @jonturneratduke ! Glad you liked!

Actually, you do not need to simulate the percentage, I already did it internally!
Did you happen to read the new readme? It's in https://github.com/rsalmei/alive-progress#alive-bar-modes, if not I invite you to take a look :wink: 
Please, try without declaring the `total`, I'm gonna calculate for you both the throughput and the ETA!
Let me know the result :+1:

**Comment by jonturneratduke** [comment]
Yes, it works perfectly if I just read & follow the instructions. 😃
ETA and throughput are super! Some of our processes may take 5 minutes or more so that really helps set user expectations. Plus, no more crashes if I try to print() while the status bar is active.
I suspect there was a lot of work internally to make all this possible, but you've implemented it in a really tidy way that hides all that complexity.
