### ISSUE TITLE
Spinner Only?

### ISSUE THREAD

**Issue by engineerjoe440** [rsalmei/alive-progress#40]
I might have overlooked something, but is it possible to only have a spinner without a progress bar? I dug around in the source a little bit, but I couldn't find exactly what I was looking for.

If this isn't an option, is it a possible addition?

Best I could figure out was minimizing the progress bar like the following. Works, but not the best.

```python
from alive_progress import alive_bar

with alive_bar(1,length=3,spinner='classic') as progress_bar:
        # do something...
        progress_bar()
```

**Comment by rsalmei** [comment]
Hello @engineerjoe440,

I don't think I really understand, you would like to use a progress bar without a progress bar? 🤔 
I might be able to help you, but what are you actually trying to achieve?

**Comment by engineerjoe440** [comment]
Hi @rsalmei,

Yeah, I thought it could be useful for situations where a process was being "spun up" outside of the visibility of the Python script. In other words, imagine a case where a Python script is activating something in a subprocess or other means that cannot otherwise provide feedback to the main script about how far along in its process it is.

I thought that if there were a simple way to expose the spinners on their own, (independently of the progress bar) that could be quite useful. So I'm not really thinking a "progress bar" more so a function that exposes the spinners on their own.

Does that make any more sense?

Thanks!!!

**Comment by rsalmei** [comment]
Hey man, I think it does! 👍 

That's really not possible at this moment, but actually I am implementing a new feature in the future v2 that might help you.
I'm creating the concept of "precalculation", don't really know how to say that. It is a new mode where the bar will enter unknown (so two nice spinners will be running), to allow one to calculate the very total to be used in the bar. Then, when your subprocess has finished, you can restart the bar with the total, and it works as usual. The key is that it will allow a user feedback with the elapsed time in those precalculate times...

Would that work for you? It would be basically two spinners instead of one like you asked, with the addition of an elapsed time counter! 
If it does, it is already in the work, but it is trickier than I thought, gonna take some time.

You're welcome man!

**Comment by engineerjoe440** [comment]
Hey @rsalmei,

I think that sounds awesome!!! Take your time, I'll be excited to see it when you're ready. I think I'll probably have to see it to confirm that it's exactly what I'm imagining, but if it is, it'll be awesome!

Thanks again! Stay safe and healthy!

**Comment by rsalmei** [comment]
Hey @engineerjoe440, how are you?

I think I have it! It is working nicely, have a look:
![quantifying mode](https://user-images.githubusercontent.com/6652853/85098199-4f4d4780-b1d0-11ea-94fa-44ba475c7dae.gif)

Would that work for what you need?

**Comment by engineerjoe440** [comment]
@rsalmei Sorry for the delayed response.... Super busy lately. I think that's awesome!!! Basically, it will allow some kind of "quantifying" state where the time is indeterminate, and then the bar will be set up to finish the loading and indicate a percentage.

**BEAUTIFUL!!!**

I think that is great!!!!

**Comment by rsalmei** [comment]
Great, thank you!
I'll let you know when it is released!

**Comment by rsalmei** [comment]
Hey @engineerjoe440, how are you man!

I'm polishing now the 2.0 in #51, should not take long, but I'll have to keep you hanging for a little more.
This quantifying mode did not make it yet, it was getting way too big an update...

But it will in the next one, the 2.1!

Just wanted to let you know that!
Stay safe and healthy in there too!

**Comment by engineerjoe440** [comment]
Thanks again @rsalmei !!! This is an awesome project!

**Comment by rsalmei** [comment]
Hey @engineerjoe440, how are you man?

I'm sorry it is taking so long, super busy lately (learning Rust!).
I'd like to tell you, even if your request would be nicely fulfilled by the future "Quantifying Mode" feature (in version 2.1), I now did implement support for disabling the spinner, as well as the bar or even both!! 😄
So I can deliver what you've asked right in the next 2.0!! 🎉 

I'm going to close this one then, but feel free to contact me anytime!

**Comment by engineerjoe440** [comment]
Oh man!!! That sounds terrific!!!! Thank you!!!

I'm really excited to see it! But I totally get running out of time! I've been super busy too, so no worries! But this is still such an awesome project! Way to go!!!

**Comment by rsalmei** [comment]
Hey man! I don't know if you had the chance to see it, but there's even more news in this regard!
I've even cited your name there, did github notified you?
https://github.com/rsalmei/alive-progress/issues/72
Anyway, look how cool it is! 👍

**Comment by engineerjoe440** [comment]
Yeah!!!! I saw the GitHub notification... I just hadn't wandered over though to look ;)
