### ISSUE TITLE
OSError: [WinError 6] The handle is invalid with pytest or tox

### ISSUE THREAD

**Issue by eugenkleinschmidt** [rsalmei/alive-progress#41]
When running in pytest or tox got this error

```
def alive_repr(spin=''):
        update_data()

        line = '{} {}{}{} in {} {} {}'.format(
            bar_repr(run.percent, end), spin, spin and ' ' or '',
            monitor(), to_elapsed(), run.stats(), run.text or title or ''
        )

        line_len = len(line)
        with print_lock:
            if line_len < run.last_line_len:
                clear_traces()
>           sys.__stdout__.write(line + (spin and '\r' or '\n'))
E           OSError: [WinError 6] Das Handle ist ungültig
```

but progress bar is done
![image](https://user-images.githubusercontent.com/10838796/82829872-9b98b680-9eb4-11ea-9924-a759413a4b98.png)

here with tox:
![image](https://user-images.githubusercontent.com/10838796/82830142-385b5400-9eb5-11ea-85b2-54ac5e799945.png)

test code:

```
from alive_progress import alive_bar


def test_progress():
    items = range(1000)                  # retrieve your set of items
    with alive_bar(len(items)) as bar:   # declare your expected total
        for item in items:               # iterate as usual
            # process each item
            bar()                        # call after consuming one item


if __name__ == "__main__":
    test_progress()

```

tox
```
[tox]
skip_missing_interpreters = True
ignore_basepython_conflict = true
envlist =
    py{36, 37, 38},

[testenv]
setenv =
    PYTHONUNBUFFERED=yes
skip_install = true
deps =
    pytest
    alive-progress
commands =
    pytest {posargs}
```

calling it directly make no problems

**Comment by rsalmei** [comment]
Hello @eugenkleinschmidt,

I've searched several possibilities and could not find even a clue.
Please post your exact code, and the exact line you are calling in the shell, including the output of `pip list`.
Let's first try to determine if it is a Windows specific thing, by trying to simulate it here (MacOS).

**Comment by eugenkleinschmidt** [comment]
argh.... only win makes problems 
https://github.com/eugenkleinschmidt/test_alive_progress/runs/713785231?check_suite_focus=true

I tested it also with PyCharms Pytest. Here I have no problem
![grafik](https://user-images.githubusercontent.com/10838796/83046258-0ed23200-a047-11ea-8dbf-0383bb058e80.png)

**Comment by rsalmei** [comment]
Yeah man, unfortunately it is...

Well, I've found this answer that could help: https://stackoverflow.com/a/27093194

Also this readme explains a lot: https://github.com/Drekin/win-unicode-console
See:
*The standard stream objects (sys.stdin, sys.stdout, sys.stderr) are not capable of reading **and displaying** Unicode characters in Windows console.*

Anyway, do you really need windows support? Actually I've just realized it didn't work on it, as no one had ever complained about it, so it will be pretty low on my priority...

**Comment by rsalmei** [comment]
Hey @eugenkleinschmidt, how are you?

Are you still using `alive-progress` in Windows?
Please report what happens, and please test it with:
```python
    with alive_bar(len(items), theme='ascii') as bar:
```
That way I can know if it really is some fancy character, or something deeper.

**Comment by rsalmei** [comment]
Hey, I just found out that Windows Terminal does support Unicode. give it a try!

I've installed Python on a Windows machine, and ended up stuck with another bug: #50 
I'll close this one for now, feel free to reopen if you have any more information.
