### ISSUE TITLE
ThreadExecutor()

### ISSUE THREAD

**Issue by jamesb93** [rsalmei/alive-progress#42]
Is there a way to have a bar work inside a ThreadExecutor context?

```
    with alive_bar(len(workables)) as bar:
        with ThreadPoolExecutor() as pool:
            for work in workables:
                pool.submit(process, work)
                bar()
```
This kind of interface would be really useful for measuring progress on threaded jobs.

**Comment by rsalmei** [comment]
Hello @jamesb93!

It's a good question, but I think you can do it without too much hassle. The `alive_bar` can monitor anything that is countable, so jobs on a pool of any kind should be fine.

Your example code would actually monitor just the submitting to a pool, not their completion. To measure the progress of completed jobs, you can leverage the futures api [`as_completed`](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.as_completed) like this:

```python
from concurrent.futures import ThreadPoolExecutor, as_completed
from alive_progress import alive_bar
import time

def process(work):
     time.sleep(1)

workables = [x for x in range(10)]

with alive_bar(len(workables)) as bar:
     with ThreadPoolExecutor(max_workers=2) as pool:
         futures = [pool.submit(process, work) for work in workables]
         for result in as_completed(futures):
             bar()
```

You would nicely see the alive_bar progress go up two by two, until all jobs are completed!
See for yourself, the above code is complete, and should run as is. 👍

**Comment by jamesb93** [comment]
This such a great answer! Very helpful. Thank you. I'll give it a shot with my code to make it work.

**Comment by rsalmei** [comment]
You're welcome! Glad to help.

**Comment by jamesb93** [comment]
Just wanted to confirm your code slotted in without any difficult modifications, and I learned something about concurrent.futures :)

**Comment by rsalmei** [comment]
Great, that's nice to hear! 😉
