### ISSUE TITLE
Usage without a context manager

### ISSUE THREAD

**Issue by pzelnip** [rsalmei/alive-progress#44]
I'd like to use this progress bar with a framework, but that framework provides a mechanism for updating a progress indicator that the framework calls.  Ie it's kinda like:

```
class MyProgressIndicator(BaseClassFromFramework):
    def update(self, current_count, total):
        # update the progress bar here
```

The idea is that I register `MyProgressIndicator` with the framework, and it instantiates `MyProgressIndicator` for me, and calls `update()` each time it processes an item.  Ideally I'd like to use alive-progress here, but the problem is that there's no place in the way this framework works for registering a context manager.  Ideally, what I'd like to do is something like:

```
class MyProgressIndicator(BaseClassFromFramework):
    def __init__(self, total_to_process):
        self.alive_bar = alive_bar(total_to_process)

    def update(self, current_count, total):
        self.alive_bar()   # update the progress bar 
```

Is there some way to achieve that?

**Comment by rsalmei** [comment]
Hello @pzelnip, you sure can!

You need to deconstruct the context manager, and make it work imperatively.
Please experiment with something like that:

```python
class MyProgressIndicator(BaseClassFromFramework):
    def __init__(self, total_to_process):
        self.alive_bar_instance = alive_bar(total_to_process, manual=True)
        # let's start the bar, entering the context manager:
        self.bar = self.alive_bar_instance.__enter__()
        # it's already on the screen, with the spinner alive!

    def update(self, current_count, total):
        self.bar(current_count / total)   # update the progress bar manually
        if current_count == total:  # or other means to detect ending
            self.alive_bar_instance.__exit__(None, None, None)  # finalize alive_bar and prints receipt
```

That's it!
If the interface includes some other method call for finalizing the progress, you can move the last line to inside it (the `if` is not necessary then).

Let me know if that solves it properly... 😉

**Comment by tarcisioe** [comment]
Maybe `contextlib.ExitStack` can help hiding some of the boilerplate and making the code look a bit less arcane? Along the lines of

```
class MyProgressIndicator(BaseClassFromFramework):
    def __init__(self, total_to_process):
        self.exit_stack = ExitStack()
        self.bar = self.exit_stack.push(alive_bar(total_to_process))

    def update(self, current_count, total):
        self.bar()   # update the progress bar
```

And when it's time to stop the bar:

```
    self.exit_stack.close()
```

**Comment by rsalmei** [comment]
Yes, of course it is an option! It is actually to use a variable number of context managers, but could be used with just one for this purpose.
I didn't suggest it because it is for Python 3 only, and prefer solutions that work anywhere.
Thanks.

**Comment by pzelnip** [comment]
Sorry it took so long for me to respond.  Deconstructing it the context manager calls does work.  Thanks!

Wasn't able to get the version using ExitStack to work (Python 3 is fine for me as that's all I use), I think partly as I'm not quite grokking how ExitStack works.

**Comment by rsalmei** [comment]
No problem man, glad to see it did work!
You're welcome 👍
