### ISSUE TITLE
how is the print logging achieved?

### ISSUE THREAD

**Issue by Ahmed-Mokhles** [rsalmei/alive-progress#53]
hello @rsalmei 
i hope you're having a pleasant day.

after playing around with your (awesome) library for a bit, i decided to try and create my own, much simpler approach with less features.
my rewrite of this library turned out super lightweight (only about 100 lines of code) but there is one feature that is missing, which i'd love to implement, and its the logging messages that are printed along with any print statement:

`on 10: log message`

at first i thought the simplest method would be to create my own alternative to the print function that could be used by the user, but its nowhere near as cool, and kind of messy.
however, i couldn't figure out how to implement the "enrich print" feature.

i tried reading your source code to figure out how you implemented it, but with no luck. i found `install_logging_hook()`, which then i traced was called from `start_monitoring()`, but i just could not wrap my head around how both worked.

so, i hope its not much to ask for, but could you possibly briefly explain how i could implement it in a single script? or maybe even provide a code snippet that i could add to the beginning of my python script?

thank you very much in advance.

**Comment by Ahmed-Mokhles** [comment]
i figured it out! (i think)

```
import sys

print("message before")    # this is before the hook is activated

class hook:    # define a hook class with functions "write" and "flush"
    def write(text):    # this function print the decorated text
        if text != "\n":
            text = f"log: {text}\n"

            sys.__stdout__.write(text)

    def flush():    # this function will flush the buffer
        sys.__stdout__.flush()

restore = sys.stdout    # this allows you to restore the stdout later
sys.stdout = hook    # now you replace the normal stdout with your hook

print("hook activated")    # after the hook is activated

sys.stdout = restore    # now stdout is back to normal

print("hook deactivated")
```

the output:

```
message before
log: hook activated
hook deactivated
```

if you think this could be improved, please comment your thoughts, and thank you for an awesome library!
cheers

**Comment by rsalmei** [comment]
Hello @Ahmed-Mokhles, thank you man.
I can't really say I understand you think it's an awesome library, but yet decide to create your own... Is it for the sake of learning, fun or what?

Well, regarding the print hook, you got the basics! It should be similar to a python stream, I've implemented it with closures, you with a class.
I'm finishing the `alive-progress` v2, which has a much more advanced implementation, which supports the logging framework and files. You can take a look at that in #51.

Best,
Rogério.

**Comment by Ahmed-Mokhles** [comment]
it truly is an amazing library! and yes, both for learning and fun! the idea of having a progress bar in a terminal was always intriguing to me, and now I can finally see it being made with my own two hands, thanks to inspiration from your awesome library!

as for the print hook, im glad i got it right.

and i'm looking forward to v2...

thanks again! and best of luck.

**Comment by rsalmei** [comment]
Thank you, to you too!
