### ISSUE TITLE
What's shell and theme you using?

### ISSUE THREAD

**Issue by rainzee** [rsalmei/alive-progress#54]
Hi, You done a great job. I very enjoy using alive-progress. It is very elegant and makes my whole program more intelligent. At the same time, I also noticed that the command line tools you used in the demonstration are very beautiful. I saw that you said that you are using fish. I want to know what program you use, what theme, and configuration. Thanks again

**Comment by rsalmei** [comment]
Hey @rainzee, thank you very much.

Where have you seen the shell I use? And the theme, I don't recall where I did show them.

Anyway, I've stopped using fish, it was annoying me the lack of compatibility with POSIX, and even it using simpler commands, it is another dialect to learn...

I'm using zsh now, with oh-my-zsh and p10k as theme inside iTerm2. Using the right combination of plugins, I've achieved the same usability features as fish, with total compatibility with bash.

I like them very much, and recommend them!
My current shell:
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/6652853/93643734-f52e6f00-f9d6-11ea-9cb5-2b5bef9df862.png">

Regards,
Rogério.

**Comment by TheTechRobo** [comment]
I think he meant the 

[In]: print("foo")
[Out]: foo

**Comment by rsalmei** [comment]
Hey @TheTechRobo, thanks.

Initially I thought exactly that! The "command line tools" he was referring to.
But when he mentioned "fish" it settled to me it should be a shell...

Anyway, if it is really that, it is the very cool `ipython`! Just `pip install ipython` and you're good to go.
There's another one I like called `bpython`, also just `pip install bpython` and be happy.

You'll never use pure python again... 👍

**Comment by TheTechRobo** [comment]
will try out later, thanks! :D

**Comment by rsalmei** [comment]
You're welcome!
