### ISSUE TITLE
Tell me please  how to get rid of "on 0", "on 1" ...

### ISSUE THREAD

**Issue by Dinamos** [rsalmei/alive-progress#58]
import alive_progress
ii = [100,1,2,3,5,8,6,7,1,10]
with alive_progress.alive_bar(len(ii), title='Copy', length=25, spinner="classic") as bar:
...     for k in ii:
...         print(str(k))
...         bar()
...         
on 0: 100
on 1: 1
on 2: 2
on 3: 3
on 4: 5
on 5: 8
on 6: 6
on 7: 7
on 8: 1
on 9: 10
Copy |█████████████████████████| 10/10 [100%] in 0.0s (0.00/s)

**Comment by TheTechRobo** [comment]
Are you using a python interpreter?If so, that's your problem. run it directly in a script.

also, next time please format your code (before the first line put \`\`\`, after the last line put \`\`\`)

**Comment by rsalmei** [comment]
Hello @Dinamos,

It's on the README, just include `enrich_print=False` in alive_bar parameters, it is enabled by default.

And yeah, please format your code, it's a mess to understand it that way.
