### ISSUE TITLE
Doesn't work in IDLE

### ISSUE THREAD

**Issue by JoepTM** [rsalmei/alive-progress#60]
I tried to run the basic example but it doesn't work, i get this errors:
![image](https://user-images.githubusercontent.com/66672754/99276385-e6283980-282c-11eb-8c51-291587c18471.png)

Does someone know how to fix it?

**Comment by rsalmei** [comment]
Hey man, that is very odd. Is your system saying that `sys.__stdout__` is `None`?
That does not make sense.
Which platform are you using? What code did you try?

**Comment by JoepTM** [comment]
i have windows

**Comment by rsalmei** [comment]
Yeah, I had already seen that, given the paths "C:"...
I need more than that. How did you run your program? Which terminal do you use? Are you using Windows Subsystem for Linux?

**Comment by JoepTM** [comment]
I run it just in the normal python shell
![image](https://user-images.githubusercontent.com/66672754/99304436-a7a57580-2852-11eb-98c1-c85272a9412d.png)

Or do i have to use it in ascciinema

**Comment by rsalmei** [comment]
What do you mean by "normal python shell"?
Please describe exactly which way have you used to run it.

**Comment by JoepTM** [comment]
The code is on the left side and the shell is on the right side, i use Python 3.9.0
![image](https://user-images.githubusercontent.com/66672754/99353640-35aa4c00-28a5-11eb-9fa7-2815f1e68d8f.png)

If i run the program i get the error on the left side of my screen.

**Comment by rsalmei** [comment]
I still didn't see how you ran the code.
How do you enter this "Python Shell" and ran Progress.py?

**Comment by JoepTM** [comment]
on the top of the editor is run 
![image](https://user-images.githubusercontent.com/66672754/99413467-1b4c8e80-28f6-11eb-97c8-307cac68e0ed.png)
Hover iver that and then run module
then i get that error

**Comment by rsalmei** [comment]
Hummm, ok, I really have never seen this shell.
And this whole Python Shell, how did you run it? Is it an icon on your desktop?

**Comment by TheTechRobo** [comment]
I recognize that - that's IDLE.

It comes standard with the default installation iirc.

Joep, next time please be more specific...

**Comment by JoepTM** [comment]
Okay, sorry. But i didn't know that there were multiple python shells

**Comment by rsalmei** [comment]
Ohhh now I see it, thank you @TheTechRobo!!

@JoepTM, that's not actually "the" Python shell, it's a program in Python that happens to run Python programs, used for learning purpose only.

I've never tried it, and can't possibly know what it does differently internally.
What I do know is that `alive-progress` uses some pretty advanced inner workings of Python, that probably are not available inside IDLE.

I strongly recommend installing `iPython`, it's an incredible REPL for any Python use.
Just `pip install ipython` in your shell, and then `ipython`.

For windows, I'd also recommend installing WSL "Windows Subsystem for Linux", which is amazing.

**Comment by JoepTM** [comment]
Okay, i'll try it tomorrow, thanks.

**Comment by JoepTM** [comment]
it worked thanks!!
