### ISSUE TITLE
?25l instead of "notes2" as spinner

### ISSUE THREAD

**Issue by kallewesterling** [rsalmei/alive-progress#64]
Running the following script causes the bar to not show up in VSCode's environment on an M1 mac mini:

```py
with alive_bar(len(df), spinner = 'notes2') as bar:
    for row in df.fillna('').itertuples():
        ...
```

Here's what it looks like:

![image](https://user-images.githubusercontent.com/7298727/103426414-627d9e80-4b87-11eb-996e-5aef3e076844.png)

```console
[?25l[?25h|⚠                                       | (!) 0/7492 [0%] in 4.8s (0.00/s)
```

**Comment by rsalmei** [comment]
Hey @kallewesterling, it seems to me there's two different issues.
You probably forgot to call `bar()` inside the loop, that's why it finished with 0, and didn't fill up at all.
But regarding the `[?25l` and similar symbols, that's the control characters used to beautify the output, they should make the cursor disappear, what it seems your vscode is not doing, I can't imagine why.
Mine does:
<img width="641" alt="image" src="https://user-images.githubusercontent.com/6652853/103440485-dd48c700-4c24-11eb-9508-ccc42d237f53.png">

I know I didn't change anything regarding interpreting control characters, both in vscode and in iterm2. Do you?
I'm in a macbook 16 with Big Sur.

**Comment by kallewesterling** [comment]
Heya @rsalmei -- I did forget to add the `bar()` - you're right! But even after doing that, when I _run the code_ - i.e. not in the terminal but rather with "output" in VS Code, or to be clear, by clicking the "play" button in the upper right corner, this happens...

![image](https://user-images.githubusercontent.com/7298727/103491545-bcce6780-4df2-11eb-807c-add379d3f8e7.png)

However, you're right - with `bar()` in the right place, the terminal side of VS Code, at least, shows the right thing! Thanks!

**Comment by rsalmei** [comment]
Nice! You're welcome @kallewesterling 

But I'm still very puzzled regarding the control characters... We are both on a macOS, so no Windows involved, which seems to cause problems with these.
My vscode interprets these chars, it simply has always worked! Why wouldn't yours? 🤔

**Comment by kallewesterling** [comment]
Testing on my other machine (a 2014 MacBook Pro 13") to see if I get the same error.

My Python runs on an `anaconda` installation, so maybe that has something to do with it? 🤔

**Comment by kallewesterling** [comment]
Looks like there is something wrong with the std output for this window in VS Code perhaps. Hm!

![test-py-giphy-640](https://user-images.githubusercontent.com/7298727/103723759-c4337380-4fa0-11eb-8ce0-814fa733b01e.gif)

As I said above, when I run it in the `terminal` part of VS Code, I have no trouble with the output:

![test-py-terminal-640](https://user-images.githubusercontent.com/7298727/103723956-3ad07100-4fa1-11eb-868b-cc2878541a62.gif)

**Comment by rsalmei** [comment]
Hey, that's weird. I've made this same file.
But when I click 
<img width="104" alt="image" src="https://user-images.githubusercontent.com/6652853/104074750-a3149200-51ef-11eb-9b31-e4ca7c29ef21.png">, regardless of what tab I left selected, it goes to Terminal and runs it there...

I don't know why yours would run in this Output, mine has only internal vscode stuff.
But `?25l` and other control sequences I think would really never work inside anything but a terminal. Only console terminals implement these protocols.

**Comment by rsalmei** [comment]
I'll close this one, let me know if I can help you with anything else 👍

**Comment by kallewesterling** [comment]
Yeah, no worries. I'll see what strangeness causes that to happen in my VS Code and not yours!

**Comment by rsalmei** [comment]
Ok, please report back if you find anything.
