### ISSUE TITLE
How about adding color, rainbow?

### ISSUE THREAD

**Issue by hongquan** [rsalmei/alive-progress#65]
I found that this library is pretty cute, make me laugh at first glance.
Do you have plan to add color, rainbow to the progress bar also?

**Comment by rsalmei** [comment]
Hey man, thank you I think 😂.

Yeah, I do think about adding colors, but it's way more difficult than it seems to...
I've described a little what it takes to implement that, take a look: #49
You'll see it's very very hard. 

I am working on another big feature for about 6 months, to support grapheme clusters like these!!
So It's at least a little colorful 😄:
```python
    balls = scrolling_spinner_factory('🏀🏈🏉🏐🏓⚾️🥎⚽️🧶🎾🎱', 3, 1)
    flora = bouncing_spinner_factory('🌱🌲🌳🌴🌵🌾🌿🍀🍁🍂', 8)
    fruits = bouncing_spinner_factory('🍎🍍🍌🍋🍊🍉🍈🍇🍅🍓🍒🍑🍐🍏', 10, hide=False)
    flowers = bouncing_spinner_factory('💐🌷🌸🌹🌺🌻🌼', block=3)
    elements = bouncing_spinner_factory(('🔥💨', '🌊⚡️'), 6, 2)
```
I should release it soon in the 2.0, more info in #51

**Comment by hongquan** [comment]
Thanks.
