### ISSUE TITLE
Eta does not use a running average

### ISSUE THREAD

**Issue by Tobias-Braun** [rsalmei/alive-progress#67]
### Problem

When using the progress bar to display tasks with a great number of iterations that take much time, the simple eta calculation suffers from various problems, causing the displayed eta to greatly differ from the expected one:

1. For tasks displayed that involve networking, connection speed of both the client and server can vary greatly during the execution.
2. Computational tasks can be sped up over time by memoization or other effects.
3. Tasks can also be slowed down due to less RAM being available over time
4. Caching, as well as loads and saves can significantly change the execution time of some iterations or iteration intervals. Especially, when for example for a first section of a data array, the data is already processed, while for the other sections, significantly more processing time is required.

### Proposal

Implement a running average calculation strategy and provide a parameter for users to set the eta calculation strategy (for example in the contructor of the alive_bar)

The running average could be implemented using a simple sliding window (average over the last n values, where n is a constant or a fraction of the total)
On each call to bar(), a new value is added consisting of the current running time and the current progress (int/float, depending on the mode).
Another approach would be to calculate the average at each step and accounting for the last average with a discount factor slightly smaller than 1 (for example 0.98): sliding_average_at_step = (average_at_step + discount_factor * previous_sliding_average) / (1 + discount_factor).

The calculation above would result in a sliding_average calculated in O(1) that includes the averages of all previous steps weightened depending on how many steps ago they were. Therefore, I'd recommend the latter approach or maybe both.

I'm eager to hear opinions on the issue, and if wanted, I can also try to implement the functionality and provide a pull request.

**Comment by rsalmei** [comment]
Hey @Tobias-Braun, very nice write-up, thanks!

Yeah, I do agree.
In the current 1.6 version, I did release an exponential smoothing of the ETA data, have you seen it?
It is a dual generator, which receives the current position and the rate, and yields the smoothed value.
Here it is: https://github.com/rsalmei/alive-progress/blob/master/alive_progress/core/timing.py#L28-L53
What do you think of it?

I've used a hard-coded alfa constant of .5, which I tested manually and found it to be the best all around.
I didn't want to externalize it to the user to not clutter de README and make it more difficult to use.
It is here: https://github.com/rsalmei/alive-progress/blob/89a2f65c011d5d00a9162d0e313b077b408a9c86/alive_progress/core/progress.py#L217-L219

In this moment, which I have a very bit PR opened for the new major version 2.0, I would prefer to implement it myself, or postpone it until it is released. But I'm keen to have this feature the best it could be! 👍

**Comment by Tobias-Braun** [comment]
Yeah, I've seen it after I forked your repo. Digged a bit into it and found it beeing harder than I thought. The exponential smoothing was exactly like my idea, but I would use it with an average per step rather than the average for the total run.

Found out that a bit of refactoring would be needed, as the average (the per second) text should change according to the eta.
I've implemented it, tested and changed it and it is okay'ish for my use case but definetly not perfect. If you want, I can link it to you for reference.

**Comment by rsalmei** [comment]
Hey @Tobias-Braun, have you tested this on the newest 3.0, does this issue still apply?
Also, I'd like you to see #215, which might make an even bigger effect on ETA.

**Comment by Tobias-Braun** [comment]
Hey @rsalmei, sorry I have not tested anything with the latest versions as I am currently not using the library anymore. However, I remember that my problem here was a very special case.

**Comment by rsalmei** [comment]
Ok, no problem.
In that case, I'm going to close this one, but feel free to reply here if you want.
