### ISSUE TITLE
Docs: alive-progress compared with tqdm

### ISSUE THREAD

**Issue by clbarnes** [rsalmei/alive-progress#69]
tqdm is arguably the gold standard in python progress bars: it's very commonly used and feature-rich. My first question when finding this project was "I wonder what benefits this has over tqdm?", and I strongly suspect I'm not alone.

As many people coming to this project will be familiar with tqdm (and some may dismiss it as their progress needs seem to be already fulfilled), it'd be really helpful to have a comparison. For example, handling the `print`/`logging` output by default is a massive selling point of alive. It would also let you set out tqdm features which are or are not on your roadmap (and/or ask for contributions).

**Comment by rsalmei** [comment]
Hey @clbarnes,

Seems like an interesting idea, the problem is I don't know tqdm very much myself.
I've never used it, just read a little when someone once asked about a feature available there.
All features here in `alive-progress` are original ones, which I wanted to use at some point.

Anyway, I'd be willing to do that, but I'd need help. What would be the key features and shortcomings of tqdm?

**Comment by TheTechRobo** [comment]
I'll check it out sometime. No promises though :P

**Comment by rsalmei** [comment]
Ok, closing this one as also stale.

If someone would make a starting table with the others' features and shortcomings, I could insert my own points in it.
But I won't study another, similar project, just to compare to mine.

Besides, no other project I think is studying mine to compare them. Unfortunately, I think this is the user's option to compare and choose which one better suits his needs.

(Personally, I'd just look at these to form my opinion, I love how fluid `alive-progress` is, if I say so myself. 😊 
I would only use another project at all, if I absolutely desperately need it.)
![main](https://github.com/rsalmei/alive-progress/raw/main/img/alive-demo.gif)
![print-hook](https://github.com/rsalmei/alive-progress/raw/main/img/print-hook.gif)
![spinners](https://github.com/rsalmei/alive-progress/raw/main/img/showtime-spinners.gif)
