### ISSUE TITLE
Feature request: spinner only

### ISSUE THREAD

**Issue by lsorber** [rsalmei/alive-progress#72]
Would be great to be able to render alive-progress's spinners only, similar to [click-spinner](https://github.com/click-contrib/click-spinner)'s:

```python
with click_spinner.spinner():
    do_something()
    do_something_else()
```

**Comment by TheTechRobo** [comment]
Possibly related: #56

> In unknown mode, there is currently no way to disable either the unknown bar and/or the spinner. It's very distracting to show two animations in the unknown mode when only one of the animations is enough. If we're able to show only one animation (unknown or spinner), it would look more professional.

**Comment by lsorber** [comment]
Would v2.0 also allow you to render the spinner at the current cursor position (i.e. without printing a newline)?

**Comment by TheTechRobo** [comment]
I'm not sure, you'd have to wait for the maintainer's response.

**Comment by rsalmei** [comment]
Hey, @lsorber, you can! This was first requested in #40.
At least you will, as soon as I release #51...

Thanks @TheTechRobo, I appreciate your help in several tickets! 👍 

This should also interest @engineerjoe440!
I just implemented support for disabling:
- the monitor widget! => the part that shows where you are, "x/y [z%]" for example
- the stats widget! => the part that tracks speed, "(x/s, eta: ys)" for example
- the elapsed widget! => of course the "in xs"

How cool is that!?! 🎉 

So in the next 2.0, you will get to do:

https://user-images.githubusercontent.com/6652853/104136223-98830580-5373-11eb-8488-3ab9b3e07e10.mov

Or even something like this:

https://user-images.githubusercontent.com/6652853/104136352-47bfdc80-5374-11eb-9707-10895ec7392c.mov

**Comment by rsalmei** [comment]
> Would v2.0 also allow you to render the spinner at the current cursor position (i.e. without printing a newline)?

I think this is not possible "as you say". I cannot read the current cursor position, to reposition it there afterwards.
But as I've shown above, you could set a `title` with any text you want, and draw the spinner besides it.

**Comment by rsalmei** [comment]
Hey, to simulate exactly `click-spinner` does, you just:

https://user-images.githubusercontent.com/6652853/104136844-768b8200-5377-11eb-8e1f-859eca6e2a50.mov

**Comment by rsalmei** [comment]
I couldn't resist 😂 

https://user-images.githubusercontent.com/6652853/104136931-fc0f3200-5377-11eb-80a3-a1ff0e91b68b.mov


Remember all the other bells and whistles of `alive-progress` are active, like hide cursor support, which the other doesn't have...

**Comment by lsorber** [comment]
Looks great, thank you @rsalmei! (Apologies I didn't search before submitting this issue.)

**Comment by rsalmei** [comment]
No problem man!
