### ISSUE TITLE
Can't use alive-progress in for loop?

### ISSUE THREAD

**Issue by TheTechRobo** [rsalmei/alive-progress#77]
Just installed alive-progress with pip.

![image](https://user-images.githubusercontent.com/52163910/105425987-59c53900-5c18-11eb-8346-1b41f3a3eb33.png)

This is with the Python interpreter, the one that comes with debian.

BTW: Are you going to make a branch from the master branch that will have the 1.x code so you can still make bugfixes ?

**Comment by rsalmei** [comment]
Hey man, there's no bug in there, you just sent an integer to the `bar.text()` method...
That position is already inside the bar, but if you do want to put in the text section, you can `bar.text(str(i))`

**Comment by TheTechRobo** [comment]
Ahhh, I feel stupid now hehe. Thanks. :)
