### ISSUE TITLE
When I reduced the size of the window in WIN10, it crashed.

### ISSUE THREAD

**Issue by a76yyyy** [rsalmei/alive-progress#84]
![error](https://user-images.githubusercontent.com/56478790/115671247-e51bab00-a37c-11eb-8dbc-f2ad4bd734b9.gif)

**Comment by TheTechRobo** [comment]
Is this reproducible? Can you do it again? Which version is having this issue - 1.x or 2.x? If in 2.x, try 1.x, and if in 1.x, try it in 2.x.

**Comment by a76yyyy** [comment]
> Is this reproducible? Can you do it again? Which version is having this issue - 1.x or 2.x? If in 2.x, try 1.x, and if in 1.x, try it in 2.x.

This phenomenon is reproducible. And the package version is the latest.
What does it mean to try 2.x?

**Comment by a76yyyy** [comment]
> Is this reproducible? Can you do it again? Which version is having this issue - 1.x or 2.x? If in 2.x, try 1.x, and if in 1.x, try it in 2.x.

This phenomenon is reproducible. And the package version is the latest.
What does it mean to try 2.x?

**Comment by TheTechRobo** [comment]
There is currently a work-in-progress huge update called 2.0.

Could you see if the error is reproducible on there? The Pull-request is #51. Clone that branch, install it, and see if the error is still there.

**Comment by TheTechRobo** [comment]
I can't reproduce this in the Crostini terminal on ChromeOS, so this seems to be a Windows-specific bug.

**Comment by a76yyyy** [comment]
> I can't reproduce this in the Crostini terminal on ChromeOS, so this seems to be a Windows-specific bug.

I think so. When I use 2.x, it is still reproducible. 
I suggest to define a maxcol variable to solve this bug:
`maxcol = os.get_terminal_size().columns`

**Comment by TheTechRobo** [comment]
Thanks for that further information,
@rsalmei will appreciate it. :) 
He is a little busy though (he 
apparently has a new job) so
he might not get back right away.

**Comment by rsalmei** [comment]
Hello there!

Yes, I do appreciate! :) Thanks @TheTechRobo 
Yeah, new job, using a new and super complex language (Rust), but I'm digging it.

But actually I can't see the crash @a76yyyy, your image stops right where it was needed...
Is there any exception on screen? Are you sure it's `alive_progress` that crashes, or could it be the ipython process?
Please post an image with the actual error, or with the exception.

**Comment by rsalmei** [comment]
Also, please try the first two responses from here: https://stackoverflow.com/questions/12492810/python-how-can-i-make-the-ansi-escape-codes-to-work-also-in-windows
I'd like to know if that `os.system('color')` and/or `colorama.init()` do work, so just put them in the same file, before anything.

Also, if you can I'd recommend installing WSL (Windows Subsystem for Linux), which is awesome.

**Comment by rsalmei** [comment]
Hello @a76yyyy.

Analyzing your gif, it really doesn't have any problem. Look, in one before last we see that the screen is about to wrap:
![image](https://user-images.githubusercontent.com/6652853/116945965-4ed66780-ac4f-11eb-852d-fc7d3f5bcfed.png)

When it does, the terminal scrolls all content up, and when the next refresh of `alive_progress` comes in, it is printed on the next line:
![image](https://user-images.githubusercontent.com/6652853/116946013-762d3480-ac4f-11eb-815a-058573072c3c.png)

So, there's nothing unexpected in there.
I really need to see what you say happens after it... A crash or exception.

**Comment by a76yyyy** [comment]
> Hello @a76yyyy.
> 
> Analyzing your gif, it really doesn't have any problem. Look, in one before last we see that the screen is about to wrap:
> ![image](https://user-images.githubusercontent.com/6652853/116946135-bf7d8400-ac4f-11eb-9beb-f5f802d9d565.png)
> 
> When it does, the terminal scrolls all content up, and when the next refresh of `alive_progress` comes in, it is printed on the next line:
> ![image](https://user-images.githubusercontent.com/6652853/116946144-c6a49200-ac4f-11eb-81b9-274e73b04b11.png)
> 
> So, there's nothing unexpected in there.
> I really need to see what you say happens after it... A crash or exception.

In fact, the process or terminal crashed when I dragged the side of the terminal, so that I could not know whether the module raised an exception

**Comment by rsalmei** [comment]
I see, but no Python program can ever make its interpreter crash like that.
I think it's probably the ipython or the terminal itself that crashed, regardless of what was running in them.

Please try this, with nothing running on the terminal but WITH data play with it's size.
Run like a `dir /?` I don't recall the dir params, but try to fill the screen with text and make it wrap and return.

Then enter ipython, run this, and play again:
```python
from itertools import cycle
from shutil import get_terminal_size
import time

asd = cycle('12345')
print('\033[s')  # <-- saves the cursor position
while 1:
    x = get_terminal_size().columns
    # clear till the end of screen, and restores cursor
    print('\033[J\033[u' + (next(asd) * x) + '\r', end='')
    time.sleep(1/60.)
```

**Comment by rsalmei** [comment]
> I think so. When I use 2.x, it is still reproducible.
> I suggest to define a maxcol variable to solve this bug:
> `maxcol = os.get_terminal_size().columns`

I didn't understand this response of yours.
1. How did you come to this conclusion, if we don't even know what is this "bug"?
2. Why do you think this would solve it?

**Comment by a76yyyy** [comment]
In my opinion, it should at least be as effective as the example without causing the terminal to crash.
![thought](https://user-images.githubusercontent.com/56478790/117122408-7a309200-adc8-11eb-9c39-614c5903e83b.gif)
```python
import time,sys,os
is_alive = True
rop,maxcol = 0,os.get_terminal_size().columns
while is_alive:
    tmp = os.get_terminal_size().columns
    if tmp != maxcol:
        time.sleep(0.2)
        maxcol = tmp
        continue
    if 0 <= rop < 100:
        print("\r[%s%s]%3d%%" % ( ">" * int(rop/100*(maxcol-8)), " " * int((100-rop)/100*(maxcol-8)), rop), end='')
        sys.stdout.flush()
        rop += 1
    else:
        print("\r[%s]%3d%%" % ( ">" * int(maxcol-8), rop))
        rop = 0
    time.sleep(0.1)
```

**Comment by rsalmei** [comment]
Humm, cool example, but I need help to pinpoint the problem.
What is the trigger of this crash?
In this example, you stop updating at all if moving, I don't feel that would be it.

Could you:
1. try the two codes I posted above?
2. remove the whole `if tmp != maxcol:` block from your example, and try again?

**Comment by a76yyyy** [comment]
> Humm, cool example, but I need help to pinpoint the problem.
> What is the trigger of this crash?
> In this example, you stop updating at all if moving, I don't feel that would be it.
> 
> Could you:
> 
> 1. try the two codes I posted above?
> 2. remove the whole `if tmp != maxcol:` block from your example, and try again?

1.The code you posted did not crash.
2.When I remove the whole `if tmp != maxcol:` block, the screen display is as follows:
![error1](https://user-images.githubusercontent.com/56478790/117625484-a5d8c100-b1a8-11eb-951b-7fe9e2c6d5ab.gif)

**Comment by rsalmei** [comment]
Hey, is there any news here?
I still cannot pinpoint what the problem is, I need more info/examples/a way to simulate it.

**Comment by rsalmei** [comment]
Ok, closing this as stale. Let me know if anything new arises.
