### ISSUE TITLE
Failed to show up on Jupyter notebook.

### ISSUE THREAD

**Issue by ssghost** [rsalmei/alive-progress#86]
I imported "alive_bar" function in a Jupyter notebook code block, and write a test code like below:
```python
from alive_progress import alive_bar
  with alive_bar(100) as bar:
        for i in range(100):
            time.sleep(.03)
            bar()
```
After this, hit "run" button, nothing showed up, the status shows this code block is already done.

Do I need to add some more commands before running the code to force the function to display all its effects on Jupyter notebook?

**Comment by TheTechRobo** [comment]
Related: #16. Alive-Progress as far as I know does not support Jupyter Notebook.

**Comment by rsalmei** [comment]
Yeah, that's exactly it.
Unfortunately jupyter notebooks do not work in a terminal, and do not support terminal applications. They have a graphical user interface, with graphical widgets.
To interact with that, it's needed a completely different bar implementation, drawing the aforementioned widgets via [ipywidgets](https://github.com/jupyter-widgets/ipywidgets) e [ipycanvas](https://github.com/martinRenou/ipycanvas).
I do want to support that some day, but I'd need help, some frontend maybe? I don't know any frontend stuff...

Yeah @TheTechRobo, that thread ended up being in Brazilian Portuguese... 👍

**Comment by rsalmei** [comment]
Closing this one.

**Comment by thorstenkampe** [comment]
TQDM has superb Jupyter [notebook integration](https://github.com/tqdm/tqdm#ipython-jupyter-integration). Maybe that could get Alive-Progress started?!

**Comment by rsalmei** [comment]
Yeah, I know it does @thorstenkampe, thanks.
Actually, I wouldn't call that a notebook "integration", it's another implementation of a progress bar, with an interface resembling the original, as a jupyter widget.
The goal in tqdm is just to see a process, the goal here is to see it _in style_. Tqdm only updates the bar passively, when there's any change. Here I refresh the bar dynamically, from 4 up to 60 frames per second based on the processing speed, and I don't know if that would even be supported in notebooks...
So, It's not an easy task at all.

Anyway, I did a quick look at their code, and it does not even draw the actual bar, it uses an internal ready-to-use component of ipywidgets:

https://github.com/tqdm/tqdm/blob/master/tqdm/notebook.py#L47

So, perhaps it really wouldn't be so hard to support something like it, using that same approach.
It surely wouldn't support all the bells and whistles that `alive-progress` does have, but it would be ok as an MVP...
Thanks 👍.
