### ISSUE TITLE
Unsupported Unicodes on Windows 10

### ISSUE THREAD

**Issue by pranjal-joshi** [rsalmei/alive-progress#88]
Hello,

My code with `smooth` bar and `waves` spinner works well on **Ubuntu.**

However, the same code on **Windows 10** shows incorrect output due to the Unicode issue.

![alive_issue](https://user-images.githubusercontent.com/6128978/119837706-7653e380-bf20-11eb-8f33-3f0e5ec6adad.png)

**Please suggest a workaround for this!**

**Comment by rsalmei** [comment]
Hello @pranjal-joshi,

Yeah, those square blocks are weird, but it's odd.
I had a similar question recently, that on Windows it wasn't showing control characters, but Unicode was OK (in #83)...
Which font are you using on your terminal? Are you sure it does contain Unicode chars?

**Comment by pranjal-joshi** [comment]
Thanks for the quick help!

I went through #83.
Currently, I am using `Monaco` font with my Command Prompt. However, I tried all of the font option available for cmd but everytime I am getting different kind of blocks but not the desired result.

**Comment by TheTechRobo** [comment]
Could you try it in the new windows terminal?

The square blocks typically mean it's not a good font. Try installing a [nerd font](https://www.nerdfonts.com/).

**Comment by rsalmei** [comment]
Yes, that's a great suggestion! I use nerd fonts myself, have several installed like Hack, FiraCode, Source Code Pro, Dejavu, VictorMono, etc.
These fonts should always have all exotic characters you'd ever need.

**Comment by pranjal-joshi** [comment]
@rsalmei @TheTechRobo 

I'm shipping my application binaries using `pyinstaller`.
Is it possible to ship one of the Nerd Font with it and automatically set it console font?

**Comment by TheTechRobo** [comment]
I don't think so, unless you bundle a full-on terminal with it. :/

Font choice is set by the console, not the program, sadly.

**Comment by pranjal-joshi** [comment]
Sure! I will try more about packing font in the executable. I will update if I found a way to do it.
meanwhile, I just use the following code to avoid bad-looking blocks:
```
    import platform
    bar = 'smooth'
    spinner = 'waves'
    if 'Windows' in platform.platform():
        bar = 'classic2'
        spinner = 'dots_recur'
    with alive_bar(numStocks,bar=bar,spinner=spinner) as progressbar:
        # Do some stuff here
        progressbar()
```
