### ISSUE TITLE
ETA as Input (Feature)

### ISSUE THREAD

**Issue by jacobian91** [rsalmei/alive-progress#89]
I may have missed it, but I haven't been able to find this functionality in `main` or `2.0`.

We have a case where we have a long single step (HTTP post). Currently in `main` I'm trying an unknown spinner, and adding the title "ETA 50seconds".  It would be great to input an ETA like: `with alive_bar(eta=50,...) as bar:`

**Comment by TheTechRobo** [comment]
That makes sense, since sometimes you don't want alive-progress to handle it, and also unknown mode can still work with it, for example if it is searching through directories, it might be done 90% of the changes and you can assume that it is only a small amount of time left (relatively), and so even in unknown mode ETA can be useful. Agree fully!

**Comment by jacobian91** [comment]
Another feature would be to add the ability to make a standard progress bar (not an unknown spinner) and make it purely time-based and need to call `bar()` only once.

**Comment by jacobian91** [comment]
The problem with manual mode is I still have to call `bar()` multiple times. A simple example of my use-case would be where a single line of python code is called that takes time to complete and only is called once, e.g. a subprocess call to 'timeout'. 
```python
import subprocess
eta_seconds = 5
with alive_bar(eta_seconds):
    subprocess.run(['timeout','5'])
```

**Comment by rsalmei** [comment]
I don't see any problem in calling `bar()` multiple times. Remember this is the way to make the bar go forward.
I think it'd be very weird to make a progress bar update itself automatically. Any progress bar change should always be a response from an active call by the user.

In your case, I'd create a background thread, and display a cool `alive-progress` being updated every second.
You could use the definite mode as usual, and increment it until the desired time, or even better, you could use the manual mode to make it backward from 50 to 0, clearly indicating to the user it is the expected time remaining!

Can't make much more than this man. Hope it works! 👍
