### ISSUE TITLE
Disabling pbar's output elements (Feature)

### ISSUE THREAD

**Issue by pierre-manchon** [rsalmei/alive-progress#93]
Considering the output of the alive-progress's progress bars:

|####################| 100/100[100%] in 1:33.1 (0.97/s)

It would be awesome to be able to remove or disable some the elements of the output which are printed:

- the total (100/100)
- the percentage ([100%])
- the execution time (in 1.33.1)
- or the iteration time ((0.97/s))

In my opinion that would definitely help customizing even clearer and simpler progress bars. And who can do more can do less !

**Comment by TheTechRobo** [comment]
possible duplicate of https://github.com/rsalmei/alive-progress/issues/62#issuecomment-827952960

**Comment by pierre-manchon** [comment]
Indeed, this is similar to what I had in mind. I'm glad this issue has already been addressed and will be implemented with 2.0.
