### ISSUE TITLE
Unknown Symbols

### ISSUE THREAD

**Issue by SirDankenstien** [rsalmei/alive-progress#96]
![image](https://user-images.githubusercontent.com/52797753/126632214-f588b9c7-cbeb-4d15-baab-12ffcc1a6d05.png)
Running on Windows 10

**Comment by rsalmei** [comment]
Hey @SirDankenstien 

It seems your console's font is missing some characters.
I recently got another issue exactly like this, please take a look there: #88

**Comment by rsalmei** [comment]
Well, please reopen if anything new arises.
